// jsonschema-editor-vue/src/components/molecules/ui/CategoryUiElement.vue
<script setup lang="ts">
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import type { Category } from "@jsonschema-editor/ui-schema";
import UiFormElementResolver from "./UiFormElementResolver.vue";

defineProps<{
  element: Category;
  schema: SchemaNode;
  document?: SchemaDocument;
  readonly?: boolean;
}>();

const data = defineModel<Record<string, unknown>>({ required: true });
</script>

<template>
  <section class="jse-category">
    <h3 v-if="element.label" class="jse-category__title">{{ element.label }}</h3>
    <UiFormElementResolver
      v-for="(child, index) in element.elements"
      :key="index"
      v-model="data"
      :element="child"
      :schema="schema"
      :document="document"
      :readonly="readonly"
    />
  </section>
</template>

// jsonschema-editor-react/src/components/molecules/ui/CategoryUiElement.tsx
import type { Category, UiElement } from "@jsonschema-editor/ui-schema";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";
import { UiFormElementResolver } from "./UiFormElementResolver.js";

export interface CategoryUiElementProps extends UiElementRendererProps {
  element: Category;
}

export function CategoryUiElement({
  element,
  schema,
  document,
  data,
  onDataChange,
  readonly,
}: CategoryUiElementProps) {
  return (
    <section className="jse-category">
      {element.label ? <h3 className="jse-category__title">{element.label}</h3> : null}
      {element.elements.map((child: UiElement, index: number) => (
        <UiFormElementResolver
          key={index}
          element={child}
          schema={schema}
          document={document}
          data={data}
          onDataChange={onDataChange}
          readonly={readonly}
        />
      ))}
    </section>
  );
}
