// jsonschema-editor-examples/src/site/components/molecules/SiteTopbar.vue
<script setup lang="ts">
import type { AppLocale, AppPage, AppStack } from "../../../app-routing";
import BrandLink from "../atoms/BrandLink.vue";
import LocaleSelect from "../atoms/LocaleSelect.vue";
import NavLink from "../atoms/NavLink.vue";
import StackSwitch from "../atoms/StackSwitch.vue";

const locale = defineModel<AppLocale>("locale", { required: true });

defineProps<{
  ui: {
    brandPrefix: string;
    brandSuffix: string;
    topNavAria: string;
    navGetStarted: string;
    navExamples: string;
    navImprint: string;
    stackAria: string;
    localeLabel: string;
  };
  activePage: AppPage;
  ownedStack: AppStack;
  examplesHref: string;
  getStartedHref: string;
  imprintHref: string;
  vueHref: string;
  reactHref: string;
}>();

const emit = defineEmits<{
  openExamples: [];
  openGetStarted: [];
  openImprint: [];
  selectStack: [stack: AppStack];
}>();
</script>

<template>
  <header class="app__topbar">
    <div class="app__topbar-start">
      <BrandLink
        :href="examplesHref"
        :brand-prefix="ui.brandPrefix"
        :brand-suffix="ui.brandSuffix"
        @navigate="emit('openExamples')"
      />
      <nav class="app__topnav" :aria-label="ui.topNavAria">
        <NavLink
          :href="getStartedHref"
          :active="activePage === 'get-started'"
          :label="ui.navGetStarted"
          @navigate="emit('openGetStarted')"
        />
        <NavLink
          :href="examplesHref"
          :active="activePage === 'examples'"
          :label="ui.navExamples"
          @navigate="emit('openExamples')"
        />
        <NavLink
          :href="imprintHref"
          :active="activePage === 'imprint'"
          :label="ui.navImprint"
          @navigate="emit('openImprint')"
        />
      </nav>
    </div>
    <div class="app__topbar-actions">
      <StackSwitch
        :switch-aria-label="ui.stackAria"
        :owned-stack="ownedStack"
        :vue-href="vueHref"
        :react-href="reactHref"
        @select="emit('selectStack', $event)"
      />
      <LocaleSelect v-model="locale" :label="ui.localeLabel" />
    </div>
  </header>
</template>

// jsonschema-editor-examples-react/src/site/components/molecules/SiteTopbar.tsx
import type { AppLocale, AppPage, AppStack } from "../../../app-routing.js";
import { BrandLink } from "../atoms/BrandLink.js";
import { LocaleSelect } from "../atoms/LocaleSelect.js";
import { NavLink } from "../atoms/NavLink.js";
import { StackSwitch } from "../atoms/StackSwitch.js";

export interface SiteChromeUi {
  brandPrefix: string;
  brandSuffix: string;
  topNavAria: string;
  navGetStarted: string;
  navExamples: string;
  navImprint: string;
  stackAria: string;
  localeLabel: string;
}

interface SiteTopbarProps {
  ui: SiteChromeUi;
  activePage: AppPage;
  ownedStack: AppStack;
  locale: AppLocale;
  examplesHref: string;
  getStartedHref: string;
  imprintHref: string;
  vueHref: string;
  reactHref: string;
  onLocaleChange: (locale: AppLocale) => void;
  onOpenExamples: () => void;
  onOpenGetStarted: () => void;
  onOpenImprint: () => void;
  onSelectStack: (stack: AppStack) => void;
}

export function SiteTopbar({
  ui,
  activePage,
  ownedStack,
  locale,
  examplesHref,
  getStartedHref,
  imprintHref,
  vueHref,
  reactHref,
  onLocaleChange,
  onOpenExamples,
  onOpenGetStarted,
  onOpenImprint,
  onSelectStack,
}: SiteTopbarProps) {
  return (
    <header className="app__topbar">
      <div className="app__topbar-start">
        <BrandLink
          href={examplesHref}
          brandPrefix={ui.brandPrefix}
          brandSuffix={ui.brandSuffix}
          onNavigate={onOpenExamples}
        />
        <nav className="app__topnav" aria-label={ui.topNavAria}>
          <NavLink
            href={getStartedHref}
            active={activePage === "get-started"}
            label={ui.navGetStarted}
            onNavigate={onOpenGetStarted}
          />
          <NavLink
            href={examplesHref}
            active={activePage === "examples"}
            label={ui.navExamples}
            onNavigate={onOpenExamples}
          />
          <NavLink
            href={imprintHref}
            active={activePage === "imprint"}
            label={ui.navImprint}
            onNavigate={onOpenImprint}
          />
        </nav>
      </div>
      <div className="app__topbar-actions">
        <StackSwitch
          ariaLabel={ui.stackAria}
          ownedStack={ownedStack}
          vueHref={vueHref}
          reactHref={reactHref}
          onSelect={onSelectStack}
        />
        <LocaleSelect label={ui.localeLabel} locale={locale} onLocaleChange={onLocaleChange} />
      </div>
    </header>
  );
}
