// jsonschema-editor-examples/src/site/components/molecules/SiteFooter.vue
<script setup lang="ts">
defineProps<{
  copyright: string;
  imprintLabel: string;
  imprintHref: string;
  imprintActive?: boolean;
}>();

const emit = defineEmits<{
  openImprint: [];
}>();
</script>

<template>
  <footer class="app__footer">
    <p class="app__footer-copy">{{ copyright }}</p>
    <a
      :href="imprintHref"
      class="app__footer-link"
      :aria-current="imprintActive ? 'page' : undefined"
      @click.prevent="emit('openImprint')"
    >
      {{ imprintLabel }}
    </a>
  </footer>
</template>

// jsonschema-editor-examples-react/src/site/components/molecules/SiteFooter.tsx
interface SiteFooterProps {
  copyright: string;
  imprintLabel: string;
  imprintHref: string;
  imprintActive?: boolean;
  onOpenImprint: () => void;
}

export function SiteFooter({
  copyright,
  imprintLabel,
  imprintHref,
  imprintActive,
  onOpenImprint,
}: SiteFooterProps) {
  return (
    <footer className="app__footer">
      <p className="app__footer-copy">{copyright}</p>
      <a
        href={imprintHref}
        className="app__footer-link"
        aria-current={imprintActive ? "page" : undefined}
        onClick={(event) => {
          event.preventDefault();
          onOpenImprint();
        }}
      >
        {imprintLabel}
      </a>
    </footer>
  );
}
