// jsonschema-editor-vue/src/components/templates/JsonSchemaForm.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import { registerDefaultControls } from "../../registry/register-defaults.js";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import type { JseI18nOptions, JseLocale } from "../../i18n/types";
import UiElementRenderer from "../molecules/ui/UiElementRenderer.vue";
import { resolveJseI18nOptions, setupJseI18n } from "../../composables/useJseI18n";
import {
  setupFormValidation,
  type FormValidationMode,
} from "../../composables/useFormValidation";
import { setupJseVueExtensions, type JseVueExtension } from "../../registry/vue-extension";

const props = withDefaults(
  defineProps<{
    schema: SchemaDocument;
    uiSchema: UiSchema;
    readonly?: boolean;
    locale?: JseLocale;
    fallbackLocale?: JseLocale;
    messages?: JseI18nOptions["messages"];
    translate?: JseI18nOptions["translate"];
    extensions?: JseVueExtension[];
    validation?: boolean;
    validationMode?: FormValidationMode;
  }>(),
  {
    validation: true,
    validationMode: "blur",
  },
);

const emit = defineEmits<{
  submit: [payload: { valid: boolean }];
  validated: [payload: { valid: boolean }];
}>();

setupJseI18n(() => resolveJseI18nOptions(props));
setupJseVueExtensions(props.extensions);
registerDefaultControls();

const data = defineModel<Record<string, unknown>>({ required: true });

const validationEnabled = computed(() => props.validation !== false);
const validation = setupFormValidation({
  schema: toRef(props, "schema"),
  data,
  enabled: validationEnabled,
  mode: computed(() => props.validationMode),
});

const rootElement = computed(() => props.uiSchema.root);

function onSubmit() {
  if (!validationEnabled.value) {
    emit("submit", { valid: true });
    return;
  }

  validation.submitted.value = true;
  const valid = validation.validateAll();
  emit("validated", { valid });
  emit("submit", { valid });
}

defineExpose({
  validate: validation.validateAll,
  isValid: validation.isValid,
});
</script>

<template>
  <form class="jse-form" novalidate @submit.prevent="onSubmit">
    <UiElementRenderer
      v-model="data"
      :element="rootElement"
      :schema="schema.root"
      :document="schema"
      :readonly="readonly"
    />
  </form>
</template>

// jsonschema-editor-react/src/components/templates/JsonSchemaForm.tsx
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  type FormEvent,
} from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { FormDataProvider } from "../../context/FormDataContext.js";
import {
  FormValidationProvider,
  useFormValidation,
  type FormValidationMode,
} from "../../context/FormValidationContext.js";
import { JseI18nProvider, resolveJseI18nOptions } from "../../context/JseI18nContext.js";
import { RegistriesProvider } from "../../context/RegistriesContext.js";
import type { JseI18nOptions } from "../../i18n/types.js";
import { registerDefaultControls } from "../../registry/register-defaults.js";
import {
  setupJseReactExtensions,
  type JseReactExtension,
} from "../../registry/react-extension.js";
import { UiElementRenderer } from "../molecules/ui/UiFormElementResolver.js";
import "../../style.css";

registerDefaultControls();

export interface JsonSchemaFormProps {
  schema: SchemaDocument;
  uiSchema: UiSchema;
  data: Record<string, unknown>;
  onDataChange: (data: Record<string, unknown>) => void;
  readonly?: boolean;
  locale?: JseI18nOptions["locale"];
  fallbackLocale?: JseI18nOptions["fallbackLocale"];
  messages?: JseI18nOptions["messages"];
  translate?: JseI18nOptions["translate"];
  extensions?: JseReactExtension[];
  validation?: boolean;
  validationMode?: FormValidationMode;
  onSubmit?: (payload: { valid: boolean }) => void;
  onValidated?: (payload: { valid: boolean }) => void;
}

export interface JsonSchemaFormHandle {
  validate: () => boolean;
}

export const JsonSchemaForm = forwardRef<JsonSchemaFormHandle, JsonSchemaFormProps>(
  function JsonSchemaForm(props, ref) {
    setupJseReactExtensions(props.extensions);

    const i18nOptions = useMemo(
      () =>
        resolveJseI18nOptions({
          locale: props.locale,
          fallbackLocale: props.fallbackLocale,
          messages: props.messages,
          translate: props.translate,
        }),
      [props.fallbackLocale, props.locale, props.messages, props.translate],
    );

    return (
      <JseI18nProvider options={i18nOptions}>
        <RegistriesProvider>
          <FormDataProvider data={props.data} onDataChange={props.onDataChange}>
            <FormValidationProvider
              schema={props.schema}
              data={props.data}
              enabled={props.validation !== false}
              mode={props.validationMode ?? "blur"}
            >
              <JsonSchemaFormBody {...props} ref={ref} />
            </FormValidationProvider>
          </FormDataProvider>
        </RegistriesProvider>
      </JseI18nProvider>
    );
  },
);

const JsonSchemaFormBody = forwardRef<JsonSchemaFormHandle, JsonSchemaFormProps>(
  function JsonSchemaFormBody(props, ref) {
    const validation = useFormValidation();
    const rootElement = props.uiSchema.root;

    useImperativeHandle(ref, () => ({
      validate: () => validation?.validateAll() ?? true,
    }));

    const handleSubmit = useCallback(
      (event: FormEvent) => {
        event.preventDefault();
        if (props.validation === false) {
          props.onSubmit?.({ valid: true });
          return;
        }
        const valid = validation?.validateAll() ?? true;
        props.onValidated?.({ valid });
        props.onSubmit?.({ valid });
      },
      [props, validation],
    );

    return (
      <form className="jse-form" noValidate onSubmit={handleSubmit}>
        <UiElementRenderer
          element={rootElement}
          schema={props.schema.root}
          document={props.schema}
          data={props.data}
          onDataChange={props.onDataChange}
          readonly={props.readonly}
        />
      </form>
    );
  },
);
