// jsonschema-editor-vue/src/components/templates/JsonSchemaFormEditor.vue
<script setup lang="ts">
import { toRef } from "vue";
import { registerDefaultControls } from "../../registry/register-defaults.js";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import type { JseI18nOptions, JseLocale } from "../../i18n/types";
import JseButton from "../atoms/JseButton.vue";
import JseTabs from "../atoms/JseTabs.vue";
import JseTextarea from "../atoms/JseTextarea.vue";
import SchemaStructureEditor from "../organisms/SchemaStructureEditor.vue";
import UiStructureEditor from "../organisms/UiStructureEditor.vue";
import {
  resolveJseI18nOptions,
  setupJseI18n,
  useJseI18n,
} from "../../composables/useJseI18n";
import { useSchemaFormEditorState } from "../../composables/useSchemaFormEditorState";
import { setupJseVueExtensions, type JseVueExtension } from "../../registry/vue-extension";

const props = withDefaults(
  defineProps<{
    schema: SchemaDocument;
    uiSchema: UiSchema;
    locale?: JseLocale;
    fallbackLocale?: JseLocale;
    messages?: JseI18nOptions["messages"];
    translate?: JseI18nOptions["translate"];
    /** Opt-in locales for editing UI label translations in the attributes panel. */
    labelLocales?: JseLocale[];
    extensions?: JseVueExtension[];
    /** When true, schema and UI schema stay visible but are not editable. */
    readonly?: boolean;
  }>(),
  { readonly: false },
);

const emit = defineEmits<{
  "update:schema": [schema: SchemaDocument];
  "update:uiSchema": [uiSchema: UiSchema];
  "update:messages": [messages: NonNullable<JseI18nOptions["messages"]>];
}>();

setupJseI18n(() => resolveJseI18nOptions(props));
setupJseVueExtensions(props.extensions);
registerDefaultControls();
const { t } = useJseI18n();

const {
  editorTab,
  editorTabs,
  selectedSchemaPath,
  selectedUiPath,
  uiManualEdit,
  showAdvancedJson,
  documentRef,
  uiRoot,
  updateDocument,
  updateUiRoot,
  regenerateUiFromSchema,
  schemaJson,
  uiSchemaJson,
} = useSchemaFormEditorState(toRef(props, "schema"), toRef(props, "uiSchema"), emit, {
  readonly: toRef(props, "readonly"),
});
</script>

<template>
  <div class="jse-editor">
    <section class="jse-editor__panel jse-editor__panel--main">
      <JseTabs v-model="editorTab" panel-id-prefix="jse-editor" :tabs="editorTabs" />

      <div
        v-show="editorTab === 'schema'"
        id="jse-editor-schema"
        class="jse-editor__tab-panel"
        role="tabpanel"
        aria-labelledby="jse-editor-tab-schema"
      >
        <SchemaStructureEditor
          :document="documentRef"
          :selected-path="selectedSchemaPath"
          @update:document="updateDocument"
          @update:selected-path="selectedSchemaPath = $event"
        />
      </div>

      <div
        v-show="editorTab === 'ui'"
        id="jse-editor-ui"
        class="jse-editor__tab-panel"
        role="tabpanel"
        aria-labelledby="jse-editor-tab-ui"
      >
        <div v-if="uiManualEdit && !readonly" class="jse-editor__banner">
          {{ t("editor.banner.manualUi") }}
          <JseButton type="button" @click="regenerateUiFromSchema">
            {{ t("editor.banner.regenerate") }}
          </JseButton>
        </div>
        <UiStructureEditor
          :root="uiRoot"
          :selected-path="selectedUiPath"
          :document="documentRef"
          :label-locales="labelLocales"
          :messages="messages"
          @update:root="updateUiRoot"
          @update:selected-path="selectedUiPath = $event"
          @update:messages="emit('update:messages', $event)"
        />
      </div>

      <details class="jse-editor__advanced" :open="showAdvancedJson">
        <summary @click.prevent="showAdvancedJson = !showAdvancedJson">
          {{ t("editor.advanced.summary") }}
        </summary>
        <label v-show="editorTab === 'schema'" class="jse-editor__json">
          {{ t("editor.advanced.schemaJson") }}
          <JseTextarea v-model="schemaJson" :rows="8" :disabled="readonly" />
        </label>
        <label v-show="editorTab === 'ui'" class="jse-editor__json">
          {{ t("editor.advanced.uiJson") }}
          <JseTextarea v-model="uiSchemaJson" :rows="8" :disabled="readonly" />
        </label>
      </details>
    </section>
  </div>
</template>

// jsonschema-editor-react/src/components/templates/JsonSchemaFormEditor.tsx
import { useMemo } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { JseButton } from "../atoms/JseButton.js";
import { JseTabs } from "../atoms/JseTabs.js";
import { JseTextarea } from "../atoms/JseTextarea.js";
import { SchemaStructureEditor } from "../organisms/SchemaStructureEditor.js";
import { UiStructureEditor } from "../organisms/UiStructureEditor.js";
import { EditorContextProvider } from "../../context/EditorContext.js";
import { JseI18nProvider, resolveJseI18nOptions } from "../../context/JseI18nContext.js";
import { RegistriesProvider } from "../../context/RegistriesContext.js";
import type { JseI18nOptions, JseLocale } from "../../i18n/types.js";
import { registerDefaultControls } from "../../registry/register-defaults.js";
import {
  setupJseReactExtensions,
  type JseReactExtension,
} from "../../registry/react-extension.js";
import { useSchemaFormEditorState } from "../../hooks/useSchemaFormEditorState.js";
import { useJseI18n } from "../../context/JseI18nContext.js";

registerDefaultControls();

export interface JsonSchemaFormEditorProps {
  schema: SchemaDocument;
  uiSchema: UiSchema;
  onSchemaChange: (schema: SchemaDocument) => void;
  onUiSchemaChange: (uiSchema: UiSchema) => void;
  locale?: JseI18nOptions["locale"];
  fallbackLocale?: JseI18nOptions["fallbackLocale"];
  messages?: JseI18nOptions["messages"];
  translate?: JseI18nOptions["translate"];
  /** Opt-in locales for editing UI label translations in the attributes panel. */
  labelLocales?: readonly JseLocale[];
  onMessagesChange?: (messages: NonNullable<JseI18nOptions["messages"]>) => void;
  extensions?: JseReactExtension[];
  /** When true, schema and UI schema stay visible but are not editable. */
  readonly?: boolean;
}

function JsonSchemaFormEditorBody({
  schema,
  uiSchema,
  onSchemaChange,
  onUiSchemaChange,
  labelLocales,
  messages,
  onMessagesChange,
  readonly = false,
}: Pick<
  JsonSchemaFormEditorProps,
  | "schema"
  | "uiSchema"
  | "onSchemaChange"
  | "onUiSchemaChange"
  | "labelLocales"
  | "messages"
  | "onMessagesChange"
  | "readonly"
>) {
  const { t } = useJseI18n();

  const {
    editorTab,
    setEditorTab,
    editorTabs,
    selectedSchemaPath,
    setSelectedSchemaPath,
    selectedUiPath,
    setSelectedUiPath,
    uiManualEdit,
    showAdvancedJson,
    setShowAdvancedJson,
    documentRef,
    uiRoot,
    updateDocument,
    updateUiRoot,
    regenerateUiFromSchema,
    schemaJson,
    setSchemaJson,
    uiSchemaJson,
    setUiSchemaJson,
    editorContext,
  } = useSchemaFormEditorState(
    schema,
    uiSchema,
    {
      onSchemaChange,
      onUiSchemaChange,
    },
    { readonly },
  );

  return (
    <EditorContextProvider value={editorContext}>
      <div className="jse-editor">
        <section className="jse-editor__panel jse-editor__panel--main">
          <JseTabs
            modelValue={editorTab}
            onModelValueChange={(id) => setEditorTab(id as "schema" | "ui")}
            panelIdPrefix="jse-editor"
            tabs={editorTabs}
          />

          {editorTab === "schema" ? (
            <div
              id="jse-editor-schema"
              className="jse-editor__tab-panel"
              role="tabpanel"
              aria-labelledby="jse-editor-tab-schema"
            >
              <SchemaStructureEditor
                document={documentRef}
                selectedPath={selectedSchemaPath}
                onDocumentChange={updateDocument}
                onSelectedPathChange={setSelectedSchemaPath}
              />
            </div>
          ) : null}

          {editorTab === "ui" ? (
            <div
              id="jse-editor-ui"
              className="jse-editor__tab-panel"
              role="tabpanel"
              aria-labelledby="jse-editor-tab-ui"
            >
              {uiManualEdit && !readonly ? (
                <div className="jse-editor__banner">
                  {t("editor.banner.manualUi")}
                  <JseButton type="button" onClick={regenerateUiFromSchema}>
                    {t("editor.banner.regenerate")}
                  </JseButton>
                </div>
              ) : null}
              <UiStructureEditor
                root={uiRoot}
                selectedPath={selectedUiPath}
                document={documentRef}
                onRootChange={updateUiRoot}
                onSelectedPathChange={setSelectedUiPath}
                labelLocales={labelLocales}
                messages={messages}
                onMessagesChange={onMessagesChange}
              />
            </div>
          ) : null}

          <details className="jse-editor__advanced" open={showAdvancedJson}>
            <summary
              onClick={(event) => {
                event.preventDefault();
                setShowAdvancedJson((value) => !value);
              }}
            >
              {t("editor.advanced.summary")}
            </summary>
            {editorTab === "schema" ? (
              <label className="jse-editor__json">
                {t("editor.advanced.schemaJson")}
                <JseTextarea
                  modelValue={schemaJson}
                  rows={8}
                  disabled={readonly}
                  onModelValueChange={setSchemaJson}
                />
              </label>
            ) : null}
            {editorTab === "ui" ? (
              <label className="jse-editor__json">
                {t("editor.advanced.uiJson")}
                <JseTextarea
                  modelValue={uiSchemaJson}
                  rows={8}
                  disabled={readonly}
                  onModelValueChange={setUiSchemaJson}
                />
              </label>
            ) : null}
          </details>
        </section>
      </div>
    </EditorContextProvider>
  );
}

export function JsonSchemaFormEditor(props: JsonSchemaFormEditorProps) {
  setupJseReactExtensions(props.extensions);

  const i18nOptions = useMemo(
    () =>
      resolveJseI18nOptions({
        locale: props.locale,
        fallbackLocale: props.fallbackLocale,
        messages: props.messages,
        translate: props.translate,
      }),
    [props.fallbackLocale, props.locale, props.messages, props.translate],
  );

  return (
    <JseI18nProvider options={i18nOptions}>
      <RegistriesProvider>
        <JsonSchemaFormEditorBody
          schema={props.schema}
          uiSchema={props.uiSchema}
          onSchemaChange={props.onSchemaChange}
          onUiSchemaChange={props.onUiSchemaChange}
          labelLocales={props.labelLocales}
          messages={props.messages}
          onMessagesChange={props.onMessagesChange}
          readonly={props.readonly}
        />
      </RegistriesProvider>
    </JseI18nProvider>
  );
}
