// jsonschema-editor-react/src/components/molecules/tree/SchemaDefsTreeNode.tsx
import { useMemo } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import { DEFS_SEGMENT, listDocumentChildren } from "../../../utils/schema-document.js";
import { schemaPathKey, type SchemaPath } from "../../../utils/schema-editor.js";
import { JseTreeToggle } from "../../atoms/JseTreeToggle.js";
import { JseTreeNodeActions } from "../JseTreeNodeActions.js";
import { useEditorContext } from "../../../context/EditorContext.js";
import { useJseI18n } from "../../../context/JseI18nContext.js";
import { SchemaTreeNode } from "./SchemaTreeNode.js";

export interface SchemaDefsTreeNodeProps {
  document: SchemaDocument;
  selectedPath: SchemaPath;
  expandedKeys: ReadonlySet<string>;
  onSelect: (path: SchemaPath) => void;
  onToggle: (path: SchemaPath) => void;
  onAdd: (path: SchemaPath, event: React.MouseEvent) => void;
  onEdit: (path: SchemaPath, event: React.MouseEvent) => void;
  onDelete: (path: SchemaPath) => void;
}

export function SchemaDefsTreeNode({
  document,
  selectedPath,
  expandedKeys,
  onSelect,
  onToggle,
  onAdd,
  onEdit,
  onDelete,
}: SchemaDefsTreeNodeProps) {
  const { t } = useJseI18n();
  const { readonly } = useEditorContext();
  const defsPath = useMemo(() => [DEFS_SEGMENT] as SchemaPath, []);
  const defsChildren = useMemo(
    () => listDocumentChildren(document, defsPath),
    [document, defsPath],
  );
  const defsExpanded = expandedKeys.has(DEFS_SEGMENT);
  const defsSelected = schemaPathKey(selectedPath) === DEFS_SEGMENT;

  return (
    <div className="jse-tree-node">
      <div
        className={[
          "jse-tree-node__row",
          defsSelected ? "jse-tree-node__row--selected" : "",
        ]
          .filter(Boolean)
          .join(" ")}
        style={{ paddingLeft: "4px" }}
        onClick={() => onSelect(defsPath)}
      >
        <JseTreeToggle hasChildren expanded={defsExpanded} onToggle={() => onToggle(defsPath)} />
        <span className="jse-tree-node__kind">$defs</span>
        <span className="jse-tree-node__label">{t("schemaStructure.defs.label")}</span>
        <JseTreeNodeActions
          showAdd={!readonly}
          showEdit={false}
          showDelete={false}
          addLabel={t("schemaStructure.defs.addDefinition")}
          onAdd={(event) => onAdd(defsPath, event)}
        />
      </div>

      {defsExpanded ? (
        <div className="jse-tree-node__children">
          {defsChildren.map((defPath) => (
            <SchemaTreeNode
              key={schemaPathKey(defPath)}
              document={document}
              path={defPath}
              selectedPath={selectedPath}
              expandedKeys={expandedKeys}
              depth={1}
              onSelect={onSelect}
              onToggle={onToggle}
              onAdd={onAdd}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </div>
      ) : null}
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/tree/SchemaDefsTreeNode.vue
<script setup lang="ts">
import { computed } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import { DEFS_SEGMENT, listDocumentChildren } from "../../../utils/schema-document";
import { schemaPathKey, type SchemaPath } from "../../../utils/schema-editor";
import { useEditorContext } from "../../../composables/useEditorContext";
import JseTreeToggle from "../../atoms/JseTreeToggle.vue";
import JseTreeNodeActions from "../JseTreeNodeActions.vue";
import { useJseI18n } from "../../../composables/useJseI18n";
import SchemaTreeNode from "./SchemaTreeNode.vue";

const props = defineProps<{
  document: SchemaDocument;
  selectedPath: SchemaPath;
  expandedKeys: ReadonlySet<string>;
}>();

const emit = defineEmits<{
  select: [path: SchemaPath];
  toggle: [path: SchemaPath];
  add: [path: SchemaPath, event: MouseEvent];
  edit: [path: SchemaPath, event: MouseEvent];
  delete: [path: SchemaPath];
}>();

const { t } = useJseI18n();
const { readonly } = useEditorContext();

const defsPath = [DEFS_SEGMENT] as SchemaPath;
const defsChildren = computed(() => listDocumentChildren(props.document, defsPath));
const defsExpanded = computed(() => props.expandedKeys.has(DEFS_SEGMENT));
const defsSelected = computed(() => schemaPathKey(props.selectedPath) === DEFS_SEGMENT);
</script>

<template>
  <div class="jse-tree-node">
    <div
      class="jse-tree-node__row"
      :class="{ 'jse-tree-node__row--selected': defsSelected }"
      style="padding-left: 4px"
      @click="emit('select', defsPath)"
    >
      <JseTreeToggle
        :has-children="true"
        :expanded="defsExpanded"
        @toggle="emit('toggle', defsPath)"
      />
      <span class="jse-tree-node__kind">$defs</span>
      <span class="jse-tree-node__label">{{ t("schemaStructure.defs.label") }}</span>
      <JseTreeNodeActions
        :show-add="!readonly"
        :show-edit="false"
        :show-delete="false"
        :add-label="t('schemaStructure.defs.addDefinition')"
        @add="emit('add', defsPath, $event)"
      />
    </div>

    <div v-if="defsExpanded" class="jse-tree-node__children">
      <SchemaTreeNode
        v-for="defPath in defsChildren"
        :key="schemaPathKey(defPath)"
        :document="document"
        :path="defPath"
        :selected-path="selectedPath"
        :expanded-keys="expandedKeys"
        :depth="1"
        @select="emit('select', $event)"
        @toggle="emit('toggle', $event)"
        @add="(path, event) => emit('add', path, event)"
        @edit="(path, event) => emit('edit', path, event)"
        @delete="emit('delete', $event)"
      />
    </div>
  </div>
</template>
