// jsonschema-editor-vue/src/components/molecules/tree/UiTreeNode.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { Control } from "@jsonschema-editor/ui-schema";
import {
  controlAllowsDetail,
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  listUiChildren,
  uiPathKey,
  type UiPath,
} from "../../../utils/ui-editor";
import { canAcceptUiChildren, canDeleteUiElement } from "../../../utils/ui-tree-actions";
import { useTreeNodeActionLabels } from "../../../composables/useTreeNodeActionLabels";
import { useJseI18n } from "../../../composables/useJseI18n";
import JseTreeToggle from "../../atoms/JseTreeToggle.vue";
import JseTreeNodeActions from "../JseTreeNodeActions.vue";

defineOptions({ name: "UiTreeNode" });

const props = defineProps<{
  root: UiElement;
  path: UiPath;
  selectedPath: UiPath;
  expandedKeys: ReadonlySet<string>;
  depth?: number;
  dragSourcePath: UiPath | null;
  document?: SchemaDocument | null;
}>();

const emit = defineEmits<{
  select: [path: UiPath];
  toggle: [path: UiPath];
  add: [path: UiPath, event: MouseEvent];
  edit: [path: UiPath, event: MouseEvent];
  delete: [path: UiPath];
  dragStart: [path: UiPath];
  drop: [targetPath: UiPath, sourcePath: UiPath];
}>();

const { t } = useJseI18n();
const element = computed(() => getUiElementAt(props.root, props.path));
const children = computed(() => listUiChildren(element.value, props.path));
const label = computed(() => getUiElementLabel(element.value));
const pathKey = computed(() => uiPathKey(props.path));
const isSelected = computed(() => uiPathKey(props.selectedPath) === pathKey.value);
const isExpanded = computed(
  () => props.path.length === 0 || props.expandedKeys.has(pathKey.value),
);
const isLayout = computed(() => isLayoutElement(element.value));
const hasDetail = computed(() => controlAllowsDetail(element.value, props.document));
const hasChildren = computed(() => children.value.length > 0);
const isContainer = computed(() => isLayout.value || hasDetail.value);
const isDragOver = ref(false);
const showAdd = computed(() => canAcceptUiChildren(element.value, props.document));
const showDelete = computed(() => canDeleteUiElement(props.path));
const { addLabel, editLabel, deleteLabel } = useTreeNodeActionLabels(label, "ui");

function onDragStart(event: DragEvent) {
  emit("dragStart", props.path);
  event.dataTransfer?.setData("text/plain", pathKey.value);
  event.dataTransfer!.effectAllowed = "move";
}

function onDragOver(event: DragEvent) {
  if (!isContainer.value || !props.dragSourcePath) return;
  event.preventDefault();
  isDragOver.value = true;
}

function onDragLeave() {
  isDragOver.value = false;
}

function onDrop(event: DragEvent) {
  event.preventDefault();
  isDragOver.value = false;
  if (!props.dragSourcePath) return;
  const targetPath =
    hasDetail.value && !isLayout.value ? ([...props.path, "detail"] as UiPath) : props.path;
  emit("drop", targetPath, props.dragSourcePath);
}
</script>

<template>
  <div class="jse-tree-node">
    <div
      class="jse-tree-node__row"
      :class="{
        'jse-tree-node__row--selected': isSelected,
        'jse-tree-node__row--drag-over': isDragOver,
      }"
      :style="{ paddingLeft: `${((depth ?? 0) * 16) + 4}px` }"
      draggable="true"
      @click="emit('select', path)"
      @dragstart="onDragStart"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
    >
      <JseTreeToggle
        :has-children="isContainer && hasChildren"
        :expanded="isExpanded"
        @toggle="emit('toggle', path)"
      />

      <span class="jse-tree-node__kind">{{ element.elementKind }}</span>
      <span class="jse-tree-node__label">{{ label }}</span>
      <span v-if="element instanceof Control" class="jse-tree-node__meta">{{ element.scope }}</span>
      <span v-if="hasDetail && !isLayout" class="jse-tree-node__meta">{{ t("layout.detailHint") }}</span>

      <JseTreeNodeActions
        :show-add="showAdd"
        :show-edit="true"
        :show-delete="showDelete"
        :add-label="addLabel"
        :edit-label="editLabel"
        :delete-label="deleteLabel"
        @add="emit('add', path, $event)"
        @edit="emit('edit', path, $event)"
        @delete="emit('delete', path)"
      />
    </div>

    <div v-if="isExpanded && hasChildren" class="jse-tree-node__children">
      <UiTreeNode
        v-for="childPath in children"
        :key="uiPathKey(childPath)"
        :root="root"
        :path="childPath"
        :selected-path="selectedPath"
        :expanded-keys="expandedKeys"
        :drag-source-path="dragSourcePath"
        :document="document"
        :depth="(depth ?? 0) + 1"
        @select="emit('select', $event)"
        @toggle="emit('toggle', $event)"
        @add="(childPath, event) => emit('add', childPath, event)"
        @edit="(childPath, event) => emit('edit', childPath, event)"
        @delete="emit('delete', $event)"
        @drag-start="emit('dragStart', $event)"
        @drop="(target, source) => emit('drop', target, source)"
      />
    </div>
  </div>
</template>

// jsonschema-editor-react/src/components/molecules/tree/UiTreeNode.tsx
import { useMemo, useState } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { Control } from "@jsonschema-editor/ui-schema";
import {
  controlAllowsDetail,
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  listUiChildren,
  uiPathKey,
  type UiPath,
} from "../../../utils/ui-editor.js";
import { canAcceptUiChildren, canDeleteUiElement } from "../../../utils/ui-tree-actions.js";
import { useJseI18n } from "../../../context/JseI18nContext.js";
import { useTreeNodeActionLabels } from "../../../hooks/useTreeNodeActionLabels.js";
import { JseTreeToggle } from "../../atoms/JseTreeToggle.js";
import { JseTreeNodeActions } from "../JseTreeNodeActions.js";

export interface UiTreeNodeProps {
  root: UiElement;
  path: UiPath;
  selectedPath: UiPath;
  expandedKeys: ReadonlySet<string>;
  depth?: number;
  dragSourcePath: UiPath | null;
  document?: SchemaDocument | null;
  onSelect: (path: UiPath) => void;
  onToggle: (path: UiPath) => void;
  onAdd: (path: UiPath, event: React.MouseEvent) => void;
  onEdit: (path: UiPath, event: React.MouseEvent) => void;
  onDelete: (path: UiPath) => void;
  onDragStart: (path: UiPath) => void;
  onDrop: (targetPath: UiPath, sourcePath: UiPath) => void;
}

export function UiTreeNode({
  root,
  path,
  selectedPath,
  expandedKeys,
  depth = 0,
  dragSourcePath,
  document,
  onSelect,
  onToggle,
  onAdd,
  onEdit,
  onDelete,
  onDragStart,
  onDrop,
}: UiTreeNodeProps) {
  const [isDragOver, setIsDragOver] = useState(false);
  const { t } = useJseI18n();

  const element = getUiElementAt(root, path);
  const children = useMemo(() => listUiChildren(element, path), [element, path]);
  const label = getUiElementLabel(element);
  const pathKey = uiPathKey(path);
  const isSelected = uiPathKey(selectedPath) === pathKey;
  const isExpanded = path.length === 0 || expandedKeys.has(pathKey);
  const isLayout = isLayoutElement(element);
  const hasDetail = controlAllowsDetail(element, document);
  const isContainer = isLayout || hasDetail;
  const showAdd = canAcceptUiChildren(element, document);
  const showDelete = canDeleteUiElement(path);
  const { addLabel, editLabel, deleteLabel } = useTreeNodeActionLabels(label, "ui");

  function handleDragStart(event: React.DragEvent) {
    onDragStart(path);
    event.dataTransfer?.setData("text/plain", pathKey);
    if (event.dataTransfer) event.dataTransfer.effectAllowed = "move";
  }

  function handleDragOver(event: React.DragEvent) {
    if (!isContainer || !dragSourcePath) return;
    event.preventDefault();
    setIsDragOver(true);
  }

  function handleDrop(event: React.DragEvent) {
    event.preventDefault();
    setIsDragOver(false);
    if (!dragSourcePath) return;
    const targetPath =
      hasDetail && !isLayout ? ([...path, "detail"] as UiPath) : path;
    onDrop(targetPath, dragSourcePath);
  }

  return (
    <div className="jse-tree-node">
      <div
        className={[
          "jse-tree-node__row",
          isSelected ? "jse-tree-node__row--selected" : "",
          isDragOver ? "jse-tree-node__row--drag-over" : "",
        ]
          .filter(Boolean)
          .join(" ")}
        style={{ paddingLeft: `${depth * 16 + 4}px` }}
        draggable
        onClick={() => onSelect(path)}
        onDragStart={handleDragStart}
        onDragOver={handleDragOver}
        onDragLeave={() => setIsDragOver(false)}
        onDrop={handleDrop}
      >
        <JseTreeToggle
          hasChildren={isContainer && children.length > 0}
          expanded={isExpanded}
          onToggle={() => onToggle(path)}
        />
        <span className="jse-tree-node__kind">{element.elementKind}</span>
        <span className="jse-tree-node__label">{label}</span>
        {element instanceof Control ? (
          <span className="jse-tree-node__meta">{element.scope}</span>
        ) : null}
        {hasDetail && !isLayout ? (
          <span className="jse-tree-node__meta">{t("layout.detailHint")}</span>
        ) : null}
        <JseTreeNodeActions
          showAdd={showAdd}
          showEdit
          showDelete={showDelete}
          addLabel={addLabel}
          editLabel={editLabel}
          deleteLabel={deleteLabel}
          onAdd={(event) => onAdd(path, event)}
          onEdit={(event) => onEdit(path, event)}
          onDelete={() => onDelete(path)}
        />
      </div>

      {isExpanded && children.length > 0 ? (
        <div className="jse-tree-node__children">
          {children.map((childPath) => (
            <UiTreeNode
              key={uiPathKey(childPath)}
              root={root}
              path={childPath}
              selectedPath={selectedPath}
              expandedKeys={expandedKeys}
              dragSourcePath={dragSourcePath}
              document={document}
              depth={depth + 1}
              onSelect={onSelect}
              onToggle={onToggle}
              onAdd={onAdd}
              onEdit={onEdit}
              onDelete={onDelete}
              onDragStart={onDragStart}
              onDrop={onDrop}
            />
          ))}
        </div>
      ) : null}
    </div>
  );
}
