// jsonschema-editor-examples/src/site/components/atoms/StackSwitch.vue
<script setup lang="ts">
import type { AppStack } from "../../../app-routing";

defineProps<{
  /** Accessible name for the stack switcher nav. */
  switchAriaLabel: string;
  ownedStack: AppStack;
  vueHref: string;
  reactHref: string;
}>();

const emit = defineEmits<{
  select: [stack: AppStack];
}>();
</script>

<template>
  <nav class="app__stack-switch" :aria-label="switchAriaLabel">
    <a
      :href="vueHref"
      class="app__stack-switch-link"
      :class="{ 'app__stack-switch-link--active': ownedStack === 'vue' }"
      :aria-current="ownedStack === 'vue' ? 'page' : undefined"
      @click="
        (event) => {
          if (ownedStack === 'vue') event.preventDefault();
          else emit('select', 'vue');
        }
      "
    >
      Vue
    </a>
    <a
      :href="reactHref"
      class="app__stack-switch-link"
      :class="{ 'app__stack-switch-link--active': ownedStack === 'react' }"
      :aria-current="ownedStack === 'react' ? 'page' : undefined"
      @click="
        (event) => {
          if (ownedStack === 'react') event.preventDefault();
          else emit('select', 'react');
        }
      "
    >
      React
    </a>
  </nav>
</template>

// jsonschema-editor-examples-react/src/site/components/atoms/StackSwitch.tsx
import type { AppStack } from "../../../app-routing.js";

interface StackSwitchProps {
  ariaLabel: string;
  ownedStack: AppStack;
  vueHref: string;
  reactHref: string;
  onSelect: (stack: AppStack) => void;
}

export function StackSwitch({
  ariaLabel,
  ownedStack,
  vueHref,
  reactHref,
  onSelect,
}: StackSwitchProps) {
  return (
    <nav className="app__stack-switch" aria-label={ariaLabel}>
      <a
        href={vueHref}
        className={`app__stack-switch-link${ownedStack === "vue" ? " app__stack-switch-link--active" : ""}`}
        aria-current={ownedStack === "vue" ? "page" : undefined}
        onClick={(event) => {
          if (ownedStack === "vue") {
            event.preventDefault();
            return;
          }
          onSelect("vue");
        }}
      >
        Vue
      </a>
      <a
        href={reactHref}
        className={`app__stack-switch-link${ownedStack === "react" ? " app__stack-switch-link--active" : ""}`}
        aria-current={ownedStack === "react" ? "page" : undefined}
        onClick={(event) => {
          if (ownedStack === "react") {
            event.preventDefault();
            return;
          }
          onSelect("react");
        }}
      >
        React
      </a>
    </nav>
  );
}
