// jsonschema-editor-react/src/components/molecules/ui/GroupUiElement.tsx
import type { Group, UiElement } from "@jsonschema-editor/ui-schema";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";
import { UiFormElementResolver } from "./UiFormElementResolver.js";

export interface GroupUiElementProps extends UiElementRendererProps {
  element: Group;
}

export function GroupUiElement({
  element,
  schema,
  document,
  data,
  onDataChange,
  readonly,
}: GroupUiElementProps) {
  return (
    <fieldset className="jse-group">
      {element.label ? <legend>{element.label}</legend> : null}
      {element.elements.map((child: UiElement, index: number) => (
        <UiFormElementResolver
          key={index}
          element={child}
          schema={schema}
          document={document}
          data={data}
          onDataChange={onDataChange}
          readonly={readonly}
        />
      ))}
    </fieldset>
  );
}

// jsonschema-editor-vue/src/components/molecules/ui/GroupUiElement.vue
<script setup lang="ts">
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import type { Group } from "@jsonschema-editor/ui-schema";
import UiFormElementResolver from "./UiFormElementResolver.vue";

defineProps<{
  element: Group;
  schema: SchemaNode;
  document?: SchemaDocument;
  readonly?: boolean;
}>();

const data = defineModel<Record<string, unknown>>({ required: true });
</script>

<template>
  <fieldset class="jse-group">
    <legend v-if="element.label">{{ element.label }}</legend>
    <UiFormElementResolver
      v-for="(child, index) in element.elements"
      :key="index"
      v-model="data"
      :element="child"
      :schema="schema"
      :document="document"
      :readonly="readonly"
    />
  </fieldset>
</template>
