// jsonschema-editor-react/src/components/molecules/ui/LabelUiElement.tsx
import type { Label } from "@jsonschema-editor/ui-schema";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";

export interface LabelUiElementProps extends UiElementRendererProps {
  element: Label;
}

export function LabelUiElement({ element }: LabelUiElementProps) {
  return <p className="jse-label">{element.text}</p>;
}

// jsonschema-editor-vue/src/components/molecules/ui/LabelUiElement.vue
<script setup lang="ts">
import type { SchemaNode } from "@jsonschema-editor/json-schema";
import type { Label } from "@jsonschema-editor/ui-schema";

defineProps<{
  element: Label;
  schema: SchemaNode;
  readonly?: boolean;
}>();

defineModel<Record<string, unknown>>({ required: true });
</script>

<template>
  <p class="jse-label">{{ element.text }}</p>
</template>
