// jsonschema-editor-react/src/components/molecules/ui/LayoutUiElement.tsx
import type { HorizontalLayout, VerticalLayout, UiElement } from "@jsonschema-editor/ui-schema";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";
import { UiFormElementResolver } from "./UiFormElementResolver.js";

export interface LayoutUiElementProps extends UiElementRendererProps {
  element: VerticalLayout | HorizontalLayout;
}

export function LayoutUiElement({
  element,
  schema,
  document,
  data,
  onDataChange,
  readonly,
}: LayoutUiElementProps) {
  return (
    <div
      className={
        element.elementKind === "HorizontalLayout"
          ? "jse-layout jse-layout--horizontal"
          : "jse-layout"
      }
    >
      {element.elements.map((child: UiElement, index: number) => (
        <UiFormElementResolver
          key={index}
          element={child}
          schema={schema}
          document={document}
          data={data}
          onDataChange={onDataChange}
          readonly={readonly}
        />
      ))}
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/ui/LayoutUiElement.vue
<script setup lang="ts">
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import type { HorizontalLayout, VerticalLayout } from "@jsonschema-editor/ui-schema";
import UiFormElementResolver from "./UiFormElementResolver.vue";

defineProps<{
  element: VerticalLayout | HorizontalLayout;
  schema: SchemaNode;
  document?: SchemaDocument;
  readonly?: boolean;
}>();

const data = defineModel<Record<string, unknown>>({ required: true });
</script>

<template>
  <div
    :class="
      element.elementKind === 'HorizontalLayout'
        ? 'jse-layout jse-layout--horizontal'
        : 'jse-layout'
    "
  >
    <UiFormElementResolver
      v-for="(child, index) in element.elements"
      :key="index"
      v-model="data"
      :element="child"
      :schema="schema"
      :document="document"
      :readonly="readonly"
    />
  </div>
</template>
