// jsonschema-editor-react/src/components/molecules/ui/StepperUiElement.tsx
import { useMemo, useState } from "react";
import {
  resolveStepIndicatorLabel,
  resolveUiI18nString,
  type Step,
  type Stepper,
  type UiElement,
} from "@jsonschema-editor/ui-schema";
import { JseButton } from "../../atoms/JseButton.js";
import { useJseI18n } from "../../../context/JseI18nContext.js";
import { useStepperStepsDisplayMode } from "../../../hooks/useStepperStepsDisplayMode.js";
import { buildUiElementKey } from "../../../utils/ui-element-key.js";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";
import { UiFormElementResolver } from "./UiFormElementResolver.js";

export interface StepperUiElementProps extends UiElementRendererProps {
  element: Stepper;
}

export function StepperUiElement({
  element,
  schema,
  document,
  data,
  onDataChange,
  readonly,
  scopePrefix,
}: StepperUiElementProps) {
  const { t, te } = useJseI18n();
  const [activeStep, setActiveStep] = useState(0);

  const steps = useMemo(
    () => element.elements.filter((child): child is Step => child.elementKind === "Step"),
    [element.elements],
  );

  const activeStepElement = steps[activeStep] ?? steps[0];
  const isFirst = activeStep <= 0;
  const isLast = activeStep >= steps.length - 1;

  function stepLabel(step: Step, index: number): string {
    return (
      resolveUiI18nString(
        { i18n: step.i18n, defaultMessage: step.label, suffix: "label" },
        (key) => (te(key) ? t(key) : undefined),
      ) ?? t("stepper.step", { index: index + 1 })
    );
  }

  const { containerRef, displayMode } = useStepperStepsDisplayMode(steps.length, activeStep);

  function stepIndicatorLabel(step: Step, index: number): string | undefined {
    const fullLabel = stepLabel(step, index);
    return resolveStepIndicatorLabel(displayMode, fullLabel, index === activeStep);
  }

  function scrollActiveStepIntoView() {
    requestAnimationFrame(() => {
      containerRef.current
        ?.querySelector<HTMLElement>(".jse-stepper__step-indicator--active")
        ?.scrollIntoView({ block: "nearest", inline: "nearest" });
    });
  }

  function goToStep(index: number) {
    if (index < 0 || index >= steps.length) return;
    setActiveStep(index);
    scrollActiveStepIntoView();
  }

  return (
    <div className="jse-stepper">
      <ol
        ref={containerRef}
        className={`jse-stepper__steps jse-stepper__steps--${displayMode}`}
        role="list"
      >
        {steps.map((step, index) => {
          const fullLabel = stepLabel(step, index);
          const indicatorLabel = stepIndicatorLabel(step, index);

          return (
            <li
              key={index}
              className={[
                "jse-stepper__step-indicator",
                index === activeStep ? "jse-stepper__step-indicator--active" : "",
                index < activeStep ? "jse-stepper__step-indicator--done" : "",
              ]
                .filter(Boolean)
                .join(" ")}
            >
              <button
                type="button"
                className="jse-stepper__step-button"
                aria-current={index === activeStep ? "step" : undefined}
                aria-label={`${index + 1}. ${fullLabel}`}
                title={fullLabel}
                onClick={() => goToStep(index)}
              >
                <span className="jse-stepper__step-number">{index + 1}</span>
                {indicatorLabel ? (
                  <span className="jse-stepper__step-label">{indicatorLabel}</span>
                ) : null}
              </button>
            </li>
          );
        })}
      </ol>

      {activeStepElement ? (
        <div className="jse-stepper__panel">
          {activeStepElement.elements.map((child: UiElement, index: number) => (
            <UiFormElementResolver
              key={buildUiElementKey(`step-${activeStep}`, child, index)}
              element={child}
              schema={schema}
              document={document}
              data={data}
              onDataChange={onDataChange}
              readonly={readonly}
              scopePrefix={scopePrefix}
            />
          ))}
        </div>
      ) : null}

      {steps.length > 1 ? (
        <div className="jse-stepper__nav">
          <JseButton type="button" disabled={isFirst || readonly} onClick={() => goToStep(activeStep - 1)}>
            {t("stepper.back")}
          </JseButton>
          <JseButton type="button" disabled={isLast || readonly} onClick={() => goToStep(activeStep + 1)}>
            {t("stepper.next")}
          </JseButton>
        </div>
      ) : null}
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/ui/StepperUiElement.vue
<script setup lang="ts">
import { computed, nextTick, ref } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import {
  resolveStepIndicatorLabel,
  resolveUiI18nString,
  type Step,
  type Stepper,
} from "@jsonschema-editor/ui-schema";
import JseButton from "../../atoms/JseButton.vue";
import { useJseI18n } from "../../../composables/useJseI18n";
import { useStepperStepsDisplayMode } from "../../../composables/useStepperStepsDisplayMode";
import { buildUiElementKey } from "../../../utils/ui-element-key";
import UiFormElementResolver from "./UiFormElementResolver.vue";

const props = defineProps<{
  element: Stepper;
  schema: SchemaNode;
  document?: SchemaDocument;
  readonly?: boolean;
  scopePrefix?: string;
}>();

const data = defineModel<Record<string, unknown>>({ required: true });

const { t, te } = useJseI18n();

function stepLabel(step: Step, index: number): string {
  return (
    resolveUiI18nString(
      { i18n: step.i18n, defaultMessage: step.label, suffix: "label" },
      (key) => (te(key) ? t(key) : undefined),
    ) ?? t("stepper.step", { index: index + 1 })
  );
}
const activeStep = ref(0);

const steps = computed(() =>
  props.element.elements.filter((child): child is Step => child.elementKind === "Step"),
);

const stepsRef = ref<HTMLOListElement | null>(null);
const layoutWatchSource = computed(() => [steps.value.length, activeStep.value] as const);
const { displayMode } = useStepperStepsDisplayMode(stepsRef, layoutWatchSource);

function stepIndicatorLabel(step: Step, index: number): string | undefined {
  const fullLabel = stepLabel(step, index);
  return resolveStepIndicatorLabel(displayMode.value, fullLabel, index === activeStep.value);
}

const activeStepElement = computed(
  () => steps.value[activeStep.value] ?? steps.value[0],
);

const isFirst = computed(() => activeStep.value <= 0);
const isLast = computed(() => activeStep.value >= steps.value.length - 1);

function scrollActiveStepIntoView() {
  void nextTick(() => {
    stepsRef.value
      ?.querySelector<HTMLElement>(".jse-stepper__step-indicator--active")
      ?.scrollIntoView({ block: "nearest", inline: "nearest" });
  });
}

function goToStep(index: number) {
  if (index < 0 || index >= steps.value.length) return;
  activeStep.value = index;
  scrollActiveStepIntoView();
}

function previousStep() {
  goToStep(activeStep.value - 1);
}

function nextStep() {
  goToStep(activeStep.value + 1);
}
</script>

<template>
  <div class="jse-stepper">
    <ol
      ref="stepsRef"
      class="jse-stepper__steps"
      :class="`jse-stepper__steps--${displayMode}`"
      role="list"
    >
      <li
        v-for="(step, index) in steps"
        :key="index"
        class="jse-stepper__step-indicator"
        :class="{
          'jse-stepper__step-indicator--active': index === activeStep,
          'jse-stepper__step-indicator--done': index < activeStep,
        }"
      >
        <button
          type="button"
          class="jse-stepper__step-button"
          :aria-current="index === activeStep ? 'step' : undefined"
          :aria-label="`${index + 1}. ${stepLabel(step, index)}`"
          :title="stepLabel(step, index)"
          @click="goToStep(index)"
        >
          <span class="jse-stepper__step-number">{{ index + 1 }}</span>
          <span v-if="stepIndicatorLabel(step, index)" class="jse-stepper__step-label">
            {{ stepIndicatorLabel(step, index) }}
          </span>
        </button>
      </li>
    </ol>

    <div v-if="activeStepElement" class="jse-stepper__panel">
      <UiFormElementResolver
        v-for="(child, index) in activeStepElement.elements"
        :key="buildUiElementKey(`step-${activeStep}`, child, index)"
        v-model="data"
        :element="child"
        :schema="schema"
        :document="document"
        :readonly="readonly"
        :scope-prefix="scopePrefix"
      />
    </div>

    <div v-if="steps.length > 1" class="jse-stepper__nav">
      <JseButton type="button" :disabled="isFirst || readonly" @click="previousStep">
        {{ t("stepper.back") }}
      </JseButton>
      <JseButton type="button" :disabled="isLast || readonly" @click="nextStep">
        {{ t("stepper.next") }}
      </JseButton>
    </div>
  </div>
</template>
