// jsonschema-editor-react/src/components/molecules/ui/StepUiElement.tsx
import type { Step, UiElement } from "@jsonschema-editor/ui-schema";
import type { UiElementRendererProps } from "../../../types/form-field-props.js";
import { UiFormElementResolver } from "./UiFormElementResolver.js";

export interface StepUiElementProps extends UiElementRendererProps {
  element: Step;
}

export function StepUiElement({
  element,
  schema,
  document,
  data,
  onDataChange,
  readonly,
}: StepUiElementProps) {
  return (
    <section className="jse-step">
      {element.label ? <h3 className="jse-step__title">{element.label}</h3> : null}
      {element.elements.map((child: UiElement, index: number) => (
        <UiFormElementResolver
          key={index}
          element={child}
          schema={schema}
          document={document}
          data={data}
          onDataChange={onDataChange}
          readonly={readonly}
        />
      ))}
    </section>
  );
}

// jsonschema-editor-vue/src/components/molecules/ui/StepUiElement.vue
<script setup lang="ts">
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import type { Step } from "@jsonschema-editor/ui-schema";
import UiFormElementResolver from "./UiFormElementResolver.vue";

defineProps<{
  element: Step;
  schema: SchemaNode;
  document?: SchemaDocument;
  readonly?: boolean;
}>();

const data = defineModel<Record<string, unknown>>({ required: true });
</script>

<template>
  <section class="jse-step">
    <h3 v-if="element.label" class="jse-step__title">{{ element.label }}</h3>
    <UiFormElementResolver
      v-for="(child, index) in element.elements"
      :key="index"
      v-model="data"
      :element="child"
      :schema="schema"
      :document="document"
      :readonly="readonly"
    />
  </section>
</template>
