// jsonschema-editor-react/src/components/molecules/JseFormField.tsx
import type { ReactNode } from "react";
import { JseLabel } from "../atoms/JseLabel.js";

export interface JseFormFieldProps {
  label?: string;
  boolean?: boolean;
  children: ReactNode;
}

export function JseFormField({ label, boolean, children }: JseFormFieldProps) {
  return (
    <div
      className={[
        "jse-attribute-control",
        boolean ? "jse-attribute-control--boolean" : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      {boolean ? (
        <>
          {children}
          {label ? <JseLabel>{label}</JseLabel> : null}
        </>
      ) : (
        <>
          {label ? <JseLabel>{label}</JseLabel> : null}
          {children}
        </>
      )}
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/JseFormField.vue
<script setup lang="ts">
import JseLabel from "../atoms/JseLabel.vue";

defineProps<{
  label?: string;
  boolean?: boolean;
}>();
</script>

<template>
  <div
    class="jse-attribute-control"
    :class="{ 'jse-attribute-control--boolean': boolean }"
  >
    <template v-if="boolean">
      <slot />
      <slot name="label">
        <JseLabel v-if="label">{{ label }}</JseLabel>
      </slot>
    </template>
    <template v-else>
      <slot name="label">
        <JseLabel v-if="label">{{ label }}</JseLabel>
      </slot>
      <slot />
    </template>
  </div>
</template>
