// jsonschema-editor-react/src/components/molecules/UiAddToolbar.tsx
import { useMemo } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { VerticalLayout } from "@jsonschema-editor/ui-schema";
import {
  canAcceptUiChild,
  controlPathOfDetail,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  getUiInsertParentPath,
  type UiPath,
} from "../../utils/ui-editor.js";
import {
  encodePaletteDragData,
  setActivePaletteKind,
} from "../../utils/ui-layout-drag.js";
import { UI_PALETTE_KINDS, type UiPaletteKind } from "../../utils/ui-palette.js";
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface UiAddToolbarProps {
  root: UiElement;
  selectedPath: UiPath;
  document?: SchemaDocument | null;
  onPaletteDrag: (kind: string | null) => void;
}

export function UiAddToolbar({ root, selectedPath, document, onPaletteDrag }: UiAddToolbarProps) {
  const { t } = useJseI18n();

  const insertParentPath = useMemo(
    () => getUiInsertParentPath(root, selectedPath, document),
    [root, selectedPath, document],
  );

  const insertParent = useMemo((): UiElement => {
    const path = insertParentPath;
    if (path[path.length - 1] === "detail") {
      try {
        return getUiElementAt(root, path);
      } catch {
        return new VerticalLayout();
      }
    }
    return getUiElementAt(root, path);
  }, [root, insertParentPath]);

  const targetLabel = useMemo(() => {
    const path = insertParentPath;
    if (path[path.length - 1] === "detail") {
      try {
        const control = getUiElementAt(root, controlPathOfDetail(path));
        return t("layout.detailTarget", { label: getUiElementLabel(control) });
      } catch {
        return t("layout.detailHint");
      }
    }
    return getUiElementLabel(insertParent);
  }, [insertParent, insertParentPath, root, t]);

  function isKindAllowed(kind: UiPaletteKind): boolean {
    return canAcceptUiChild(insertParent, createUiElement(kind, { translate: t }));
  }

  function onDragStart(kind: UiPaletteKind, event: React.DragEvent) {
    if (!isKindAllowed(kind)) {
      event.preventDefault();
      return;
    }
    setActivePaletteKind(kind);
    onPaletteDrag(kind);
    event.dataTransfer.setData("text/plain", encodePaletteDragData(kind));
    event.dataTransfer.effectAllowed = "copy";
  }

  function onDragEnd() {
    setActivePaletteKind(null);
    onPaletteDrag(null);
  }

  return (
    <div className="jse-structure-editor__toolbar" data-testid="ui-add-toolbar">
      <p className="jse-structure-editor__hint">
        {t("uiStructure.toolbarDragHint", { label: targetLabel })}
      </p>

      <div className="jse-structure-editor__buttons jse-structure-editor__buttons--palette">
        {UI_PALETTE_KINDS.map((kind) => {
          const allowed = isKindAllowed(kind);
          return (
            <button
              key={kind}
              type="button"
              className={["jse-palette-chip", allowed ? "" : "jse-palette-chip--disabled"]
                .filter(Boolean)
                .join(" ")}
              draggable={allowed}
              disabled={!allowed}
              aria-disabled={!allowed}
              title={
                allowed
                  ? t("uiStructure.paletteDragTitle", { kind })
                  : t("uiStructure.paletteDisabledTitle", { kind, label: targetLabel })
              }
              onDragStart={(event) => onDragStart(kind, event)}
              onDragEnd={onDragEnd}
            >
              {t("elementActions.addKind", { kind })}
            </button>
          );
        })}
      </div>
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/UiAddToolbar.vue
<script setup lang="ts">
import { computed } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { VerticalLayout } from "@jsonschema-editor/ui-schema";
import {
  canAcceptUiChild,
  controlPathOfDetail,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  getUiInsertParentPath,
  type UiPath,
} from "../../utils/ui-editor";
import {
  encodePaletteDragData,
  setActivePaletteKind,
} from "../../utils/ui-layout-drag";
import { UI_PALETTE_KINDS, type UiPaletteKind } from "../../utils/ui-palette";
import { useJseI18n } from "../../composables/useJseI18n";

const props = defineProps<{
  root: UiElement;
  selectedPath: UiPath;
  document?: SchemaDocument | null;
}>();

const emit = defineEmits<{
  "palette-drag": [kind: string | null];
}>();

const { t } = useJseI18n();

const insertParentPath = computed(() =>
  getUiInsertParentPath(props.root, props.selectedPath, props.document),
);

const insertParent = computed((): UiElement => {
  const path = insertParentPath.value;
  if (path[path.length - 1] === "detail") {
    try {
      return getUiElementAt(props.root, path);
    } catch {
      return new VerticalLayout();
    }
  }
  return getUiElementAt(props.root, path);
});

const targetLabel = computed(() => {
  const path = insertParentPath.value;
  if (path[path.length - 1] === "detail") {
    try {
      const control = getUiElementAt(props.root, controlPathOfDetail(path));
      return t("layout.detailTarget", { label: getUiElementLabel(control) });
    } catch {
      return t("layout.detailHint");
    }
  }
  return getUiElementLabel(insertParent.value);
});

function isKindAllowed(kind: UiPaletteKind): boolean {
  return canAcceptUiChild(insertParent.value, createUiElement(kind, { translate: t }));
}

function onDragStart(kind: UiPaletteKind, event: DragEvent) {
  if (!isKindAllowed(kind)) {
    event.preventDefault();
    return;
  }
  setActivePaletteKind(kind);
  emit("palette-drag", kind);
  event.dataTransfer?.setData("text/plain", encodePaletteDragData(kind));
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = "copy";
  }
}

function onDragEnd() {
  setActivePaletteKind(null);
  emit("palette-drag", null);
}
</script>

<template>
  <div class="jse-structure-editor__toolbar" data-testid="ui-add-toolbar">
    <p class="jse-structure-editor__hint">
      {{ t("uiStructure.toolbarDragHint", { label: targetLabel }) }}
    </p>

    <div class="jse-structure-editor__buttons jse-structure-editor__buttons--palette">
      <button
        v-for="kind in UI_PALETTE_KINDS"
        :key="kind"
        type="button"
        class="jse-palette-chip"
        :class="{ 'jse-palette-chip--disabled': !isKindAllowed(kind) }"
        :draggable="isKindAllowed(kind)"
        :disabled="!isKindAllowed(kind)"
        :aria-disabled="!isKindAllowed(kind)"
        :title="
          isKindAllowed(kind)
            ? t('uiStructure.paletteDragTitle', { kind })
            : t('uiStructure.paletteDisabledTitle', { kind, label: targetLabel })
        "
        @dragstart="onDragStart(kind, $event)"
        @dragend="onDragEnd"
      >
        {{ t("elementActions.addKind", { kind }) }}
      </button>
    </div>
  </div>
</template>
