// jsonschema-editor-react/src/components/molecules/UiElementActions.tsx
import { useEffect, useMemo, useState } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { JseButton } from "../atoms/JseButton.js";
import { ControlScopeField } from "./ControlScopeField.js";
import {
  canAcceptUiChild,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  getUiInsertParentPath,
  insertUiElement,
  type UiPath,
} from "../../utils/ui-editor.js";
import {
  findControlScopeSuggestion,
  listControlScopeSuggestions,
  listUsedControlScopes,
} from "../../utils/control-scope-suggestions.js";
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface UiElementActionsProps {
  root: UiElement;
  targetPath: UiPath;
  document?: SchemaDocument | null;
  onRootChange: (root: UiElement) => void;
  onDone: () => void;
}

type UiLayoutElementKind =
  | "Group"
  | "VerticalLayout"
  | "HorizontalLayout"
  | "Label"
  | "Categorization"
  | "Category"
  | "Stepper"
  | "Step";

const uiLayoutElementKinds: UiLayoutElementKind[] = [
  "Group",
  "VerticalLayout",
  "HorizontalLayout",
  "Label",
  "Categorization",
  "Category",
  "Stepper",
  "Step",
];

export function UiElementActions({
  root,
  targetPath,
  document,
  onRootChange,
  onDone,
}: UiElementActionsProps) {
  const { t } = useJseI18n();
  const [controlScope, setControlScope] = useState("");

  const targetElement = useMemo(() => getUiElementAt(root, targetPath), [root, targetPath]);
  const targetLabel = getUiElementLabel(targetElement);
  const insertParentPath = useMemo(
    () => getUiInsertParentPath(root, targetPath),
    [root, targetPath],
  );
  const insertParent = useMemo(
    () => getUiElementAt(root, insertParentPath),
    [root, insertParentPath],
  );
  const usedScopes = useMemo(() => listUsedControlScopes(root), [root]);
  const availableSuggestions = useMemo(
    () => listControlScopeSuggestions(document, { excludeScopes: usedScopes }),
    [document, usedScopes],
  );
  const allSuggestions = useMemo(() => listControlScopeSuggestions(document), [document]);

  const compatibleKinds = useMemo(
    () =>
      uiLayoutElementKinds.filter((kind) =>
        canAcceptUiChild(insertParent, createUiElement(kind, { translate: t })),
      ),
    [insertParent, t],
  );

  const canAddControl = useMemo(
    () => canAcceptUiChild(insertParent, createUiElement("Control", { translate: t })),
    [insertParent, t],
  );

  useEffect(() => {
    if (!controlScope.trim()) {
      setControlScope(availableSuggestions[0]?.scope ?? "");
    }
  }, [availableSuggestions, controlScope, targetPath]);

  function addElement(kind: UiLayoutElementKind) {
    const element = createUiElement(kind, { translate: t });
    if (!canAcceptUiChild(insertParent, element)) return;
    onRootChange(insertUiElement(root, insertParentPath, element));
    onDone();
  }

  function addControl() {
    if (!canAddControl) return;
    const scope = controlScope.trim() || "#/properties/field";
    const suggestion = findControlScopeSuggestion(allSuggestions, scope);
    const element = createUiElement("Control", {
      translate: t,
      scope,
      label: suggestion?.label,
    });
    onRootChange(insertUiElement(root, insertParentPath, element));
    const next = listControlScopeSuggestions(document, {
      excludeScopes: [...usedScopes, scope],
    });
    setControlScope(next[0]?.scope ?? "");
    onDone();
  }

  return (
    <div className="jse-element-actions">
      <p className="jse-element-actions__target">
        {t("elementActions.target")} <strong>{targetLabel}</strong>
        <span className="jse-element-actions__kind">({targetElement.elementKind})</span>
      </p>

      {compatibleKinds.length > 0 ? (
        <div className="jse-element-actions__section">
          <span className="jse-structure-editor__hint">{t("elementActions.addUiElement")}</span>
          <div className="jse-structure-editor__buttons">
            {compatibleKinds.map((kind) => (
              <JseButton key={kind} type="button" onClick={() => addElement(kind)}>
                {t("elementActions.addKind", { kind })}
              </JseButton>
            ))}
          </div>
        </div>
      ) : null}

      {canAddControl ? (
        <div className="jse-element-actions__section">
          <ControlScopeField
            document={document}
            usedScopes={usedScopes}
            modelValue={controlScope}
            onModelValueChange={setControlScope}
          />
          <div className="jse-structure-editor__buttons">
            <JseButton type="button" onClick={addControl}>
              {t("elementActions.addKind", { kind: "Control" })}
            </JseButton>
          </div>
        </div>
      ) : null}

      {compatibleKinds.length === 0 && !canAddControl ? (
        <p className="jse-structure-editor__note">
          {t("uiStructure.toolbarNoCompatible", { label: targetLabel })}
        </p>
      ) : null}
    </div>
  );
}

// jsonschema-editor-vue/src/components/molecules/UiElementActions.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import JseButton from "../atoms/JseButton.vue";
import ControlScopeField from "./ControlScopeField.vue";
import {
  canAcceptUiChild,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  getUiInsertParentPath,
  insertUiElement,
  type UiPath,
} from "../../utils/ui-editor";
import {
  findControlScopeSuggestion,
  listControlScopeSuggestions,
  listUsedControlScopes,
} from "../../utils/control-scope-suggestions";
import { useJseI18n } from "../../composables/useJseI18n";

type UiLayoutElementKind =
  | "Group"
  | "VerticalLayout"
  | "HorizontalLayout"
  | "Label"
  | "Categorization"
  | "Category"
  | "Stepper"
  | "Step";

const LAYOUT_KINDS: readonly UiLayoutElementKind[] = [
  "Group",
  "VerticalLayout",
  "HorizontalLayout",
  "Label",
  "Categorization",
  "Category",
  "Stepper",
  "Step",
];

const props = defineProps<{
  root: UiElement;
  targetPath: UiPath;
  document?: SchemaDocument | null;
}>();

const emit = defineEmits<{
  "update:root": [root: UiElement];
  done: [];
}>();

const { t } = useJseI18n();
const controlScope = ref("");

const targetElement = computed(() => getUiElementAt(props.root, props.targetPath));
const targetLabel = computed(() => getUiElementLabel(targetElement.value));
const insertParentPath = computed(() => getUiInsertParentPath(props.root, props.targetPath));
const insertParent = computed(() => getUiElementAt(props.root, insertParentPath.value));
const usedScopes = computed(() => listUsedControlScopes(props.root));
const availableSuggestions = computed(() =>
  listControlScopeSuggestions(props.document, { excludeScopes: usedScopes.value }),
);
const allSuggestions = computed(() => listControlScopeSuggestions(props.document));

const compatibleKinds = computed(() =>
  LAYOUT_KINDS.filter((kind) =>
    canAcceptUiChild(insertParent.value, createUiElement(kind, { translate: t })),
  ),
);

const canAddControl = computed(() =>
  canAcceptUiChild(insertParent.value, createUiElement("Control", { translate: t })),
);

watch(
  () => [props.targetPath, availableSuggestions.value] as const,
  () => {
    if (!controlScope.value.trim()) {
      controlScope.value = availableSuggestions.value[0]?.scope ?? "";
    }
  },
  { immediate: true },
);

function addElement(kind: UiLayoutElementKind) {
  const element = createUiElement(kind, { translate: t });
  if (!canAcceptUiChild(insertParent.value, element)) return;
  emit("update:root", insertUiElement(props.root, insertParentPath.value, element));
  emit("done");
}

function addControl() {
  if (!canAddControl.value) return;
  const scope = controlScope.value.trim() || "#/properties/field";
  const suggestion = findControlScopeSuggestion(allSuggestions.value, scope);
  const element = createUiElement("Control", {
    translate: t,
    scope,
    label: suggestion?.label,
  });
  emit("update:root", insertUiElement(props.root, insertParentPath.value, element));
  const next = listControlScopeSuggestions(props.document, {
    excludeScopes: [...usedScopes.value, scope],
  });
  controlScope.value = next[0]?.scope ?? "";
  emit("done");
}
</script>

<template>
  <div class="jse-element-actions">
    <p class="jse-element-actions__target">
      {{ t("elementActions.target") }} <strong>{{ targetLabel }}</strong>
      <span class="jse-element-actions__kind">({{ targetElement.elementKind }})</span>
    </p>

    <div v-if="compatibleKinds.length > 0" class="jse-element-actions__section">
      <span class="jse-structure-editor__hint">{{ t("elementActions.addUiElement") }}</span>
      <div class="jse-structure-editor__buttons">
        <JseButton
          v-for="kind in compatibleKinds"
          :key="kind"
          type="button"
          @click="addElement(kind)"
        >
          {{ t("elementActions.addKind", { kind }) }}
        </JseButton>
      </div>
    </div>

    <div v-if="canAddControl" class="jse-element-actions__section">
      <ControlScopeField
        v-model="controlScope"
        :document="document"
        :used-scopes="usedScopes"
      />
      <div class="jse-structure-editor__buttons">
        <JseButton type="button" @click="addControl">
          {{ t("elementActions.addKind", { kind: "Control" }) }}
        </JseButton>
      </div>
    </div>

    <p
      v-if="compatibleKinds.length === 0 && !canAddControl"
      class="jse-structure-editor__note"
    >
      {{ t("uiStructure.toolbarNoCompatible", { label: targetLabel }) }}
    </p>
  </div>
</template>
