// jsonschema-editor-react/src/components/molecules/UiLayoutEditorNode.tsx
import { Fragment, useMemo, useState } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { Control, HorizontalLayout, VerticalLayout } from "@jsonschema-editor/ui-schema";
import {
  canAcceptUiChild,
  canMoveUiElementTo,
  controlAllowsDetail,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  listUiChildren,
  parseUiPathKey,
  uiPathKey,
  type UiPath,
} from "../../utils/ui-editor.js";
import { canAcceptUiChildren, canDeleteUiElement } from "../../utils/ui-tree-actions.js";
import {
  getActiveLayoutDragSourcePath,
  getActivePaletteKind,
  parsePaletteDragData,
  resolveStackInsertIndex,
  setActiveLayoutDragSourcePath,
} from "../../utils/ui-layout-drag.js";
import type { UiPaletteKind } from "../../utils/ui-palette.js";
import { useJseI18n } from "../../context/JseI18nContext.js";
import { useTreeNodeActionLabels } from "../../hooks/useTreeNodeActionLabels.js";
import { UiLayoutDropZone } from "../atoms/UiLayoutDropZone.js";
import { JseTreeNodeActions } from "./JseTreeNodeActions.js";

export interface UiLayoutEditorNodeProps {
  root: UiElement;
  path: UiPath;
  selectedPath: UiPath;
  dragSourcePath: UiPath | null;
  document?: SchemaDocument | null;
  paletteKind?: string | null;
  depth?: number;
  onSelect: (path: UiPath) => void;
  onAdd: (path: UiPath, event: React.MouseEvent) => void;
  onEdit: (path: UiPath, event: React.MouseEvent) => void;
  onDelete: (path: UiPath) => void;
  onDragStart: (path: UiPath) => void;
  onDropAt: (parentPath: UiPath, insertIndex: number, event?: React.DragEvent) => void;
}

export function UiLayoutEditorNode({
  root,
  path,
  selectedPath,
  dragSourcePath,
  document,
  paletteKind = null,
  depth = 0,
  onSelect,
  onAdd,
  onEdit,
  onDelete,
  onDragStart,
  onDropAt,
}: UiLayoutEditorNodeProps) {
  const [activeDropIndex, setActiveDropIndex] = useState<number | null>(null);
  const { t } = useJseI18n();

  const element = getUiElementAt(root, path);
  const label = getUiElementLabel(element);
  const pathKey = uiPathKey(path);
  const isSelected = uiPathKey(selectedPath) === pathKey;
  const isLayout = isLayoutElement(element);
  const showDetail = controlAllowsDetail(element, document);
  const stackParentPath: UiPath =
    showDetail && !isLayout ? [...path, "detail"] : path;
  const isHorizontal = element instanceof HorizontalLayout;
  const children = useMemo(
    () => listUiChildren(element, path),
    [element, path],
  );
  const showAdd = canAcceptUiChildren(element, document);
  const showDelete = canDeleteUiElement(path);
  const { addLabel, editLabel, deleteLabel } = useTreeNodeActionLabels(label, "ui");
  const isDragging =
    dragSourcePath !== null && uiPathKey(dragSourcePath) === pathKey;

  const scopeHint = useMemo(() => {
    if (!(element instanceof Control)) return "";
    const segments = element.scope.split("/");
    return segments[segments.length - 1] ?? element.scope;
  }, [element]);

  const blockClass = useMemo(() => {
    const kind = element.elementKind;
    if (kind === "Control") return "jse-layout-block--control";
    if (kind === "Group") return "jse-layout-block--group";
    if (kind === "Label") return "jse-layout-block--label";
    if (kind === "HorizontalLayout") return "jse-layout-block--horizontal";
    if (kind === "VerticalLayout") return "jse-layout-block--vertical";
    if (kind === "Category" || kind === "Step") return "jse-layout-block--section";
    if (kind === "Categorization" || kind === "Stepper") return "jse-layout-block--container";
    return "jse-layout-block--default";
  }, [element.elementKind]);

  function resolvePaletteKind(event?: React.DragEvent): string | null {
    if (paletteKind) return paletteKind;
    const active = getActivePaletteKind();
    if (active) return active;
    return parsePaletteDragData(event?.dataTransfer?.getData("text/plain"));
  }

  function resolveDragSourcePath(event?: React.DragEvent): UiPath | null {
    if (resolvePaletteKind(event)) return null;
    if (dragSourcePath) return dragSourcePath;
    const activePath = getActiveLayoutDragSourcePath(parseUiPathKey);
    if (activePath) return activePath;
    const key = event?.dataTransfer?.getData("text/plain");
    if (!key || parsePaletteDragData(key)) return null;
    return parseUiPathKey(key);
  }

  function dropParentForAccept(): UiElement {
    if (showDetail && !isLayout) {
      const control = element as Control;
      if (control.detail && isLayoutElement(control.detail)) return control.detail;
      return new VerticalLayout();
    }
    return element;
  }

  function canDropAt(insertIndex: number, event?: React.DragEvent): boolean {
    const kind = resolvePaletteKind(event);
    if (kind) {
      if (!isLayout && !showDetail) return false;
      return canAcceptUiChild(
        dropParentForAccept(),
        createUiElement(kind as UiPaletteKind),
      );
    }
    const sourcePath = resolveDragSourcePath(event);
    if (!sourcePath) return false;
    return canMoveUiElementTo(root, sourcePath, stackParentPath, insertIndex);
  }

  const hasActiveDrag = dragSourcePath !== null || Boolean(paletteKind);
  const showStack = isLayout || showDetail;

  function handleDragStart(event: React.DragEvent) {
    onDragStart(path);
    setActiveLayoutDragSourcePath(path, uiPathKey);
    event.dataTransfer?.setData("text/plain", pathKey);
    if (event.dataTransfer) event.dataTransfer.effectAllowed = "move";
  }

  function onLayoutDragEnter(event: React.DragEvent) {
    if (!showStack) return;
    if (!resolveDragSourcePath(event) && !resolvePaletteKind(event)) return;
    event.preventDefault();
  }

  function onLayoutDragOver(event: React.DragEvent) {
    if (!showStack) return;
    event.stopPropagation();
    const stack = (event.currentTarget as HTMLElement).querySelector(
      ":scope > .jse-layout-editor__stack",
    );
    if (!(stack instanceof HTMLElement)) return;
    const insertIndex = resolveStackInsertIndex(stack, event.clientY);
    if (!canDropAt(insertIndex, event)) return;
    event.preventDefault();
    setActiveDropIndex(insertIndex);
  }

  function onLayoutDrop(event: React.DragEvent) {
    if (!showStack) return;
    event.stopPropagation();
    const stack = (event.currentTarget as HTMLElement).querySelector(
      ":scope > .jse-layout-editor__stack",
    );
    if (!(stack instanceof HTMLElement)) return;
    event.preventDefault();
    const insertIndex = resolveStackInsertIndex(stack, event.clientY);
    setActiveDropIndex(null);
    if (!canDropAt(insertIndex, event)) return;
    onDropAt(stackParentPath, insertIndex, event);
  }

  function onStackDragOver(event: React.DragEvent) {
    if (!showStack) return;
    const stack = event.currentTarget;
    if (!(stack instanceof HTMLElement)) return;
    const insertIndex = resolveStackInsertIndex(stack, event.clientY);
    if (!canDropAt(insertIndex, event)) return;
    event.preventDefault();
    event.stopPropagation();
    setActiveDropIndex(insertIndex);
  }

  function onStackDrop(event: React.DragEvent) {
    if (!showStack) return;
    const stack = event.currentTarget;
    if (!(stack instanceof HTMLElement)) return;
    event.preventDefault();
    event.stopPropagation();
    const insertIndex = resolveStackInsertIndex(stack, event.clientY);
    setActiveDropIndex(null);
    if (!canDropAt(insertIndex, event)) return;
    onDropAt(stackParentPath, insertIndex, event);
  }

  function onDropZoneDragOver(insertIndex: number, event: React.DragEvent) {
    if (!canDropAt(insertIndex, event)) return;
    event.preventDefault();
    setActiveDropIndex(insertIndex);
  }

  function onDropZoneDrop(insertIndex: number, event: React.DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    setActiveDropIndex(null);
    if (!canDropAt(insertIndex, event)) return;
    onDropAt(stackParentPath, insertIndex, event);
  }

  return (
    <article
      className={[
        "jse-layout-block",
        blockClass,
        isSelected ? "jse-layout-block--selected" : "",
        isDragging ? "jse-layout-block--dragging" : "",
      ]
        .filter(Boolean)
        .join(" ")}
      data-ui-path={pathKey}
      onClick={(event) => {
        event.stopPropagation();
        onSelect(path);
      }}
      onDragEnter={onLayoutDragEnter}
      onDragOver={onLayoutDragOver}
      onDrop={onLayoutDrop}
    >
      <header className="jse-layout-block__header">
        {path.length > 0 ? (
          <span
            className="jse-layout-block__drag-handle"
            draggable
            role="presentation"
            aria-hidden="true"
            onDragStart={(event) => {
              event.stopPropagation();
              handleDragStart(event);
            }}
            onDragEnd={() => setActiveDropIndex(null)}
          >
            ⠿
          </span>
        ) : null}
        <span className="jse-tree-node__kind">{element.elementKind}</span>
        <span className="jse-layout-block__title">{label}</span>
        {scopeHint ? <span className="jse-tree-node__meta">{scopeHint}</span> : null}
        {showDetail && !isLayout ? (
          <span className="jse-tree-node__meta">{t("layout.detailHint")}</span>
        ) : null}
        <JseTreeNodeActions
          showAdd={showAdd}
          showEdit
          showDelete={showDelete}
          addLabel={addLabel}
          editLabel={editLabel}
          deleteLabel={deleteLabel}
          onAdd={(event) => onAdd(path, event)}
          onEdit={(event) => onEdit(path, event)}
          onDelete={() => onDelete(path)}
        />
      </header>

      {showStack ? (
        <div
          className={[
            "jse-layout-editor__stack",
            isHorizontal ? "jse-layout-editor__stack--horizontal" : "",
            showDetail && !isLayout ? "jse-layout-editor__stack--detail" : "",
          ]
            .filter(Boolean)
            .join(" ")}
          onDragOver={onStackDragOver}
          onDragLeave={() => setActiveDropIndex(null)}
          onDrop={onStackDrop}
        >
          {children.map((childPath, index) => (
            <Fragment key={uiPathKey(childPath)}>
              <UiLayoutDropZone
                active={activeDropIndex === index && hasActiveDrag}
                onDragOver={(event) => onDropZoneDragOver(index, event)}
                onDragLeave={() => setActiveDropIndex(null)}
                onDrop={(event) => onDropZoneDrop(index, event)}
              />
              <UiLayoutEditorNode
                root={root}
                path={childPath}
                selectedPath={selectedPath}
                dragSourcePath={dragSourcePath}
                document={document}
                paletteKind={paletteKind}
                depth={depth + 1}
                onSelect={onSelect}
                onAdd={onAdd}
                onEdit={onEdit}
                onDelete={onDelete}
                onDragStart={onDragStart}
                onDropAt={onDropAt}
              />
            </Fragment>
          ))}

          {children.length === 0 || hasActiveDrag ? (
            <UiLayoutDropZone
              active={activeDropIndex === children.length && hasActiveDrag}
              label={children.length === 0 ? t("layout.dropElement") : undefined}
              onDragOver={(event) => onDropZoneDragOver(children.length, event)}
              onDragLeave={() => setActiveDropIndex(null)}
              onDrop={(event) => onDropZoneDrop(children.length, event)}
            />
          ) : null}
        </div>
      ) : null}
    </article>
  );
}

// jsonschema-editor-vue/src/components/molecules/UiLayoutEditorNode.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { Control, HorizontalLayout, VerticalLayout } from "@jsonschema-editor/ui-schema";
import {
  canAcceptUiChild,
  canMoveUiElementTo,
  controlAllowsDetail,
  createUiElement,
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  listUiChildren,
  parseUiPathKey,
  uiPathKey,
  type UiPath,
} from "../../utils/ui-editor";
import { canAcceptUiChildren, canDeleteUiElement } from "../../utils/ui-tree-actions";
import {
  getActiveLayoutDragSourcePath,
  getActivePaletteKind,
  parsePaletteDragData,
  resolveStackInsertIndex,
  setActiveLayoutDragSourcePath,
} from "../../utils/ui-layout-drag";
import type { UiPaletteKind } from "../../utils/ui-palette";
import { useJseI18n } from "../../composables/useJseI18n";
import { useTreeNodeActionLabels } from "../../composables/useTreeNodeActionLabels";
import UiLayoutDropZone from "../atoms/UiLayoutDropZone.vue";
import JseTreeNodeActions from "./JseTreeNodeActions.vue";

defineOptions({ name: "UiLayoutEditorNode" });

const props = defineProps<{
  root: UiElement;
  path: UiPath;
  selectedPath: UiPath;
  dragSourcePath: UiPath | null;
  document?: SchemaDocument | null;
  paletteKind?: string | null;
  depth?: number;
}>();

const emit = defineEmits<{
  select: [path: UiPath];
  add: [path: UiPath, event: MouseEvent];
  edit: [path: UiPath, event: MouseEvent];
  delete: [path: UiPath];
  dragStart: [path: UiPath];
  dropAt: [parentPath: UiPath, insertIndex: number, event?: DragEvent];
}>();

const activeDropIndex = ref<number | null>(null);

const element = computed(() => getUiElementAt(props.root, props.path));
const label = computed(() => getUiElementLabel(element.value));
const pathKey = computed(() => uiPathKey(props.path));
const isSelected = computed(() => uiPathKey(props.selectedPath) === pathKey.value);
const isLayout = computed(() => isLayoutElement(element.value));
const showDetail = computed(() => controlAllowsDetail(element.value, props.document));
const stackParentPath = computed((): UiPath =>
  showDetail.value && !isLayout.value ? [...props.path, "detail"] : props.path,
);
const isHorizontal = computed(() => element.value instanceof HorizontalLayout);
const children = computed(() => listUiChildren(element.value, props.path));
const showAdd = computed(() => canAcceptUiChildren(element.value, props.document));
const showDelete = computed(() => canDeleteUiElement(props.path));
const { t } = useJseI18n();
const { addLabel, editLabel, deleteLabel } = useTreeNodeActionLabels(label, "ui");
const isDragging = computed(
  () => props.dragSourcePath !== null && uiPathKey(props.dragSourcePath) === pathKey.value,
);

const scopeHint = computed(() => {
  if (!(element.value instanceof Control)) return "";
  const segments = element.value.scope.split("/");
  return segments[segments.length - 1] ?? element.value.scope;
});

const blockClass = computed(() => {
  const kind = element.value.elementKind;
  if (kind === "Control") return "jse-layout-block--control";
  if (kind === "Group") return "jse-layout-block--group";
  if (kind === "Label") return "jse-layout-block--label";
  if (kind === "HorizontalLayout") return "jse-layout-block--horizontal";
  if (kind === "VerticalLayout") return "jse-layout-block--vertical";
  if (kind === "Category" || kind === "Step") return "jse-layout-block--section";
  if (kind === "Categorization" || kind === "Stepper") return "jse-layout-block--container";
  return "jse-layout-block--default";
});

function resolvePaletteKind(event?: DragEvent): string | null {
  if (props.paletteKind) return props.paletteKind;
  const active = getActivePaletteKind();
  if (active) return active;
  return parsePaletteDragData(event?.dataTransfer?.getData("text/plain"));
}

function resolveDragSourcePath(event?: DragEvent): UiPath | null {
  if (resolvePaletteKind(event)) return null;
  if (props.dragSourcePath) return props.dragSourcePath;
  const activePath = getActiveLayoutDragSourcePath(parseUiPathKey);
  if (activePath) return activePath;
  const key = event?.dataTransfer?.getData("text/plain");
  if (!key || parsePaletteDragData(key)) return null;
  return parseUiPathKey(key);
}

function dropParentForAccept(): UiElement {
  if (showDetail.value && !isLayout.value) {
    const control = element.value as Control;
    if (control.detail && isLayoutElement(control.detail)) return control.detail;
    return new VerticalLayout();
  }
  return element.value;
}

function canDropAt(insertIndex: number, event?: DragEvent): boolean {
  const paletteKind = resolvePaletteKind(event);
  if (paletteKind) {
    if (!isLayout.value && !showDetail.value) return false;
    return canAcceptUiChild(
      dropParentForAccept(),
      createUiElement(paletteKind as UiPaletteKind),
    );
  }
  const sourcePath = resolveDragSourcePath(event);
  if (!sourcePath) return false;
  return canMoveUiElementTo(props.root, sourcePath, stackParentPath.value, insertIndex);
}

const hasActiveDrag = computed(
  () => props.dragSourcePath !== null || Boolean(props.paletteKind),
);

const showStack = computed(() => isLayout.value || showDetail.value);

function onDragStart(event: DragEvent) {
  emit("dragStart", props.path);
  setActiveLayoutDragSourcePath(props.path, uiPathKey);
  event.dataTransfer?.setData("text/plain", pathKey.value);
  if (event.dataTransfer) event.dataTransfer.effectAllowed = "move";
}

function onLayoutDragEnter(event: DragEvent) {
  if (!showStack.value) return;
  if (!resolveDragSourcePath(event) && !resolvePaletteKind(event)) return;
  event.preventDefault();
}

function onLayoutDragOver(event: DragEvent) {
  if (!showStack.value) return;
  event.stopPropagation();
  const stack = (event.currentTarget as HTMLElement).querySelector(":scope > .jse-layout-editor__stack");
  if (!(stack instanceof HTMLElement)) return;
  const insertIndex = resolveStackInsertIndex(stack, event.clientY);
  if (!canDropAt(insertIndex, event)) return;
  event.preventDefault();
  activeDropIndex.value = insertIndex;
}

function onLayoutDrop(event: DragEvent) {
  if (!showStack.value) return;
  event.stopPropagation();
  const stack = (event.currentTarget as HTMLElement).querySelector(":scope > .jse-layout-editor__stack");
  if (!(stack instanceof HTMLElement)) return;
  event.preventDefault();
  const insertIndex = resolveStackInsertIndex(stack, event.clientY);
  activeDropIndex.value = null;
  if (!canDropAt(insertIndex, event)) return;
  emit("dropAt", stackParentPath.value, insertIndex, event);
}

function onStackDragOver(event: DragEvent) {
  if (!showStack.value) return;
  const stack = event.currentTarget;
  if (!(stack instanceof HTMLElement)) return;
  const insertIndex = resolveStackInsertIndex(stack, event.clientY);
  if (!canDropAt(insertIndex, event)) return;
  event.preventDefault();
  event.stopPropagation();
  activeDropIndex.value = insertIndex;
}

function onStackDrop(event: DragEvent) {
  if (!showStack.value) return;
  const stack = event.currentTarget;
  if (!(stack instanceof HTMLElement)) return;
  event.preventDefault();
  event.stopPropagation();
  const insertIndex = resolveStackInsertIndex(stack, event.clientY);
  activeDropIndex.value = null;
  if (!canDropAt(insertIndex, event)) return;
  emit("dropAt", stackParentPath.value, insertIndex, event);
}

function onDropZoneDragOver(insertIndex: number, event: DragEvent) {
  if (!canDropAt(insertIndex, event)) return;
  event.preventDefault();
  activeDropIndex.value = insertIndex;
}

function onDropZoneDragLeave() {
  activeDropIndex.value = null;
}

function onDropZoneDrop(insertIndex: number, event: DragEvent) {
  event.preventDefault();
  event.stopPropagation();
  activeDropIndex.value = null;
  if (!canDropAt(insertIndex, event)) return;
  emit("dropAt", stackParentPath.value, insertIndex, event);
}
</script>

<template>
  <article
    class="jse-layout-block"
    :class="[
      blockClass,
      {
        'jse-layout-block--selected': isSelected,
        'jse-layout-block--dragging': isDragging,
      },
    ]"
    :data-ui-path="pathKey"
    @click.stop="emit('select', path)"
    @dragenter="onLayoutDragEnter"
    @dragover="onLayoutDragOver"
    @drop="onLayoutDrop"
  >
    <header class="jse-layout-block__header">
      <span
        v-if="path.length > 0"
        class="jse-layout-block__drag-handle"
        draggable="true"
        role="presentation"
        aria-hidden="true"
        @dragstart.stop="onDragStart"
        @dragend.stop="activeDropIndex = null"
      >⠿</span>
      <span class="jse-tree-node__kind">{{ element.elementKind }}</span>
      <span class="jse-layout-block__title">{{ label }}</span>
      <span v-if="scopeHint" class="jse-tree-node__meta">{{ scopeHint }}</span>
      <span v-if="showDetail && !isLayout" class="jse-tree-node__meta">{{ t("layout.detailHint") }}</span>

      <JseTreeNodeActions
        :show-add="showAdd"
        :show-edit="true"
        :show-delete="showDelete"
        :add-label="addLabel"
        :edit-label="editLabel"
        :delete-label="deleteLabel"
        @add="emit('add', path, $event)"
        @edit="emit('edit', path, $event)"
        @delete="emit('delete', path)"
      />
    </header>

    <div
      v-if="showStack"
      class="jse-layout-editor__stack"
      :class="{
        'jse-layout-editor__stack--horizontal': isHorizontal,
        'jse-layout-editor__stack--detail': showDetail && !isLayout,
      }"
      @dragover="onStackDragOver"
      @dragleave="onDropZoneDragLeave"
      @drop="onStackDrop"
    >
      <template v-for="(childPath, index) in children" :key="uiPathKey(childPath)">
        <UiLayoutDropZone
          :active="activeDropIndex === index && hasActiveDrag"
          @dragover="onDropZoneDragOver(index, $event)"
          @dragleave="onDropZoneDragLeave"
          @drop="onDropZoneDrop(index, $event)"
        />
        <UiLayoutEditorNode
          :root="root"
          :path="childPath"
          :selected-path="selectedPath"
          :drag-source-path="dragSourcePath"
          :document="document"
          :palette-kind="paletteKind"
          :depth="(depth ?? 0) + 1"
          @select="emit('select', $event)"
          @add="(childPath, event) => emit('add', childPath, event)"
          @edit="(childPath, event) => emit('edit', childPath, event)"
          @delete="emit('delete', $event)"
          @drag-start="emit('dragStart', $event)"
          @drop-at="(parentPath, insertIndex, event) => emit('dropAt', parentPath, insertIndex, event)"
        />
      </template>

      <UiLayoutDropZone
        v-if="children.length === 0 || hasActiveDrag"
        :active="activeDropIndex === children.length && hasActiveDrag"
        :label="children.length === 0 ? t('layout.dropElement') : undefined"
        @dragover="onDropZoneDragOver(children.length, $event)"
        @dragleave="onDropZoneDragLeave"
        @drop="onDropZoneDrop(children.length, $event)"
      />
    </div>
  </article>
</template>
