// jsonschema-editor-react/src/components/molecules/attributes/BooleanAttributeControl.tsx
import { JseCheckbox } from "../../atoms/JseCheckbox.js";
import { JseFormField } from "../JseFormField.js";
import type { AttributeControlProps } from "../../../types/attribute-control-props.js";

export function BooleanAttributeControl({
  label,
  readonly,
  modelValue,
  onModelValueChange,
}: AttributeControlProps) {
  return (
    <JseFormField label={label} boolean>
      <JseCheckbox
        modelValue={modelValue === true}
        disabled={readonly}
        onModelValueChange={(value) => onModelValueChange?.(value)}
      />
    </JseFormField>
  );
}

// jsonschema-editor-vue/src/components/molecules/attributes/BooleanAttributeControl.vue
<script setup lang="ts">
import JseCheckbox from "../../atoms/JseCheckbox.vue";
import JseFormField from "../JseFormField.vue";

defineProps<{
  label: string;
  readonly?: boolean;
}>();

const modelValue = defineModel<boolean>({ default: false });
</script>

<template>
  <JseFormField :label="label" boolean>
    <JseCheckbox v-model="modelValue" :disabled="readonly" />
  </JseFormField>
</template>
