// jsonschema-editor-react/src/components/molecules/attributes/StringAttributeControl.tsx
import { JseInput } from "../../atoms/JseInput.js";
import { JseFormField } from "../JseFormField.js";
import type { AttributeControlProps } from "../../../types/attribute-control-props.js";

export function StringAttributeControl({
  label,
  readonly,
  modelValue,
  onModelValueChange,
}: AttributeControlProps) {
  return (
    <JseFormField label={label}>
      <JseInput
        modelValue={typeof modelValue === "string" ? modelValue : String(modelValue ?? "")}
        disabled={readonly}
        onModelValueChange={(value) => onModelValueChange?.(value)}
      />
    </JseFormField>
  );
}

// jsonschema-editor-vue/src/components/molecules/attributes/StringAttributeControl.vue
<script setup lang="ts">
import JseInput from "../../atoms/JseInput.vue";
import JseFormField from "../JseFormField.vue";

defineProps<{
  label: string;
  readonly?: boolean;
}>();

const modelValue = defineModel<string>({ default: "" });
</script>

<template>
  <JseFormField :label="label">
    <JseInput v-model="modelValue" :disabled="readonly" />
  </JseFormField>
</template>
