// jsonschema-editor-react/src/components/atoms/JseTreeToggle.tsx
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface JseTreeToggleProps {
  expanded?: boolean;
  hasChildren?: boolean;
  onToggle?: () => void;
}

export function JseTreeToggle({ expanded, hasChildren, onToggle }: JseTreeToggleProps) {
  const { t } = useJseI18n();

  if (!hasChildren) {
    return <span className="jse-tree-node__spacer" aria-hidden="true" />;
  }

  return (
    <button
      type="button"
      className="jse-tree-node__toggle"
      aria-label={expanded ? t("tree.toggle.collapse") : t("tree.toggle.expand")}
      aria-expanded={hasChildren ? expanded : undefined}
      onClick={(event) => {
        event.stopPropagation();
        onToggle?.();
      }}
    >
      {expanded ? "▼" : "▶"}
    </button>
  );
}

// jsonschema-editor-vue/src/components/atoms/JseTreeToggle.vue
<script setup lang="ts">
import { useJseI18n } from "../../composables/useJseI18n";

defineProps<{
  expanded?: boolean;
  hasChildren?: boolean;
}>();

defineEmits<{ toggle: [] }>();

const { t } = useJseI18n();
</script>

<template>
  <button
    v-if="hasChildren"
    type="button"
    class="jse-tree-node__toggle"
    :aria-label="expanded ? t('tree.toggle.collapse') : t('tree.toggle.expand')"
    :aria-expanded="hasChildren ? expanded : undefined"
    @click.stop="$emit('toggle')"
  >
    {{ expanded ? "▼" : "▶" }}
  </button>
  <span v-else class="jse-tree-node__spacer" :aria-hidden="true" />
</template>
