// jsonschema-editor-react/src/components/atoms/UiLayoutDropZone.tsx
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface UiLayoutDropZoneProps {
  active?: boolean;
  label?: string;
  onDragOver?: (event: React.DragEvent) => void;
  onDragLeave?: () => void;
  onDrop?: (event: React.DragEvent) => void;
}

export function UiLayoutDropZone({
  active,
  label,
  onDragOver,
  onDragLeave,
  onDrop,
}: UiLayoutDropZoneProps) {
  const { t } = useJseI18n();

  return (
    <div
      className={["jse-layout-dropzone", active ? "jse-layout-dropzone--active" : ""]
        .filter(Boolean)
        .join(" ")}
      role="presentation"
      onDragOver={(event) => {
        event.preventDefault();
        onDragOver?.(event);
      }}
      onDragLeave={() => onDragLeave?.()}
      onDrop={(event) => {
        event.preventDefault();
        onDrop?.(event);
      }}
    >
      {active ? (
        <span className="jse-layout-dropzone__label">{label ?? t("layout.dropHere")}</span>
      ) : null}
    </div>
  );
}

// jsonschema-editor-vue/src/components/atoms/UiLayoutDropZone.vue
<script setup lang="ts">
import { useJseI18n } from "../../composables/useJseI18n";

defineProps<{
  active?: boolean;
  label?: string;
}>();

defineEmits<{
  dragover: [event: DragEvent];
  dragleave: [];
  drop: [event: DragEvent];
}>();

const { t } = useJseI18n();
</script>

<template>
  <div
    class="jse-layout-dropzone"
    :class="{ 'jse-layout-dropzone--active': active }"
    role="presentation"
    @dragover.prevent="$emit('dragover', $event)"
    @dragleave="$emit('dragleave')"
    @drop.prevent="$emit('drop', $event)"
  >
    <span v-if="active" class="jse-layout-dropzone__label">{{ label ?? t("layout.dropHere") }}</span>
  </div>
</template>
