// jsonschema-editor-vue/src/components/molecules/form/DefaultFormField.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import { useFormFieldLabel } from "../../../composables/useFormFieldLabel";
import { useScopedField } from "../../../composables/useScopedField";
import JseCheckbox from "../../atoms/JseCheckbox.vue";
import JseInput from "../../atoms/JseInput.vue";
import JseSelect from "../../atoms/JseSelect.vue";
import JseSchemaFormField from "./JseSchemaFormField.vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope, documentRef);
const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);

const inputType = computed(() => {
  switch (resolvedSchema.value?.kind) {
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "checkbox";
    default:
      return "text";
  }
});

const enumValues = computed(() => resolvedSchema.value?.enumValues ?? []);
const isCheckbox = computed(() => inputType.value === "checkbox");
</script>

<template>
  <JseSchemaFormField
    :boolean="isCheckbox"
    :label="displayLabel"
    :description="description"
    :scope="scope"
  >
    <JseSelect
      v-if="enumValues.length"
      :model-value="value as string | number"
      class="jse-field__input"
      :disabled="readonly"
      @update:model-value="value = $event"
    >
      <option v-for="option in enumValues" :key="String(option)" :value="option as string | number">
        {{ option }}
      </option>
    </JseSelect>

    <JseCheckbox
      v-else-if="isCheckbox"
      :model-value="value as boolean"
      class="jse-field__checkbox"
      :disabled="readonly"
      @update:model-value="value = $event"
    />

    <JseInput
      v-else
      :model-value="value as string | number"
      class="jse-field__input"
      :type="inputType"
      :disabled="readonly"
      @update:model-value="value = $event"
    />
  </JseSchemaFormField>
</template>

// jsonschema-editor-react/src/components/molecules/form/DefaultFormField.tsx
import { JseInput } from "../../atoms/JseInput.js";
import { JseCheckbox } from "../../atoms/JseCheckbox.js";
import { useFormFieldLabel } from "../../../hooks/useFormFieldLabel.js";
import { useScopedField } from "../../../hooks/useScopedField.js";
import type { FormFieldProps } from "../../../types/form-field-props.js";
import { JseSchemaFormField } from "./JseSchemaFormField.js";

export function DefaultFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  const inputType =
    resolvedSchema?.kind === "integer" || resolvedSchema?.kind === "number"
      ? "number"
      : resolvedSchema?.kind === "boolean"
        ? "checkbox"
        : "text";

  if (inputType === "checkbox") {
    return (
      <JseSchemaFormField
        label={displayLabel}
        description={description}
        scope={scope}
        boolean
      >
        <JseCheckbox
          modelValue={value === true}
          disabled={readonly}
          onModelValueChange={setValue}
        />
      </JseSchemaFormField>
    );
  }

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      <JseInput
        className="jse-field__input"
        type={inputType}
        modelValue={
          typeof value === "string" || typeof value === "number"
            ? value
            : String(value ?? "")
        }
        disabled={readonly}
        onModelValueChange={(next) =>
          setValue(inputType === "number" ? (next === "" ? undefined : Number(next)) : next)
        }
      />
    </JseSchemaFormField>
  );
}
