// jsonschema-editor-vue/src/components/molecules/form/JseSchemaFormField.vue
<script setup lang="ts">
import { useFieldValidation } from "../../../composables/useFormValidation";

const props = defineProps<{
  label: string;
  description?: string;
  boolean?: boolean;
  scope?: string;
}>();

const { error, onBlur } = useFieldValidation(() => props.scope ?? "");

function onFieldFocusOut(event: FocusEvent) {
  if (!props.scope) return;
  const current = event.currentTarget as HTMLElement;
  const next = event.relatedTarget as Node | null;
  if (!next || !current.contains(next)) {
    onBlur();
  }
}
</script>

<template>
  <div
    class="jse-field"
    :class="{ 'jse-field--invalid': !!error }"
    @focusout="onFieldFocusOut"
  >
    <label class="jse-field__label">
      <template v-if="boolean">
        <slot />
        {{ label }}
      </template>
      <template v-else>
        {{ label }}
      </template>
      <span v-if="description" class="jse-field__hint">{{ description }}</span>
    </label>
    <slot v-if="!boolean" />
    <p v-if="error" class="jse-field__error" role="alert">{{ error }}</p>
  </div>
</template>

// jsonschema-editor-react/src/components/molecules/form/JseSchemaFormField.tsx
import type { ReactNode, FocusEvent } from "react";
import { useFieldValidation } from "../../../context/FormValidationContext.js";

export interface JseSchemaFormFieldProps {
  label: string;
  description?: string;
  scope?: string;
  boolean?: boolean;
  children?: ReactNode;
}

export function JseSchemaFormField({
  label,
  description,
  scope,
  boolean: isBoolean,
  children,
}: JseSchemaFormFieldProps) {
  const { error, onBlur } = useFieldValidation(scope ?? "");

  function onFieldBlur(event: FocusEvent<HTMLDivElement>) {
    if (!scope) return;
    const current = event.currentTarget;
    const next = event.relatedTarget as Node | null;
    if (!next || !current.contains(next)) {
      onBlur();
    }
  }

  return (
    <div
      className={`jse-field${error ? " jse-field--invalid" : ""}`}
      onBlur={onFieldBlur}
    >
      <label className="jse-field__label">
        {isBoolean ? (
          <>
            {children}
            {label}
          </>
        ) : (
          label
        )}
        {description ? <span className="jse-field__hint">{description}</span> : null}
      </label>
      {!isBoolean ? children : null}
      {error ? (
        <p className="jse-field__error" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
