// jsonschema-editor-vue/src/components/molecules/form/NumberFormField.vue
<script setup lang="ts">
import { toRef } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import { useFormFieldLabel } from "../../../composables/useFormFieldLabel";
import { useScopedField } from "../../../composables/useScopedField";
import JseInput from "../../atoms/JseInput.vue";
import JseSchemaFormField from "./JseSchemaFormField.vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope, documentRef);
const { displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);

function onInput(raw: string | number): void {
  value.value = raw === "" ? undefined : Number(raw);
}
</script>

<template>
  <JseSchemaFormField :label="displayLabel" :description="description" :scope="scope">
    <JseInput
      :model-value="value as number"
      class="jse-field__input"
      type="number"
      :disabled="readonly"
      @update:model-value="onInput"
    />
  </JseSchemaFormField>
</template>

// jsonschema-editor-react/src/components/molecules/form/NumberFormField.tsx
import { JseInput } from "../../atoms/JseInput.js";
import { useFormFieldLabel } from "../../../hooks/useFormFieldLabel.js";
import { useScopedField } from "../../../hooks/useScopedField.js";
import type { FormFieldProps } from "../../../types/form-field-props.js";
import { JseSchemaFormField } from "./JseSchemaFormField.js";

export function NumberFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      <JseInput
        className="jse-field__input"
        type="number"
        modelValue={typeof value === "number" ? value : String(value ?? "")}
        disabled={readonly}
        onModelValueChange={(next) => setValue(next === "" ? undefined : Number(next))}
      />
    </JseSchemaFormField>
  );
}
