// jsonschema-editor-vue/src/components/atoms/JseCheckbox.vue
<script setup lang="ts">
defineProps<{
  modelValue?: boolean;
  disabled?: boolean;
  id?: string;
}>();

defineEmits<{ "update:modelValue": [value: boolean] }>();
</script>

<template>
  <input
    :id="id"
    class="jse-checkbox"
    type="checkbox"
    :checked="modelValue"
    :disabled="disabled"
    @change="$emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
  />
</template>

// jsonschema-editor-react/src/components/atoms/JseCheckbox.tsx
import type { InputHTMLAttributes } from "react";

export interface JseCheckboxProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  "type" | "checked" | "onChange"
> {
  modelValue?: boolean;
  onModelValueChange?: (value: boolean) => void;
}

export function JseCheckbox({
  modelValue,
  onModelValueChange,
  className,
  ...rest
}: JseCheckboxProps) {
  return (
    <input
      {...rest}
      className={["jse-checkbox", className ?? ""].filter(Boolean).join(" ")}
      type="checkbox"
      checked={modelValue ?? false}
      onChange={(event) => onModelValueChange?.(event.target.checked)}
    />
  );
}
