// jsonschema-editor-vue/src/components/atoms/JseInput.vue
<script setup lang="ts">
defineProps<{
  modelValue?: string | number;
  type?: string;
  disabled?: boolean;
  placeholder?: string;
}>();

defineEmits<{ "update:modelValue": [value: string | number] }>();
</script>

<template>
  <input
    class="jse-input"
    :value="modelValue"
    :type="type ?? 'text'"
    :disabled="disabled"
    :placeholder="placeholder"
    @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  />
</template>

// jsonschema-editor-react/src/components/atoms/JseInput.tsx
import type { InputHTMLAttributes } from "react";

export interface JseInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "value" | "onChange"> {
  modelValue?: string | number;
  onModelValueChange?: (value: string) => void;
}

export function JseInput({
  modelValue,
  onModelValueChange,
  className,
  ...rest
}: JseInputProps) {
  return (
    <input
      {...rest}
      className={className}
      value={modelValue ?? ""}
      onChange={(event) => onModelValueChange?.(event.target.value)}
    />
  );
}
