// jsonschema-editor-vue/src/components/atoms/JseSelect.vue
<script setup lang="ts">
defineProps<{
  modelValue?: string | number;
  disabled?: boolean;
}>();

const emit = defineEmits<{ "update:modelValue": [value: string | number] }>();

function parseSelectValue(raw: string): string | number {
  if (raw !== "" && !Number.isNaN(Number(raw)) && /^\d+$/.test(raw)) {
    return Number(raw);
  }
  return raw;
}

function emitValue(event: Event) {
  const target = event.target as HTMLSelectElement;
  emit("update:modelValue", parseSelectValue(target.value));
}
</script>

<template>
  <select
    class="jse-select"
    :value="modelValue"
    :disabled="disabled"
        @change="emitValue($event)"
  >
    <slot />
  </select>
</template>

// jsonschema-editor-react/src/components/atoms/JseSelect.tsx
import type { ReactNode, SelectHTMLAttributes } from "react";

export interface JseSelectProps extends Omit<
  SelectHTMLAttributes<HTMLSelectElement>,
  "value" | "onChange"
> {
  modelValue?: string | number;
  onModelValueChange?: (value: string | number) => void;
  children: ReactNode;
}

function parseSelectValue(raw: string): string | number {
  if (raw !== "" && !Number.isNaN(Number(raw)) && /^\d+$/.test(raw)) {
    return Number(raw);
  }
  return raw;
}

export function JseSelect({
  modelValue,
  onModelValueChange,
  className,
  children,
  ...rest
}: JseSelectProps) {
  return (
    <select
      {...rest}
      className={["jse-select", className ?? ""].filter(Boolean).join(" ")}
      value={modelValue}
      onChange={(event) => onModelValueChange?.(parseSelectValue(event.target.value))}
    >
      {children}
    </select>
  );
}
