// jsonschema-editor-vue/src/components/atoms/JseSwitch.vue
<script setup lang="ts">
const props = defineProps<{
  modelValue?: boolean;
  disabled?: boolean;
  id?: string;
  /** Accessible name when not wrapped by a visible label. */
  ariaLabel?: string;
}>();

const emit = defineEmits<{ "update:modelValue": [value: boolean] }>();

function toggle() {
  if (props.disabled) return;
  emit("update:modelValue", !props.modelValue);
}
</script>

<template>
  <button
    :id="id"
    type="button"
    class="jse-switch"
    role="switch"
    :aria-checked="modelValue ? 'true' : 'false'"
    :aria-label="ariaLabel"
    :disabled="disabled"
    @click="toggle"
  >
    <span class="jse-switch__track" aria-hidden="true">
      <span class="jse-switch__thumb" />
    </span>
  </button>
</template>

// jsonschema-editor-react/src/components/atoms/JseSwitch.tsx
import type { ButtonHTMLAttributes } from "react";

export interface JseSwitchProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  "type" | "role" | "aria-checked" | "onClick" | "children"
> {
  modelValue?: boolean;
  onModelValueChange?: (value: boolean) => void;
  /** Accessible name when not wrapped by a visible label. */
  ariaLabel?: string;
}

export function JseSwitch({
  modelValue = false,
  onModelValueChange,
  disabled,
  className,
  ariaLabel,
  id,
  ...rest
}: JseSwitchProps) {
  return (
    <button
      {...rest}
      id={id}
      type="button"
      className={["jse-switch", className ?? ""].filter(Boolean).join(" ")}
      role="switch"
      aria-checked={modelValue}
      aria-label={ariaLabel}
      disabled={disabled}
      onClick={() => {
        if (disabled) return;
        onModelValueChange?.(!modelValue);
      }}
    >
      <span className="jse-switch__track" aria-hidden="true">
        <span className="jse-switch__thumb" />
      </span>
    </button>
  );
}
