// jsonschema-editor-vue/src/components/atoms/JseSuggestionInput.vue
<script setup lang="ts">
import { computed, useId } from "vue";

export interface JseSuggestionOption {
  value: string;
  label?: string;
}

const props = defineProps<{
  modelValue?: string;
  suggestions?: readonly JseSuggestionOption[];
  disabled?: boolean;
  placeholder?: string;
  listId?: string;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const generatedId = useId();
const datalistId = computed(() => props.listId ?? `jse-suggestions-${generatedId}`);
</script>

<template>
  <div class="jse-suggestion-input">
    <input
      class="jse-input jse-suggestion-input__field"
      type="text"
      role="combobox"
      aria-autocomplete="list"
      :aria-expanded="Boolean(suggestions?.length)"
      :list="datalistId"
      :value="modelValue ?? ''"
      :disabled="disabled"
      :placeholder="placeholder"
      autocomplete="off"
      @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
    <datalist :id="datalistId">
      <option
        v-for="option in suggestions ?? []"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label ?? option.value }}
      </option>
    </datalist>
  </div>
</template>

// jsonschema-editor-react/src/components/atoms/JseSuggestionInput.tsx
import { useId } from "react";

export interface JseSuggestionOption {
  value: string;
  label?: string;
}

export interface JseSuggestionInputProps {
  modelValue?: string;
  onModelValueChange: (value: string) => void;
  suggestions?: readonly JseSuggestionOption[];
  disabled?: boolean;
  placeholder?: string;
  listId?: string;
  className?: string;
}

export function JseSuggestionInput({
  modelValue = "",
  onModelValueChange,
  suggestions = [],
  disabled,
  placeholder,
  listId,
  className,
}: JseSuggestionInputProps) {
  const generatedId = useId();
  const datalistId = listId ?? `jse-suggestions-${generatedId}`;

  return (
    <div className={["jse-suggestion-input", className].filter(Boolean).join(" ")}>
      <input
        className="jse-input jse-suggestion-input__field"
        type="text"
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={suggestions.length > 0}
        list={datalistId}
        value={modelValue}
        disabled={disabled}
        placeholder={placeholder}
        autoComplete="off"
        onChange={(event) => onModelValueChange(event.target.value)}
      />
      <datalist id={datalistId}>
        {suggestions.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label ?? option.value}
          </option>
        ))}
      </datalist>
    </div>
  );
}
