// jsonschema-editor-vue/src/components/atoms/JseTextarea.vue
<script setup lang="ts">
defineProps<{
  modelValue?: string;
  rows?: number;
  disabled?: boolean;
  placeholder?: string;
}>();

defineEmits<{ "update:modelValue": [value: string] }>();
</script>

<template>
  <textarea
    class="jse-textarea"
    :value="modelValue"
    :rows="rows ?? 3"
    :disabled="disabled"
    :placeholder="placeholder"
    spellcheck="false"
    @input="$emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
  />
</template>

// jsonschema-editor-react/src/components/atoms/JseTextarea.tsx
import type { TextareaHTMLAttributes } from "react";

export interface JseTextareaProps extends Omit<
  TextareaHTMLAttributes<HTMLTextAreaElement>,
  "value" | "onChange"
> {
  modelValue?: string;
  onModelValueChange?: (value: string) => void;
}

export function JseTextarea({
  modelValue,
  onModelValueChange,
  className,
  rows = 3,
  ...rest
}: JseTextareaProps) {
  return (
    <textarea
      {...rest}
      className={["jse-textarea", className ?? ""].filter(Boolean).join(" ")}
      value={modelValue ?? ""}
      rows={rows}
      spellCheck={false}
      onChange={(event) => onModelValueChange?.(event.target.value)}
    />
  );
}
