// jsonschema-editor-vue-extensions/src/components/CelExpressionEditor.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import {
  createCelExpressionEditor,
  type CelExpressionEditorHandle,
} from "@jsonschema-editor/json-schema-extensions/cel-editor";

const props = defineProps<{
  modelValue: string;
  disabled?: boolean;
  placeholder?: string;
  document?: SchemaDocument;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: string];
  blur: [];
}>();

const host = ref<HTMLElement | null>(null);
let editor: CelExpressionEditorHandle | null = null;
let syncing = false;

onMounted(() => {
  if (!host.value) return;
  editor = createCelExpressionEditor(host.value, {
    value: props.modelValue,
    readOnly: props.disabled === true,
    placeholder: props.placeholder,
    schemaDocument: props.document,
    onChange: (value) => {
      if (syncing) return;
      emit("update:modelValue", value);
    },
    onBlur: () => emit("blur"),
  });
});

watch(
  () => props.modelValue,
  (value) => {
    if (!editor) return;
    syncing = true;
    editor.setValue(value);
    syncing = false;
  },
);

watch(
  () => props.disabled === true,
  (disabled) => {
    editor?.setReadOnly(disabled);
  },
);

watch(
  () => props.document,
  (document) => {
    editor?.setSchemaDocument(document);
  },
);

onBeforeUnmount(() => {
  editor?.destroy();
  editor = null;
});
</script>

<template>
  <div ref="host" class="jse-cel-expression-editor" />
</template>

<style scoped>
.jse-cel-expression-editor {
  min-height: 5.5rem;
}
</style>

// jsonschema-editor-react-extensions/src/components/CelExpressionEditor.tsx
import { useEffect, useRef } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import {
  createCelExpressionEditor,
  type CelExpressionEditorHandle,
} from "@jsonschema-editor/json-schema-extensions/cel-editor";

export interface CelExpressionEditorProps {
  value: string;
  disabled?: boolean;
  placeholder?: string;
  document?: SchemaDocument;
  onChange?: (value: string) => void;
  onBlur?: () => void;
}

export function CelExpressionEditor({
  value,
  disabled,
  placeholder,
  document,
  onChange,
  onBlur,
}: CelExpressionEditorProps) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<CelExpressionEditorHandle | null>(null);
  const onChangeRef = useRef(onChange);
  const onBlurRef = useRef(onBlur);
  onChangeRef.current = onChange;
  onBlurRef.current = onBlur;

  useEffect(() => {
    if (!hostRef.current) return;
    editorRef.current = createCelExpressionEditor(hostRef.current, {
      value,
      readOnly: disabled === true,
      placeholder,
      schemaDocument: document,
      onChange: (next) => onChangeRef.current?.(next),
      onBlur: () => onBlurRef.current?.(),
    });
    return () => {
      editorRef.current?.destroy();
      editorRef.current = null;
    };
    // Mount once; value/disabled/document synced below.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional
  }, []);

  useEffect(() => {
    editorRef.current?.setValue(value);
  }, [value]);

  useEffect(() => {
    editorRef.current?.setReadOnly(disabled === true);
  }, [disabled]);

  useEffect(() => {
    editorRef.current?.setSchemaDocument(document);
  }, [document]);

  return <div ref={hostRef} className="jse-cel-expression-editor" />;
}
