// jsonschema-editor-vue-extensions/src/components/ComputedFormField.vue
<script setup lang="ts">
import { computed, ref, toRef, watch } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import {
  BooleanSchema,
  IntegerSchema,
  NumberSchema,
} from "@jsonschema-editor/json-schema";
import {
  evaluateComputedExpression,
  readComputedConfig,
} from "@jsonschema-editor/json-schema-extensions";
import {
  useFormFieldLabel,
  useScopedField,
  JseInput,
  JseCheckbox,
  JseSchemaFormField,
} from "@jsonschema-editor/vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value, formData } = useScopedField(rootSchema, rootData, props.scope, documentRef);
const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);

const evaluationError = ref<string | null>(null);

const computedConfig = computed(() =>
  resolvedSchema.value ? readComputedConfig(resolvedSchema.value) : undefined,
);

const inputType = computed(() => {
  const node = resolvedSchema.value;
  if (node instanceof BooleanSchema) return "checkbox";
  if (node instanceof NumberSchema || node instanceof IntegerSchema) return "number";
  return "text";
});

function valuesEqual(left: unknown, right: unknown): boolean {
  return Object.is(left, right);
}

function recompute(): void {
  const config = computedConfig.value;
  if (!config) {
    evaluationError.value = null;
    return;
  }

  const result = evaluateComputedExpression(config.expression, formData.value);
  if (!result.ok) {
    evaluationError.value = result.error;
    return;
  }

  evaluationError.value = null;
  if (!valuesEqual(value.value, result.value)) {
    value.value = result.value;
  }
}

watch(formData, recompute, { deep: true, immediate: true });
watch(computedConfig, recompute, { immediate: true });

const displayValue = computed(() => {
  if (inputType.value === "checkbox") {
    return value.value === true ? "true" : value.value === false ? "false" : "";
  }
  if (value.value === null || value.value === undefined) {
    return "";
  }
  return String(value.value);
});
</script>

<template>
  <JseSchemaFormField :label="displayLabel" :description="description" :scope="scope">
    <JseInput
      v-if="inputType !== 'checkbox'"
      :model-value="displayValue"
      class="jse-field__input"
      :type="inputType"
      disabled
      readonly
    />
    <label v-else class="jse-field__checkbox">
      <JseCheckbox :model-value="value === true" disabled />
      <span>{{ displayValue === "true" ? "Ja" : "Nein" }}</span>
    </label>
    <p v-if="evaluationError" class="jse-field__hint jse-field__hint--error">
      {{ evaluationError }}
    </p>
  </JseSchemaFormField>
</template>

// jsonschema-editor-react-extensions/src/components/ComputedFormField.tsx
import { useEffect, useMemo, useState } from "react";
import {
  BooleanSchema,
  IntegerSchema,
  NumberSchema,
} from "@jsonschema-editor/json-schema";
import {
  evaluateComputedExpression,
  readComputedConfig,
} from "@jsonschema-editor/json-schema-extensions";
import {
  JseInput,
  JseCheckbox,
  JseSchemaFormField,
  useFormFieldLabel,
  useScopedField,
  type FormFieldProps,
} from "@jsonschema-editor/react";

export function ComputedFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly: _readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue, formData } = useScopedField(schema, scope, document);
  const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  const [evaluationError, setEvaluationError] = useState<string | null>(null);

  const computedConfig = useMemo(
    () => (resolvedSchema ? readComputedConfig(resolvedSchema) : undefined),
    [resolvedSchema],
  );

  const inputType = useMemo(() => {
    const node = resolvedSchema;
    if (node instanceof BooleanSchema) return "checkbox";
    if (node instanceof NumberSchema || node instanceof IntegerSchema) return "number";
    return "text";
  }, [resolvedSchema]);

  useEffect(() => {
    if (!computedConfig) {
      setEvaluationError(null);
      return;
    }

    const result = evaluateComputedExpression(computedConfig.expression, formData);
    if (!result.ok) {
      setEvaluationError(result.error);
      return;
    }

    setEvaluationError(null);
    if (!Object.is(value, result.value)) {
      setValue(result.value);
    }
  }, [computedConfig, formData, setValue, value]);

  const displayValue = useMemo(() => {
    if (inputType === "checkbox") {
      return value === true ? "true" : value === false ? "false" : "";
    }
    if (value === null || value === undefined) {
      return "";
    }
    return String(value);
  }, [inputType, value]);

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      {inputType !== "checkbox" ? (
        <JseInput
          className="jse-field__input"
          type={inputType}
          modelValue={displayValue}
          disabled
          readOnly
        />
      ) : (
        <label className="jse-field__checkbox">
          <JseCheckbox modelValue={value === true} disabled />
          <span>{displayValue === "true" ? "Ja" : "Nein"}</span>
        </label>
      )}
      {evaluationError ? (
        <p className="jse-field__hint jse-field__hint--error">{evaluationError}</p>
      ) : null}
    </JseSchemaFormField>
  );
}
