// jsonschema-editor-vue-extensions/src/components/ValuesSourceFormField.vue
<script setup lang="ts">

import { computed, ref, toRef, watch } from "vue";

import type { SchemaNode } from "@jsonschema-editor/json-schema";

import {

  isFetchValuesSource,

  isStaticValuesSource,

  readValuesSourceConfig,

  type FetchValuesSource,

} from "@jsonschema-editor/json-schema-extensions";

import {

  JseSchemaFormField,

  JseSelect,

  useFormFieldLabel,

  useScopedField,

} from "@jsonschema-editor/vue";



const props = defineProps<{

  schema: SchemaNode;

  scope: string;

  label?: string;

  i18nKey?: string;

  readonly?: boolean;

}>();



const rootSchema = toRef(props, "schema");

const labelRef = toRef(props, "label");

const i18nKeyRef = toRef(props, "i18nKey");

const rootData = defineModel<Record<string, unknown>>({ required: true });



const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope);

const { resolvedSchema, displayLabel, description } = useFormFieldLabel(

  rootSchema,

  props.scope,

  labelRef,

  fieldSchema,

  i18nKeyRef,

);



type SelectOption = { value: string; label: string };



const options = ref<SelectOption[]>([]);

const loading = ref(false);

const loadError = ref<string | null>(null);



const valuesSource = computed(() =>

  resolvedSchema.value ? readValuesSourceConfig(resolvedSchema.value) : undefined,

);



function resolveItems(data: unknown, config: FetchValuesSource): unknown[] {

  if (Array.isArray(data)) return data;

  if (!config.itemsPath) return [];

  const resolved = config.itemsPath.split(".").reduce<unknown>((current: unknown, segment: string) => {

    if (current && typeof current === "object") {

      return (current as Record<string, unknown>)[segment];

    }

    return undefined;

  }, data);

  return Array.isArray(resolved) ? resolved : [];

}



async function loadOptions(config: NonNullable<typeof valuesSource.value>) {

  if (isStaticValuesSource(config)) {

    options.value = config.values.map((entry: string) => ({ value: entry, label: entry }));

    loadError.value = null;

    return;

  }



  if (!isFetchValuesSource(config)) {

    options.value = [];

    return;

  }



  loading.value = true;

  loadError.value = null;

  try {

    const response = await fetch(config.url);

    if (!response.ok) {

      throw new Error(`${response.status} ${response.statusText}`);

    }

    const payload = await response.json();

    const items = resolveItems(payload, config);

    if (!Array.isArray(items)) {

      throw new Error("Response does not contain an option list");

    }



    const valueField = config.valueField ?? "id";

    const labelField = config.labelField ?? "name";

    options.value = items.map((item) => {

      if (item && typeof item === "object") {

        const record = item as Record<string, unknown>;

        const optionValue = record[valueField];

        const optionLabel = record[labelField] ?? optionValue;

        return {

          value: String(optionValue ?? ""),

          label: String(optionLabel ?? optionValue ?? ""),

        };

      }

      return { value: String(item), label: String(item) };

    });

  } catch (error) {

    options.value = [];

    loadError.value = error instanceof Error ? error.message : "Failed to load options";

  } finally {

    loading.value = false;

  }

}



watch(

  valuesSource,

  (config) => {

    if (!config) {

      options.value = [];

      loadError.value = null;

      return;

    }

    void loadOptions(config);

  },

  { immediate: true },

);

</script>



<template>

  <JseSchemaFormField :label="displayLabel" :description="description" :scope="scope">

    <JseSelect

      :model-value="value as string | number"

      class="jse-field__input"

      :disabled="readonly || loading"

      @update:model-value="value = $event"

    >

      <option v-if="loading" disabled value="">…</option>

      <option

        v-for="option in options"

        :key="`${option.value}-${option.label}`"

        :value="option.value"

      >

        {{ option.label }}

      </option>

    </JseSelect>

    <p v-if="loadError" class="jse-field__hint jse-field__hint--error">{{ loadError }}</p>

  </JseSchemaFormField>

</template>

// jsonschema-editor-react-extensions/src/components/ValuesSourceFormField.tsx
import { useEffect, useMemo, useState } from "react";
import {
  isFetchValuesSource,
  isStaticValuesSource,
  readValuesSourceConfig,
  type FetchValuesSource,
} from "@jsonschema-editor/json-schema-extensions";
import {
  JseSchemaFormField,
  JseSelect,
  useFormFieldLabel,
  useScopedField,
  type FormFieldProps,
} from "@jsonschema-editor/react";

type SelectOption = { value: string; label: string };

function resolveItems(data: unknown, config: FetchValuesSource): unknown[] {
  if (Array.isArray(data)) return data;
  if (!config.itemsPath) return [];
  const resolved = config.itemsPath.split(".").reduce<unknown>((current: unknown, segment: string) => {
    if (current && typeof current === "object") {
      return (current as Record<string, unknown>)[segment];
    }
    return undefined;
  }, data);
  return Array.isArray(resolved) ? resolved : [];
}

export function ValuesSourceFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  const [options, setOptions] = useState<SelectOption[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  const valuesSource = useMemo(
    () => (resolvedSchema ? readValuesSourceConfig(resolvedSchema) : undefined),
    [resolvedSchema],
  );

  useEffect(() => {
    if (!valuesSource) {
      setOptions([]);
      setLoadError(null);
      return;
    }

    let cancelled = false;

    async function loadOptions(config: NonNullable<typeof valuesSource>): Promise<void> {
      if (isStaticValuesSource(config)) {
        if (!cancelled) {
          setOptions(config.values.map((entry: string) => ({ value: entry, label: entry })));
          setLoadError(null);
        }
        return;
      }

      if (!isFetchValuesSource(config)) {
        if (!cancelled) setOptions([]);
        return;
      }

      setLoading(true);
      setLoadError(null);

      try {
        const response = await fetch(config.url);
        if (!response.ok) {
          throw new Error(`${response.status} ${response.statusText}`);
        }
        const payload = await response.json();
        const items = resolveItems(payload, config);
        if (!Array.isArray(items)) {
          throw new Error("Response does not contain an option list");
        }

        const valueField = config.valueField ?? "id";
        const labelField = config.labelField ?? "name";
        const nextOptions = items.map((item) => {
          if (item && typeof item === "object") {
            const record = item as Record<string, unknown>;
            const optionValue = record[valueField];
            const optionLabel = record[labelField] ?? optionValue;
            return {
              value: String(optionValue ?? ""),
              label: String(optionLabel ?? optionValue ?? ""),
            };
          }
          return { value: String(item), label: String(item) };
        });

        if (!cancelled) setOptions(nextOptions);
      } catch (error) {
        if (!cancelled) {
          setOptions([]);
          setLoadError(error instanceof Error ? error.message : "Failed to load options");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    void loadOptions(valuesSource);

    return () => {
      cancelled = true;
    };
  }, [valuesSource]);

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      <JseSelect
        className="jse-field__input"
        modelValue={typeof value === "string" || typeof value === "number" ? value : ""}
        disabled={readonly || loading}
        onModelValueChange={setValue}
      >
        {loading ? (
          <option disabled value="">
            …
          </option>
        ) : null}
        {options.map((option) => (
          <option key={`${option.value}-${option.label}`} value={option.value}>
            {option.label}
          </option>
        ))}
      </JseSelect>
      {loadError ? <p className="jse-field__hint jse-field__hint--error">{loadError}</p> : null}
    </JseSchemaFormField>
  );
}
