// jsonschema-editor-examples/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, shallowRef, watch } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { JsonSchemaForm, JsonSchemaFormEditor, type JseLocale } from "@jsonschema-editor/vue";
import {
  defaultExampleId,
  exampleCatalog,
  exampleCategoryOrder,
  exampleManifests,
  examplesByCategory,
  type ExampleId,
} from "./examples/catalog";
import { loadExampleFromJson } from "./examples/load-example";
import { appUiFor, categoryLabelFor, fallbackLocaleFor, localeOptions } from "./app-i18n";
import { navigateToPage, pageFromHash, type AppPage } from "./app-routing";
import GetStartedPage from "./GetStartedPage.vue";
import ImprintPage from "./ImprintPage.vue";

type WorkspaceMode = "form" | "editor" | "json";
type JsonPane = "schema" | "ui" | "data";

const initial = loadExampleFromJson(exampleCatalog[defaultExampleId]);

const activePage = ref<AppPage>(pageFromHash());
const activeExampleId = ref<ExampleId>(defaultExampleId);
const locale = ref<JseLocale>("de");
const schema = shallowRef<SchemaDocument>(initial.schema);
const uiSchema = shallowRef<UiSchema>(initial.uiSchema);
const formData = ref<Record<string, unknown>>(initial.defaults);
const mode = ref<WorkspaceMode>("form");
const jsonPane = ref<JsonPane>("schema");

const ui = computed(() => appUiFor(locale.value));
const fallbackLocale = computed(() => fallbackLocaleFor(locale.value));
const activeExample = computed(() => exampleCatalog[activeExampleId.value]);

const visibleCategories = computed(() =>
  exampleCategoryOrder.filter((category) => examplesByCategory[category].length > 0),
);

const schemaJson = computed(() => JSON.stringify(schema.value.toJSON(), null, 2));
const uiSchemaJson = computed(() => JSON.stringify(uiSchema.value.toJSON(), null, 2));
const dataJson = computed(() => JSON.stringify(formData.value, null, 2));

const activeJsonContent = computed(() => {
  if (jsonPane.value === "schema") return schemaJson.value;
  if (jsonPane.value === "ui") return uiSchemaJson.value;
  return dataJson.value;
});

function syncPageFromHash() {
  activePage.value = pageFromHash();
}

function openGetStarted() {
  navigateToPage("get-started");
}

function openImprint() {
  navigateToPage("imprint");
}

function openExamples() {
  navigateToPage("examples");
}

function loadExample(id: ExampleId) {
  const loaded = loadExampleFromJson(exampleCatalog[id]);
  schema.value = loaded.schema;
  uiSchema.value = loaded.uiSchema;
  formData.value = loaded.defaults;
}

function selectExample(id: ExampleId) {
  openExamples();
  activeExampleId.value = id;
}

watch(activeExampleId, (id) => loadExample(id));

onMounted(() => {
  syncPageFromHash();
  window.addEventListener("hashchange", syncPageFromHash);
});

onUnmounted(() => {
  window.removeEventListener("hashchange", syncPageFromHash);
});
</script>

<template>
  <div class="app">
    <header class="app__topbar">
      <div class="app__topbar-start">
        <a href="#/" class="app__brand" aria-label="JSON Schema Editor" @click.prevent="openExamples">
          <span class="app__brand-prefix">{{ ui.brandPrefix }}</span>
          <span class="app__brand-suffix">{{ ui.brandSuffix }}</span>
        </a>
        <nav class="app__topnav" :aria-label="ui.topNavAria">
          <a
            href="#/get-started"
            class="app__topnav-link"
            :class="{ 'app__topnav-link--active': activePage === 'get-started' }"
            :aria-current="activePage === 'get-started' ? 'page' : undefined"
            @click.prevent="openGetStarted"
          >
            {{ ui.navGetStarted }}
          </a>
          <a
            href="#/"
            class="app__topnav-link"
            :class="{ 'app__topnav-link--active': activePage === 'examples' }"
            :aria-current="activePage === 'examples' ? 'page' : undefined"
            @click.prevent="openExamples"
          >
            {{ ui.navExamples }}
          </a>
          <a
            href="#/imprint"
            class="app__topnav-link"
            :class="{ 'app__topnav-link--active': activePage === 'imprint' }"
            :aria-current="activePage === 'imprint' ? 'page' : undefined"
            @click.prevent="openImprint"
          >
            {{ ui.navImprint }}
          </a>
        </nav>
      </div>
      <div class="app__topbar-actions">
        <label class="app__locale-picker" for="app-locale-select">
          <span class="app__locale-label">{{ ui.localeLabel }}</span>
          <select id="app-locale-select" v-model="locale" class="app__select">
            <option v-for="option in localeOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>
      </div>
    </header>

    <section v-if="activePage === 'examples'" class="app__hero">
      <p class="app__tagline">{{ ui.tagline }}</p>
      <p class="app__subtitle">{{ ui.subtitle }}</p>
    </section>

    <GetStartedPage
      v-if="activePage === 'get-started'"
      :locale="locale"
      @open-examples="openExamples"
    />

    <ImprintPage v-else-if="activePage === 'imprint'" :locale="locale" />

    <div v-else class="app__workspace">
      <aside class="app__sidebar" :aria-label="ui.scenariosHeading">
        <h2 class="app__sidebar-heading">{{ ui.scenariosHeading }}</h2>
        <nav v-for="category in visibleCategories" :key="category" class="app__nav-group">
          <h3 class="app__nav-group-title">{{ categoryLabelFor(locale, category) }}</h3>
          <ul class="app__nav-list">
            <li v-for="entry in examplesByCategory[category]" :key="entry.id">
              <button
                type="button"
                class="app__nav-item"
                :class="{ 'app__nav-item--active': activeExampleId === entry.id }"
                :aria-current="activeExampleId === entry.id ? 'page' : undefined"
                @click="selectExample(entry.id)"
              >
                <span class="app__nav-item-label">{{ entry.label }}</span>
                <span class="app__nav-item-tagline">{{ entry.tagline }}</span>
              </button>
            </li>
          </ul>
        </nav>
      </aside>

      <main class="app__main">
        <select
          id="app-example-select"
          v-model="activeExampleId"
          class="app__example-select-hidden"
          tabindex="-1"
          aria-hidden="true"
        >
          <option v-for="entry in exampleManifests" :key="entry.id" :value="entry.id">
            {{ entry.label }}
          </option>
        </select>

        <header v-if="activeExample" class="app__scenario-header">
          <h1 id="json-schema-editor-beispiel" class="app__scenario-title">
            {{ activeExample.label }}
          </h1>
          <p class="app__scenario-desc">{{ activeExample.description }}</p>
        </header>

        <section class="app__panel">
          <div class="app__view-tabs" role="tablist" :aria-label="ui.tabsAria">
            <button
              type="button"
              role="tab"
              class="app__view-tab"
              :class="{ 'app__view-tab--active': mode === 'form' }"
              :aria-selected="mode === 'form'"
              aria-controls="app-panel-form"
              @click="mode = 'form'"
            >
              {{ ui.tabForm }}
            </button>
            <button
              type="button"
              role="tab"
              class="app__view-tab"
              :class="{ 'app__view-tab--active': mode === 'editor' }"
              :aria-selected="mode === 'editor'"
              aria-controls="app-panel-editor"
              @click="mode = 'editor'"
            >
              {{ ui.tabEditor }}
            </button>
            <button
              type="button"
              role="tab"
              class="app__view-tab"
              :class="{ 'app__view-tab--active': mode === 'json' }"
              :aria-selected="mode === 'json'"
              aria-controls="app-panel-json"
              @click="mode = 'json'"
            >
              {{ ui.tabJson }}
            </button>
          </div>

          <div
            v-if="mode === 'form'"
            id="app-panel-form"
            class="app__panel-body app__split"
            role="tabpanel"
            :aria-label="ui.formPanelAria"
          >
            <div class="app__split-main">
              <JsonSchemaForm
                v-model="formData"
                :schema="schema"
                :ui-schema="uiSchema"
                :locale="locale"
                :fallback-locale="fallbackLocale"
              />
            </div>
            <aside class="app__split-side">
              <div class="app__code-header">{{ ui.dataPanelTitle }}</div>
              <pre class="app__form-data-output app__code-block">{{ dataJson }}</pre>
            </aside>
          </div>

          <div
            v-if="mode === 'editor'"
            id="app-panel-editor"
            class="app__panel-body"
            role="tabpanel"
            :aria-label="ui.editorPanelAria"
          >
            <JsonSchemaFormEditor
              v-model:schema="schema"
              v-model:ui-schema="uiSchema"
              :locale="locale"
              :fallback-locale="fallbackLocale"
            />
          </div>

          <div
            v-if="mode === 'json'"
            id="app-panel-json"
            class="app__panel-body app__json-view"
            role="tabpanel"
            :aria-label="ui.jsonPanelAria"
          >
            <div class="app__json-tabs" role="tablist" :aria-label="ui.jsonTabsAria">
              <button
                type="button"
                role="tab"
                class="app__json-tab"
                :class="{ 'app__json-tab--active': jsonPane === 'schema' }"
                :aria-selected="jsonPane === 'schema'"
                @click="jsonPane = 'schema'"
              >
                {{ ui.jsonSchema }}
              </button>
              <button
                type="button"
                role="tab"
                class="app__json-tab"
                :class="{ 'app__json-tab--active': jsonPane === 'ui' }"
                :aria-selected="jsonPane === 'ui'"
                @click="jsonPane = 'ui'"
              >
                {{ ui.jsonUi }}
              </button>
              <button
                type="button"
                role="tab"
                class="app__json-tab"
                :class="{ 'app__json-tab--active': jsonPane === 'data' }"
                :aria-selected="jsonPane === 'data'"
                @click="jsonPane = 'data'"
              >
                {{ ui.jsonData }}
              </button>
            </div>
            <pre class="app__json-output app__code-block app__code-block--full">{{ activeJsonContent }}</pre>
          </div>
        </section>
      </main>
    </div>

    <footer class="app__footer">
      <p class="app__footer-copy">{{ ui.footerCopyright }}</p>
      <a
        href="#/imprint"
        class="app__footer-link"
        :aria-current="activePage === 'imprint' ? 'page' : undefined"
        @click.prevent="openImprint"
      >
        {{ ui.footerImprint }}
      </a>
    </footer>
  </div>
</template>

// jsonschema-editor-examples-react/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { JsonSchemaForm, JsonSchemaFormEditor } from "@jsonschema-editor/react";
import {
  createInMemoryFileFieldProvider,
  FileFieldProvider,
} from "@jsonschema-editor/react-extensions";
import type { AppLocale } from "./types/locale.js";
import {
  appUiFor,
  categoryLabelFor,
  fallbackLocaleFor,
  localeOptions,
} from "./app-i18n.js";
import {
  navigateToPage,
  pageFromHash,
  type AppPage,
} from "./app-routing.js";
import {
  defaultReactExampleId,
  exampleCatalog,
  exampleCategoryOrder,
  examplesByCategory,
  exampleManifests,
  type ExampleCategory,
  type ExampleId,
} from "./examples/catalog.js";
import { loadExampleFromJson } from "./examples/load-example.js";
import { seedDemoFilesForExample } from "../../jsonschema-editor-examples/src/examples/demo-file-seeds.js";
import { GetStartedPage } from "./pages/GetStartedPage.js";
import { ImprintPage } from "./pages/ImprintPage.js";

type WorkspaceMode = "form" | "editor" | "json";
type JsonPane = "schema" | "ui" | "data";

const initial = loadExampleFromJson(exampleCatalog[defaultReactExampleId]);
const fileProvider = createInMemoryFileFieldProvider();

export function App() {
  const [activePage, setActivePage] = useState<AppPage>(() => pageFromHash());
  const [activeExampleId, setActiveExampleId] = useState<ExampleId>(defaultReactExampleId);
  const [locale, setLocale] = useState<AppLocale>("de");
  const [schema, setSchema] = useState<SchemaDocument>(initial.schema);
  const [uiSchema, setUiSchema] = useState<UiSchema>(initial.uiSchema);
  const [formData, setFormData] = useState<Record<string, unknown>>(initial.defaults);
  const [mode, setMode] = useState<WorkspaceMode>("form");
  const [jsonPane, setJsonPane] = useState<JsonPane>("schema");

  const ui = appUiFor(locale);
  const fallbackLocale = fallbackLocaleFor(locale);
  const activeExample = exampleCatalog[activeExampleId];

  const visibleCategories = useMemo(
    () =>
      exampleCategoryOrder.filter(
        (category: ExampleCategory) => examplesByCategory[category].length > 0,
      ),
    [],
  );

  const schemaJson = useMemo(() => JSON.stringify(schema.toJSON(), null, 2), [schema]);
  const uiSchemaJson = useMemo(() => JSON.stringify(uiSchema.toJSON(), null, 2), [uiSchema]);
  const dataJson = useMemo(() => JSON.stringify(formData, null, 2), [formData]);

  const activeJsonContent =
    jsonPane === "schema" ? schemaJson : jsonPane === "ui" ? uiSchemaJson : dataJson;

  const syncPageFromHash = useCallback(() => {
    setActivePage(pageFromHash());
  }, []);

  useEffect(() => {
    syncPageFromHash();
    window.addEventListener("hashchange", syncPageFromHash);
    return () => window.removeEventListener("hashchange", syncPageFromHash);
  }, [syncPageFromHash]);

  useEffect(() => {
    const loaded = loadExampleFromJson(exampleCatalog[activeExampleId]);
    let cancelled = false;

    void (async () => {
      await seedDemoFilesForExample(fileProvider, activeExampleId);
      if (cancelled) return;
      setSchema(loaded.schema);
      setUiSchema(loaded.uiSchema);
      setFormData(loaded.defaults);
    })();

    return () => {
      cancelled = true;
    };
  }, [activeExampleId]);

  function openGetStarted() {
    navigateToPage("get-started");
  }

  function openImprint() {
    navigateToPage("imprint");
  }

  function openExamples() {
    navigateToPage("examples");
  }

  function selectExample(id: ExampleId) {
    openExamples();
    setActiveExampleId(id);
  }

  return (
    <FileFieldProvider provider={fileProvider}>
      <div className="app">
      <header className="app__topbar">
        <div className="app__topbar-start">
          <a
            href="#/"
            className="app__brand"
            aria-label="JSON Schema Editor"
            onClick={(event) => {
              event.preventDefault();
              openExamples();
            }}
          >
            <span className="app__brand-prefix">{ui.brandPrefix}</span>
            <span className="app__brand-suffix">{ui.brandSuffix}</span>
            <span className="app__react-badge">{ui.reactBadge}</span>
          </a>
          <nav className="app__topnav" aria-label={ui.topNavAria}>
            <a
              href="#/get-started"
              className={`app__topnav-link${activePage === "get-started" ? " app__topnav-link--active" : ""}`}
              aria-current={activePage === "get-started" ? "page" : undefined}
              onClick={(event) => {
                event.preventDefault();
                openGetStarted();
              }}
            >
              {ui.navGetStarted}
            </a>
            <a
              href="#/"
              className={`app__topnav-link${activePage === "examples" ? " app__topnav-link--active" : ""}`}
              aria-current={activePage === "examples" ? "page" : undefined}
              onClick={(event) => {
                event.preventDefault();
                openExamples();
              }}
            >
              {ui.navExamples}
            </a>
            <a
              href="#/imprint"
              className={`app__topnav-link${activePage === "imprint" ? " app__topnav-link--active" : ""}`}
              aria-current={activePage === "imprint" ? "page" : undefined}
              onClick={(event) => {
                event.preventDefault();
                openImprint();
              }}
            >
              {ui.navImprint}
            </a>
          </nav>
        </div>
        <div className="app__topbar-actions">
          <label className="app__locale-picker" htmlFor="app-locale-select">
            <span className="app__locale-label">{ui.localeLabel}</span>
            <select
              id="app-locale-select"
              className="app__select"
              value={locale}
              onChange={(event) => setLocale(event.target.value as AppLocale)}
            >
              {localeOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </label>
        </div>
      </header>

      {activePage === "examples" ? (
        <section className="app__hero">
          <p className="app__tagline">{ui.tagline}</p>
          <p className="app__subtitle">{ui.subtitle}</p>
        </section>
      ) : null}

      {activePage === "get-started" ? (
        <GetStartedPage locale={locale} onOpenExamples={openExamples} />
      ) : null}

      {activePage === "imprint" ? <ImprintPage locale={locale} /> : null}

      {activePage === "examples" ? (
        <div className="app__workspace">
          <aside className="app__sidebar" aria-label={ui.scenariosHeading}>
            <h2 className="app__sidebar-heading">{ui.scenariosHeading}</h2>
            {visibleCategories.map((category: ExampleCategory) => (
              <nav key={category} className="app__nav-group">
                <h3 className="app__nav-group-title">{categoryLabelFor(locale, category)}</h3>
                <ul className="app__nav-list">
                  {examplesByCategory[category].map((entry) => (
                    <li key={entry.id}>
                      <button
                        type="button"
                        className={`app__nav-item${activeExampleId === entry.id ? " app__nav-item--active" : ""}`}
                        aria-current={activeExampleId === entry.id ? "page" : undefined}
                        onClick={() => selectExample(entry.id)}
                      >
                        <span className="app__nav-item-label">{entry.label}</span>
                        <span className="app__nav-item-tagline">{entry.tagline}</span>
                      </button>
                    </li>
                  ))}
                </ul>
              </nav>
            ))}
          </aside>

          <main className="app__main">
            <select
              id="app-example-select"
              className="app__example-select-hidden"
              tabIndex={-1}
              aria-hidden="true"
              value={activeExampleId}
              onChange={(event) => setActiveExampleId(event.target.value as ExampleId)}
            >
              {exampleManifests.map((entry) => (
                <option key={entry.id} value={entry.id}>
                  {entry.label}
                </option>
              ))}
            </select>

            {activeExample ? (
              <header className="app__scenario-header">
                <h1 id="json-schema-editor-beispiel" className="app__scenario-title">
                  {activeExample.label}
                </h1>
                <p className="app__scenario-desc">{activeExample.description}</p>
              </header>
            ) : null}

            <div className="app__react-notice" role="note">
              <strong>{ui.reactNoticeTitle}:</strong> {ui.reactNoticeBody}
            </div>

            <section className="app__panel">
              <div className="app__view-tabs" role="tablist" aria-label={ui.tabsAria}>
                <button
                  type="button"
                  role="tab"
                  className={`app__view-tab${mode === "form" ? " app__view-tab--active" : ""}`}
                  aria-selected={mode === "form"}
                  aria-controls="app-panel-form"
                  onClick={() => setMode("form")}
                >
                  {ui.tabForm}
                </button>
                <button
                  type="button"
                  role="tab"
                  className={`app__view-tab${mode === "editor" ? " app__view-tab--active" : ""}`}
                  aria-selected={mode === "editor"}
                  aria-controls="app-panel-editor"
                  onClick={() => setMode("editor")}
                >
                  {ui.tabEditor}
                </button>
                <button
                  type="button"
                  role="tab"
                  className={`app__view-tab${mode === "json" ? " app__view-tab--active" : ""}`}
                  aria-selected={mode === "json"}
                  aria-controls="app-panel-json"
                  onClick={() => setMode("json")}
                >
                  {ui.tabJson}
                </button>
              </div>

              {mode === "form" ? (
                <div
                  id="app-panel-form"
                  className="app__panel-body app__split"
                  role="tabpanel"
                  aria-label={ui.formPanelAria}
                >
                  <div className="app__split-main">
                    <JsonSchemaForm
                      schema={schema}
                      uiSchema={uiSchema}
                      data={formData}
                      onDataChange={setFormData}
                      locale={locale}
                      fallbackLocale={fallbackLocale}
                      validationMode="blur"
                    />
                  </div>
                  <aside className="app__split-side">
                    <div className="app__code-header">{ui.dataPanelTitle}</div>
                    <pre className="app__form-data-output app__code-block">{dataJson}</pre>
                  </aside>
                </div>
              ) : null}

              {mode === "editor" ? (
                <div
                  id="app-panel-editor"
                  className="app__panel-body"
                  role="tabpanel"
                  aria-label={ui.editorPanelAria}
                >
                  <JsonSchemaFormEditor
                    key={activeExampleId}
                    schema={schema}
                    uiSchema={uiSchema}
                    onSchemaChange={setSchema}
                    onUiSchemaChange={setUiSchema}
                    locale={locale}
                    fallbackLocale={fallbackLocale}
                  />
                </div>
              ) : null}

              {mode === "json" ? (
                <div
                  id="app-panel-json"
                  className="app__panel-body app__json-view"
                  role="tabpanel"
                  aria-label={ui.jsonPanelAria}
                >
                  <div className="app__json-tabs" role="tablist" aria-label={ui.jsonTabsAria}>
                    {(["schema", "ui", "data"] as const).map((pane) => (
                      <button
                        key={pane}
                        type="button"
                        role="tab"
                        className={`app__json-tab${jsonPane === pane ? " app__json-tab--active" : ""}`}
                        aria-selected={jsonPane === pane}
                        onClick={() => setJsonPane(pane)}
                      >
                        {pane === "schema"
                          ? ui.jsonSchema
                          : pane === "ui"
                            ? ui.jsonUi
                            : ui.jsonData}
                      </button>
                    ))}
                  </div>
                  <pre className="app__json-output app__code-block app__code-block--full">
                    {activeJsonContent}
                  </pre>
                </div>
              ) : null}
            </section>
          </main>
        </div>
      ) : null}

      <footer className="app__footer">
        <p className="app__footer-copy">{ui.footerCopyright}</p>
        <a
          href="#/imprint"
          className="app__footer-link"
          aria-current={activePage === "imprint" ? "page" : undefined}
          onClick={(event) => {
            event.preventDefault();
            openImprint();
          }}
        >
          {ui.footerImprint}
        </a>
      </footer>
      </div>
    </FileFieldProvider>
  );
}
