// jsonschema-editor-react/src/components/organisms/SchemaStructureEditor.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import { SchemaTreeNode } from "../molecules/tree/SchemaTreeNode.js";
import { SchemaDefsTreeNode } from "../molecules/tree/SchemaDefsTreeNode.js";
import { SchemaAttributesPanel } from "../molecules/panels/SchemaAttributesPanel.js";
import {
  JseFloatingPanel,
  type JseFloatingPanelHandle,
} from "../molecules/JseFloatingPanel.js";
import { SchemaElementActions } from "../molecules/SchemaElementActions.js";
import {
  DEFS_SEGMENT,
  getDocumentKindLabel,
  getDocumentNodeLabel,
  isDefsContainerPath,
  isValidDocumentPath,
  removeNodeAtPath,
  tryGetNodeAtPath,
} from "../../utils/schema-document.js";
import { schemaPathKey, type SchemaPath } from "../../utils/schema-editor.js";
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface SchemaStructureEditorProps {
  document: SchemaDocument;
  selectedPath: SchemaPath;
  onDocumentChange: (document: SchemaDocument) => void;
  onSelectedPathChange: (path: SchemaPath) => void;
}

function pathsOverlap(deletedPath: SchemaPath, targetPath: SchemaPath): boolean {
  if (targetPath.length === 0) return false;
  if (deletedPath.length > targetPath.length) return false;
  return deletedPath.every((segment, index) => segment === targetPath[index]);
}

export function SchemaStructureEditor({
  document,
  selectedPath,
  onDocumentChange,
  onSelectedPathChange,
}: SchemaStructureEditorProps) {
  const { t } = useJseI18n();

  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(
    () => new Set(["root", DEFS_SEGMENT]),
  );
  const [addDialogOpen, setAddDialogOpen] = useState(false);
  const [attributesDialogOpen, setAttributesDialogOpen] = useState(false);
  const [addTargetPath, setAddTargetPath] = useState<SchemaPath>([]);
  const [attributesTargetPath, setAttributesTargetPath] = useState<SchemaPath>([]);
  const addPanelRef = useRef<JseFloatingPanelHandle>(null);
  const attributesPanelRef = useRef<JseFloatingPanelHandle>(null);

  useEffect(() => {
    setExpandedKeys((current) => {
      const next = new Set(current);
      next.add("root");
      next.add(DEFS_SEGMENT);
      return next;
    });

    if (!isValidDocumentPath(document, attributesTargetPath)) {
      setAttributesDialogOpen(false);
      setAttributesTargetPath([]);
    }
    if (!isValidDocumentPath(document, addTargetPath)) {
      setAddDialogOpen(false);
      setAddTargetPath([]);
    }
    if (!isValidDocumentPath(document, selectedPath)) {
      onSelectedPathChange([]);
    }
  }, [addTargetPath, attributesTargetPath, document, onSelectedPathChange, selectedPath]);

  const selectedLabel = useMemo(() => {
    const node = tryGetNodeAtPath(document, selectedPath);
    if (!node) return t("schemaStructure.noSelection");
    return getDocumentNodeLabel(node, selectedPath);
  }, [document, selectedPath, t]);

  const selectedKind = useMemo(() => {
    const node = tryGetNodeAtPath(document, selectedPath);
    return node ? getDocumentKindLabel(node) : "";
  }, [document, selectedPath]);

  const attributesPanelTitle = useMemo(() => {
    const node = tryGetNodeAtPath(document, attributesTargetPath);
    if (!node) return t("schemaStructure.attributesFallback");
    const label = getDocumentNodeLabel(node, attributesTargetPath);
    return t("schemaStructure.attributesTitle", { label });
  }, [attributesTargetPath, document, t]);

  const patchDocument = useCallback(
    (next: SchemaDocument, newPath?: SchemaPath) => {
      onDocumentChange(next);
      if (newPath) onSelectedPathChange(newPath);
    },
    [onDocumentChange, onSelectedPathChange],
  );

  const togglePath = useCallback((path: SchemaPath) => {
    const key = schemaPathKey(path);
    setExpandedKeys((current) => {
      const next = new Set(current);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }, []);

  const expandPath = useCallback((path: SchemaPath) => {
    setExpandedKeys((current) => new Set([...current, schemaPathKey(path)]));
  }, []);

  const anchorPanel = useCallback(
    (panelRef: React.RefObject<JseFloatingPanelHandle | null>, event: React.MouseEvent) => {
      window.requestAnimationFrame(() => {
        const target = event.currentTarget;
        const row =
          target instanceof HTMLElement ? target.closest(".jse-tree-node__row") : null;
        if (row instanceof HTMLElement) panelRef.current?.anchorNear(row);
      });
    },
    [],
  );

  const openAddDialog = useCallback(
    (path: SchemaPath, event: React.MouseEvent) => {
      setAttributesDialogOpen(false);
      setAddTargetPath(path);
      onSelectedPathChange(path);
      setAddDialogOpen(true);
      anchorPanel(addPanelRef, event);
    },
    [anchorPanel, onSelectedPathChange],
  );

  const openAttributesDialog = useCallback(
    (path: SchemaPath, event: React.MouseEvent) => {
      if (!isValidDocumentPath(document, path)) return;
      setAddDialogOpen(false);
      setAttributesTargetPath(path);
      onSelectedPathChange(path);
      setAttributesDialogOpen(true);
      anchorPanel(attributesPanelRef, event);
    },
    [anchorPanel, document, onSelectedPathChange],
  );

  const deleteAtPath = useCallback(
    (path: SchemaPath) => {
      if (path.length === 0 || isDefsContainerPath(path)) return;
      if (pathsOverlap(path, attributesTargetPath)) {
        setAttributesDialogOpen(false);
        setAttributesTargetPath([]);
      }
      if (pathsOverlap(path, addTargetPath)) {
        setAddDialogOpen(false);
        setAddTargetPath([]);
      }
      patchDocument(removeNodeAtPath(document, path), []);
    },
    [addTargetPath, attributesTargetPath, document, patchDocument],
  );

  return (
    <div className="jse-structure-editor">
      <p className="jse-structure-editor__hint jse-structure-editor__hint--top">
        {t("schemaStructure.hint")}
      </p>

      <div
        className="jse-structure-editor__tree"
        role="tree"
        aria-label={t("schemaStructure.treeAria")}
      >
        <SchemaTreeNode
          document={document}
          path={[]}
          selectedPath={selectedPath}
          expandedKeys={expandedKeys}
          onSelect={onSelectedPathChange}
          onToggle={togglePath}
          onAdd={openAddDialog}
          onEdit={openAttributesDialog}
          onDelete={deleteAtPath}
        />
        <SchemaDefsTreeNode
          document={document}
          selectedPath={selectedPath}
          expandedKeys={expandedKeys}
          onSelect={onSelectedPathChange}
          onToggle={togglePath}
          onAdd={openAddDialog}
          onEdit={openAttributesDialog}
          onDelete={deleteAtPath}
        />
      </div>

      <div className="jse-structure-editor__status" aria-live="polite">
        <span className="jse-structure-editor__status-label">
          {t("schemaStructure.selected")}
        </span>
        {selectedKind ? <span className="jse-tree-node__kind">{selectedKind}</span> : null}
        <span className="jse-structure-editor__status-name">{selectedLabel}</span>
      </div>

      <JseFloatingPanel
        ref={addPanelRef}
        open={addDialogOpen}
        onOpenChange={setAddDialogOpen}
        title={t("schemaStructure.addElement")}
      >
        <SchemaElementActions
          document={document}
          targetPath={addTargetPath}
          onDocumentChange={(next) => {
            patchDocument(next);
            expandPath(addTargetPath);
          }}
          onDone={() => setAddDialogOpen(false)}
          onItemsSet={(arrayPath) => {
            expandPath(arrayPath);
            expandPath([...arrayPath, "items"]);
          }}
        />
      </JseFloatingPanel>

      <JseFloatingPanel
        ref={attributesPanelRef}
        open={attributesDialogOpen}
        onOpenChange={setAttributesDialogOpen}
        title={attributesPanelTitle}
        initialWidth={360}
        initialHeight={420}
      >
        {isValidDocumentPath(document, attributesTargetPath) ? (
          <SchemaAttributesPanel
            document={document}
            selectedPath={attributesTargetPath}
            onDocumentChange={(next) => patchDocument(next)}
            onSelectedPathChange={(path) => {
              setAttributesTargetPath(path);
              onSelectedPathChange(path);
            }}
          />
        ) : null}
      </JseFloatingPanel>
    </div>
  );
}

// jsonschema-editor-vue/src/components/organisms/SchemaStructureEditor.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import SchemaTreeNode from "../molecules/tree/SchemaTreeNode.vue";
import SchemaDefsTreeNode from "../molecules/tree/SchemaDefsTreeNode.vue";
import SchemaAttributesPanel from "../molecules/panels/SchemaAttributesPanel.vue";
import JseFloatingPanel from "../molecules/JseFloatingPanel.vue";
import SchemaElementActions from "../molecules/SchemaElementActions.vue";
import {
  DEFS_SEGMENT,
  getDocumentKindLabel,
  getDocumentNodeLabel,
  isDefsContainerPath,
  isValidDocumentPath,
  removeNodeAtPath,
  tryGetNodeAtPath,
} from "../../utils/schema-document";
import { schemaPathKey, type SchemaPath } from "../../utils/schema-editor";
import { useJseI18n } from "../../composables/useJseI18n";

const props = defineProps<{
  document: SchemaDocument;
  selectedPath: SchemaPath;
}>();

const emit = defineEmits<{
  "update:document": [document: SchemaDocument];
  "update:selectedPath": [path: SchemaPath];
}>();

const { t } = useJseI18n();

const expandedKeys = ref(new Set<string>(["root", DEFS_SEGMENT]));
const addDialogOpen = ref(false);
const attributesDialogOpen = ref(false);
const addTargetPath = ref<SchemaPath>([]);
const attributesTargetPath = ref<SchemaPath>([]);
const addPanelRef = ref<InstanceType<typeof JseFloatingPanel> | null>(null);
const attributesPanelRef = ref<InstanceType<typeof JseFloatingPanel> | null>(null);

watch(
  () => props.document,
  (document) => {
    expandedKeys.value.add("root");
    expandedKeys.value.add(DEFS_SEGMENT);

    if (!isValidDocumentPath(document, attributesTargetPath.value)) {
      attributesDialogOpen.value = false;
      attributesTargetPath.value = [];
    }
    if (!isValidDocumentPath(document, addTargetPath.value)) {
      addDialogOpen.value = false;
      addTargetPath.value = [];
    }
    if (!isValidDocumentPath(document, props.selectedPath)) {
      emit("update:selectedPath", []);
    }
  },
);

const selectedLabel = computed(() => {
  const node = tryGetNodeAtPath(props.document, props.selectedPath);
  if (!node) return t("schemaStructure.noSelection");
  return getDocumentNodeLabel(node, props.selectedPath);
});

const selectedKind = computed(() => {
  const node = tryGetNodeAtPath(props.document, props.selectedPath);
  return node ? getDocumentKindLabel(node) : "";
});

const attributesPanelTitle = computed(() => {
  const node = tryGetNodeAtPath(props.document, attributesTargetPath.value);
  if (!node) return t("schemaStructure.attributesFallback");
  const label = getDocumentNodeLabel(node, attributesTargetPath.value);
  return t("schemaStructure.attributesTitle", { label });
});

function pathsOverlap(deletedPath: SchemaPath, targetPath: SchemaPath): boolean {
  if (targetPath.length === 0) return false;
  if (deletedPath.length > targetPath.length) return false;
  return deletedPath.every((segment, index) => segment === targetPath[index]);
}

function selectPath(path: SchemaPath) {
  emit("update:selectedPath", path);
}

function togglePath(path: SchemaPath) {
  const key = schemaPathKey(path);
  const next = new Set(expandedKeys.value);
  if (next.has(key)) next.delete(key);
  else next.add(key);
  expandedKeys.value = next;
}

function patchDocument(next: SchemaDocument, newPath?: SchemaPath) {
  emit("update:document", next);
  if (newPath) emit("update:selectedPath", newPath);
}

function expandPath(path: SchemaPath) {
  expandedKeys.value = new Set([...expandedKeys.value, schemaPathKey(path)]);
}

async function anchorPanel(
  panelRef: InstanceType<typeof JseFloatingPanel> | null,
  event: MouseEvent,
) {
  await nextTick();
  const target = event.currentTarget;
  const row =
    target instanceof HTMLElement ? target.closest(".jse-tree-node__row") : null;
  if (row instanceof HTMLElement) panelRef?.anchorNear(row);
}

async function openAddDialog(path: SchemaPath, event: MouseEvent) {
  attributesDialogOpen.value = false;
  addTargetPath.value = path;
  emit("update:selectedPath", path);
  addDialogOpen.value = true;
  await anchorPanel(addPanelRef.value, event);
}

async function openAttributesDialog(path: SchemaPath, event: MouseEvent) {
  if (!isValidDocumentPath(props.document, path)) return;
  addDialogOpen.value = false;
  attributesTargetPath.value = path;
  emit("update:selectedPath", path);
  attributesDialogOpen.value = true;
  await anchorPanel(attributesPanelRef.value, event);
}

function deleteAtPath(path: SchemaPath) {
  if (path.length === 0 || isDefsContainerPath(path)) return;
  if (pathsOverlap(path, attributesTargetPath.value)) {
    attributesDialogOpen.value = false;
    attributesTargetPath.value = [];
  }
  if (pathsOverlap(path, addTargetPath.value)) {
    addDialogOpen.value = false;
    addTargetPath.value = [];
  }
  patchDocument(removeNodeAtPath(props.document, path), []);
}

function onDocumentUpdated(next: SchemaDocument) {
  patchDocument(next);
  expandPath(addTargetPath.value);
}

function onItemsSet(arrayPath: SchemaPath) {
  expandPath(arrayPath);
  expandPath([...arrayPath, "items"]);
}

function onAttributesPathChange(path: SchemaPath) {
  attributesTargetPath.value = path;
  emit("update:selectedPath", path);
}
</script>

<template>
  <div class="jse-structure-editor">
    <p class="jse-structure-editor__hint jse-structure-editor__hint--top">
      {{ t("schemaStructure.hint") }}
    </p>

    <div
      class="jse-structure-editor__tree"
      role="tree"
      :aria-label="t('schemaStructure.treeAria')"
    >
      <SchemaTreeNode
        :document="document"
        :path="[]"
        :selected-path="selectedPath"
        :expanded-keys="expandedKeys"
        @select="selectPath"
        @toggle="togglePath"
        @add="openAddDialog"
        @edit="openAttributesDialog"
        @delete="deleteAtPath"
      />

      <SchemaDefsTreeNode
        :document="document"
        :selected-path="selectedPath"
        :expanded-keys="expandedKeys"
        @select="selectPath"
        @toggle="togglePath"
        @add="openAddDialog"
        @edit="openAttributesDialog"
        @delete="deleteAtPath"
      />
    </div>

    <div class="jse-structure-editor__status" aria-live="polite">
      <span class="jse-structure-editor__status-label">{{ t("schemaStructure.selected") }}</span>
      <span v-if="selectedKind" class="jse-tree-node__kind">{{ selectedKind }}</span>
      <span class="jse-structure-editor__status-name">{{ selectedLabel }}</span>
    </div>

    <JseFloatingPanel ref="addPanelRef" v-model="addDialogOpen" :title="t('schemaStructure.addElement')">
      <SchemaElementActions
        :document="document"
        :target-path="addTargetPath"
        @update:document="onDocumentUpdated"
        @done="addDialogOpen = false"
        @items-set="(path) => onItemsSet(path)"
      />
    </JseFloatingPanel>

    <JseFloatingPanel
      ref="attributesPanelRef"
      v-model="attributesDialogOpen"
      :title="attributesPanelTitle"
      :initial-width="360"
      :initial-height="420"
    >
      <SchemaAttributesPanel
        v-if="isValidDocumentPath(document, attributesTargetPath)"
        :document="document"
        :selected-path="attributesTargetPath"
        @update:document="(next) => patchDocument(next)"
        @update:selected-path="onAttributesPathChange"
      />
    </JseFloatingPanel>
  </div>
</template>
