// jsonschema-editor-react/src/components/organisms/UiStructureEditor.tsx
import { useCallback, useMemo, useRef, useState } from "react";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import { UiTreeNode } from "../molecules/tree/UiTreeNode.js";
import { UiLayoutEditor } from "./UiLayoutEditor.js";
import { UiAttributesPanel } from "../molecules/panels/UiAttributesPanel.js";
import {
  JseFloatingPanel,
  type JseFloatingPanelHandle,
} from "../molecules/JseFloatingPanel.js";
import { UiElementActions } from "../molecules/UiElementActions.js";
import {
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  moveUiElement,
  moveUiElementTo,
  removeUiElement,
  uiPathKey,
  type UiPath,
} from "../../utils/ui-editor.js";
import { useJseI18n } from "../../context/JseI18nContext.js";

export interface UiStructureEditorProps {
  root: UiElement;
  selectedPath: UiPath;
  onRootChange: (root: UiElement) => void;
  onSelectedPathChange: (path: UiPath) => void;
}

export function UiStructureEditor({
  root,
  selectedPath,
  onRootChange,
  onSelectedPathChange,
}: UiStructureEditorProps) {
  const { t } = useJseI18n();

  const [viewMode, setViewMode] = useState<"tree" | "layout">("layout");
  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(() => new Set(["root"]));
  const [dragSourcePath, setDragSourcePath] = useState<UiPath | null>(null);
  const [addDialogOpen, setAddDialogOpen] = useState(false);
  const [attributesDialogOpen, setAttributesDialogOpen] = useState(false);
  const [addTargetPath, setAddTargetPath] = useState<UiPath>([]);
  const [attributesTargetPath, setAttributesTargetPath] = useState<UiPath>([]);
  const addPanelRef = useRef<JseFloatingPanelHandle>(null);
  const attributesPanelRef = useRef<JseFloatingPanelHandle>(null);

  const attributesPanelTitle = useMemo(() => {
    try {
      const element = getUiElementAt(root, attributesTargetPath);
      const label = getUiElementLabel(element);
      return t("uiStructure.attributesTitle", { label });
    } catch {
      return t("uiStructure.attributesFallback");
    }
  }, [attributesTargetPath, root, t]);

  const selectedLabel = useMemo(() => {
    try {
      const element = getUiElementAt(root, selectedPath);
      return getUiElementLabel(element);
    } catch {
      return t("uiStructure.noSelection");
    }
  }, [root, selectedPath, t]);

  const patchRoot = useCallback(
    (next: UiElement, path?: UiPath) => {
      onRootChange(next);
      if (path) onSelectedPathChange(path);
    },
    [onRootChange, onSelectedPathChange],
  );

  const togglePath = useCallback((path: UiPath) => {
    const key = uiPathKey(path);
    setExpandedKeys((current) => {
      const next = new Set(current);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }, []);

  const expandPath = useCallback((path: UiPath) => {
    setExpandedKeys((current) => new Set([...current, uiPathKey(path)]));
  }, []);

  const anchorPanel = useCallback(
    (panelRef: React.RefObject<JseFloatingPanelHandle | null>, event: React.MouseEvent) => {
      window.requestAnimationFrame(() => {
        const target = event.currentTarget;
        const row =
          target instanceof HTMLElement
            ? (target.closest(".jse-tree-node__row") ??
              target.closest(".jse-layout-block__header"))
            : null;
        if (row instanceof HTMLElement) panelRef.current?.anchorNear(row);
      });
    },
    [],
  );

  const openAddDialog = useCallback(
    (path: UiPath, event: React.MouseEvent) => {
      setAttributesDialogOpen(false);
      setAddTargetPath(path);
      onSelectedPathChange(path);
      setAddDialogOpen(true);
      anchorPanel(addPanelRef, event);
    },
    [anchorPanel, onSelectedPathChange],
  );

  const openAttributesDialog = useCallback(
    (path: UiPath, event: React.MouseEvent) => {
      setAddDialogOpen(false);
      setAttributesTargetPath(path);
      onSelectedPathChange(path);
      setAttributesDialogOpen(true);
      anchorPanel(attributesPanelRef, event);
    },
    [anchorPanel, onSelectedPathChange],
  );

  const deleteAtPath = useCallback(
    (path: UiPath) => {
      if (path.length === 0) return;
      patchRoot(removeUiElement(root, path), []);
    },
    [patchRoot, root],
  );

  const onTreeDrop = useCallback(
    (targetPath: UiPath, sourcePath: UiPath) => {
      setDragSourcePath(null);
      if (uiPathKey(sourcePath) === uiPathKey(targetPath)) return;

      const sourceParent = sourcePath.slice(0, -1);
      const targetParent = targetPath.slice(0, -1);

      if (uiPathKey(sourceParent) === uiPathKey(targetParent)) {
        patchRoot(moveUiElement(root, sourcePath, targetPath));
        return;
      }

      const targetElement = getUiElementAt(root, targetPath);
      if (isLayoutElement(targetElement)) {
        patchRoot(
          moveUiElementTo(root, sourcePath, targetPath, targetElement.elements.length),
          sourcePath,
        );
        return;
      }

      patchRoot(
        moveUiElementTo(
          root,
          sourcePath,
          targetParent,
          Number(targetPath[targetPath.length - 1]),
        ),
        sourcePath,
      );
    },
    [patchRoot, root],
  );

  return (
    <div className="jse-structure-editor">
      <div
        className="jse-structure-editor__view-toggle"
        role="tablist"
        aria-label={t("uiStructure.viewToggleAria")}
      >
        <button
          type="button"
          role="tab"
          className={[
            "jse-structure-editor__view-tab",
            viewMode === "layout" ? "jse-structure-editor__view-tab--active" : "",
          ]
            .filter(Boolean)
            .join(" ")}
          aria-selected={viewMode === "layout"}
          onClick={() => setViewMode("layout")}
        >
          {t("uiStructure.viewLayout")}
        </button>
        <button
          type="button"
          role="tab"
          className={[
            "jse-structure-editor__view-tab",
            viewMode === "tree" ? "jse-structure-editor__view-tab--active" : "",
          ]
            .filter(Boolean)
            .join(" ")}
          aria-selected={viewMode === "tree"}
          onClick={() => setViewMode("tree")}
        >
          {t("uiStructure.viewTree")}
        </button>
      </div>

      <p className="jse-structure-editor__hint jse-structure-editor__hint--top">
        {viewMode === "layout" ? t("uiStructure.hintLayout") : t("uiStructure.hintTree")}
      </p>

      {viewMode === "layout" ? (
        <UiLayoutEditor
          root={root}
          selectedPath={selectedPath}
          onRootChange={patchRoot}
          onSelectedPathChange={onSelectedPathChange}
          onAdd={openAddDialog}
          onEdit={openAttributesDialog}
          onDelete={deleteAtPath}
        />
      ) : (
        <div
          className="jse-structure-editor__tree"
          role="tree"
          aria-label={t("uiStructure.treeAria")}
          onDragEnd={() => setDragSourcePath(null)}
        >
          <UiTreeNode
            root={root}
            path={[]}
            selectedPath={selectedPath}
            expandedKeys={expandedKeys}
            dragSourcePath={dragSourcePath}
            onSelect={onSelectedPathChange}
            onToggle={togglePath}
            onAdd={openAddDialog}
            onEdit={openAttributesDialog}
            onDelete={deleteAtPath}
            onDragStart={setDragSourcePath}
            onDrop={onTreeDrop}
          />
        </div>
      )}

      <div className="jse-structure-editor__status" aria-live="polite">
        <span className="jse-structure-editor__status-label">{t("uiStructure.selected")}</span>
        <span className="jse-structure-editor__status-name">{selectedLabel}</span>
      </div>

      <JseFloatingPanel
        ref={addPanelRef}
        open={addDialogOpen}
        onOpenChange={setAddDialogOpen}
        title={t("uiStructure.addElement")}
      >
        <UiElementActions
          root={root}
          targetPath={addTargetPath}
          onRootChange={(next) => {
            patchRoot(next);
            expandPath(addTargetPath);
          }}
          onDone={() => setAddDialogOpen(false)}
        />
      </JseFloatingPanel>

      <JseFloatingPanel
        ref={attributesPanelRef}
        open={attributesDialogOpen}
        onOpenChange={setAttributesDialogOpen}
        title={attributesPanelTitle}
        initialWidth={380}
        initialHeight={360}
      >
        <UiAttributesPanel
          root={root}
          selectedPath={attributesTargetPath}
          onRootChange={(next) => patchRoot(next)}
        />
      </JseFloatingPanel>
    </div>
  );
}

// jsonschema-editor-vue/src/components/organisms/UiStructureEditor.vue
<script setup lang="ts">
import { computed, nextTick, ref } from "vue";
import type { UiElement } from "@jsonschema-editor/ui-schema";
import UiTreeNode from "../molecules/tree/UiTreeNode.vue";
import UiLayoutEditor from "./UiLayoutEditor.vue";
import UiAttributesPanel from "../molecules/panels/UiAttributesPanel.vue";
import JseFloatingPanel from "../molecules/JseFloatingPanel.vue";
import UiElementActions from "../molecules/UiElementActions.vue";
import {
  getUiElementAt,
  getUiElementLabel,
  isLayoutElement,
  moveUiElement,
  moveUiElementTo,
  removeUiElement,
  uiPathKey,
  type UiPath,
} from "../../utils/ui-editor";
import { useJseI18n } from "../../composables/useJseI18n";

const props = defineProps<{
  root: UiElement;
  selectedPath: UiPath;
}>();

const emit = defineEmits<{
  "update:root": [root: UiElement];
  "update:selectedPath": [path: UiPath];
}>();

const { t } = useJseI18n();

const viewMode = ref<"tree" | "layout">("layout");
const expandedKeys = ref(new Set<string>(["root"]));
const dragSourcePath = ref<UiPath | null>(null);
const addDialogOpen = ref(false);
const attributesDialogOpen = ref(false);
const addTargetPath = ref<UiPath>([]);
const attributesTargetPath = ref<UiPath>([]);
const addPanelRef = ref<InstanceType<typeof JseFloatingPanel> | null>(null);
const attributesPanelRef = ref<InstanceType<typeof JseFloatingPanel> | null>(null);

const attributesPanelTitle = computed(() => {
  try {
    const element = getUiElementAt(props.root, attributesTargetPath.value);
    const label = getUiElementLabel(element);
    return t("uiStructure.attributesTitle", { label });
  } catch {
    return t("uiStructure.attributesFallback");
  }
});

const selectedLabel = computed(() => {
  try {
    const element = getUiElementAt(props.root, props.selectedPath);
    return getUiElementLabel(element);
  } catch {
    return t("uiStructure.noSelection");
  }
});

function patchRoot(next: UiElement, path?: UiPath) {
  emit("update:root", next);
  if (path) emit("update:selectedPath", path);
}

function selectPath(path: UiPath) {
  emit("update:selectedPath", path);
}

function togglePath(path: UiPath) {
  const key = uiPathKey(path);
  const next = new Set(expandedKeys.value);
  if (next.has(key)) next.delete(key);
  else next.add(key);
  expandedKeys.value = next;
}

async function anchorPanel(
  panelRef: InstanceType<typeof JseFloatingPanel> | null,
  event: MouseEvent,
) {
  await nextTick();
  const target = event.currentTarget;
  const row =
    target instanceof HTMLElement
      ? (target.closest(".jse-tree-node__row") ?? target.closest(".jse-layout-block__header"))
      : null;
  if (row instanceof HTMLElement) panelRef?.anchorNear(row);
}

async function openAddDialog(path: UiPath, event: MouseEvent) {
  attributesDialogOpen.value = false;
  addTargetPath.value = path;
  emit("update:selectedPath", path);
  addDialogOpen.value = true;
  await anchorPanel(addPanelRef.value, event);
}

async function openAttributesDialog(path: UiPath, event: MouseEvent) {
  addDialogOpen.value = false;
  attributesTargetPath.value = path;
  emit("update:selectedPath", path);
  attributesDialogOpen.value = true;
  await anchorPanel(attributesPanelRef.value, event);
}

function deleteAtPath(path: UiPath) {
  if (path.length === 0) return;
  patchRoot(removeUiElement(props.root, path), []);
}

function expandPath(path: UiPath) {
  expandedKeys.value = new Set([...expandedKeys.value, uiPathKey(path)]);
}

function onRootUpdated(next: UiElement) {
  patchRoot(next);
  expandPath(addTargetPath.value);
}

function onDragStart(path: UiPath) {
  dragSourcePath.value = path;
}

function onDragEnd() {
  dragSourcePath.value = null;
}

function onTreeDrop(targetPath: UiPath, sourcePath: UiPath) {
  dragSourcePath.value = null;
  if (uiPathKey(sourcePath) === uiPathKey(targetPath)) return;

  const sourceParent = sourcePath.slice(0, -1);
  const targetParent = targetPath.slice(0, -1);

  if (uiPathKey(sourceParent) === uiPathKey(targetParent)) {
    patchRoot(moveUiElement(props.root, sourcePath, targetPath));
    return;
  }

  const targetElement = getUiElementAt(props.root, targetPath);
  if (isLayoutElement(targetElement)) {
    patchRoot(
      moveUiElementTo(props.root, sourcePath, targetPath, targetElement.elements.length),
      sourcePath,
    );
    return;
  }

  patchRoot(
    moveUiElementTo(props.root, sourcePath, targetParent, targetPath[targetPath.length - 1]),
    sourcePath,
  );
}
</script>

<template>
  <div class="jse-structure-editor">
    <div class="jse-structure-editor__view-toggle" role="tablist" :aria-label="t('uiStructure.viewToggleAria')">
      <button
        type="button"
        role="tab"
        class="jse-structure-editor__view-tab"
        :class="{ 'jse-structure-editor__view-tab--active': viewMode === 'layout' }"
        :aria-selected="viewMode === 'layout'"
        @click="viewMode = 'layout'"
      >
        {{ t("uiStructure.viewLayout") }}
      </button>
      <button
        type="button"
        role="tab"
        class="jse-structure-editor__view-tab"
        :class="{ 'jse-structure-editor__view-tab--active': viewMode === 'tree' }"
        :aria-selected="viewMode === 'tree'"
        @click="viewMode = 'tree'"
      >
        {{ t("uiStructure.viewTree") }}
      </button>
    </div>

    <p class="jse-structure-editor__hint jse-structure-editor__hint--top">
      <template v-if="viewMode === 'layout'">
        {{ t("uiStructure.hintLayout") }}
      </template>
      <template v-else>
        {{ t("uiStructure.hintTree") }}
      </template>
    </p>

    <UiLayoutEditor
      v-if="viewMode === 'layout'"
      :root="root"
      :selected-path="selectedPath"
      @update:root="patchRoot($event)"
      @update:selected-path="selectPath"
      @add="openAddDialog"
      @edit="openAttributesDialog"
      @delete="deleteAtPath"
    />

    <div
      v-else
      class="jse-structure-editor__tree"
      role="tree"
      :aria-label="t('uiStructure.treeAria')"
      @dragend="onDragEnd"
    >
      <UiTreeNode
        :root="root"
        :path="[]"
        :selected-path="selectedPath"
        :expanded-keys="expandedKeys"
        :drag-source-path="dragSourcePath"
        @select="selectPath"
        @toggle="togglePath"
        @add="openAddDialog"
        @edit="openAttributesDialog"
        @delete="deleteAtPath"
        @drag-start="onDragStart"
        @drop="onTreeDrop"
      />
    </div>

    <div class="jse-structure-editor__status" aria-live="polite">
      <span class="jse-structure-editor__status-label">{{ t("uiStructure.selected") }}</span>
      <span class="jse-structure-editor__status-name">{{ selectedLabel }}</span>
    </div>

    <JseFloatingPanel ref="addPanelRef" v-model="addDialogOpen" :title="t('uiStructure.addElement')">
      <UiElementActions
        :root="root"
        :target-path="addTargetPath"
        @update:root="onRootUpdated"
        @done="addDialogOpen = false"
      />
    </JseFloatingPanel>

    <JseFloatingPanel
      ref="attributesPanelRef"
      v-model="attributesDialogOpen"
      :title="attributesPanelTitle"
      :initial-width="380"
      :initial-height="360"
    >
      <UiAttributesPanel
        :root="root"
        :selected-path="attributesTargetPath"
        @update:root="(next) => patchRoot(next)"
      />
    </JseFloatingPanel>
  </div>
</template>
