// jsonschema-editor-examples/src/site/components/organisms/ExamplesWorkspace.vue
<script setup lang="ts">
import { computed } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { JsonSchemaForm, JsonSchemaFormEditor, type JseLocale } from "@jsonschema-editor/vue";
import type { AppLocale } from "../../../app-routing";
import {
  exampleCopyFor,
  exampleManifests,
  type ExampleId,
  type ExampleManifest,
} from "../../../examples/catalog";
import { exampleEmbedCode } from "../../example-embed-code";
import SiteCodeEditor from "../atoms/SiteCodeEditor.vue";
import ExampleCatalog from "./ExampleCatalog.vue";

export type WorkspaceMode = "form" | "editor" | "json" | "code";
type JsonPane = "schema" | "ui" | "data";

const activeExampleId = defineModel<ExampleId>("activeExampleId", { required: true });
const schema = defineModel<SchemaDocument>("schema", { required: true });
const uiSchema = defineModel<UiSchema>("uiSchema", { required: true });
const formData = defineModel<Record<string, unknown>>("formData", { required: true });
const uiLabelMessages = defineModel<Partial<Record<JseLocale, Record<string, string>>>>(
  "uiLabelMessages",
  { required: true },
);
const mode = defineModel<WorkspaceMode>("mode", { required: true });
const jsonPane = defineModel<JsonPane>("jsonPane", { required: true });

const props = defineProps<{
  locale: AppLocale;
  fallbackLocale: AppLocale;
  labelLocales: JseLocale[];
  ui: {
    scenariosHeading: string;
    tabsAria: string;
    tabForm: string;
    tabEditor: string;
    tabJson: string;
    tabCode: string;
    formPanelAria: string;
    dataPanelTitle: string;
    editorPanelAria: string;
    jsonPanelAria: string;
    codePanelAria: string;
    jsonTabsAria: string;
    jsonSchema: string;
    jsonUi: string;
    jsonData: string;
  };
  visibleCategories: import("../../../examples/catalog").ExampleCategory[];
  activeExample: ExampleManifest;
  activeExampleCopy: { label: string; description: string };
  dataJson: string;
  activeJsonContent: string;
  exampleHref: (id: ExampleId) => string;
}>();

const emit = defineEmits<{
  selectExample: [id: ExampleId];
}>();

const embedCode = computed(() =>
  exampleEmbedCode({
    stack: "vue",
    exampleId: activeExampleId.value,
    locale: props.locale,
  }),
);
</script>

<template>
  <div class="app__workspace">
    <ExampleCatalog
      :locale="locale"
      :scenarios-heading="ui.scenariosHeading"
      :visible-categories="visibleCategories"
      :active-example-id="activeExampleId"
      :example-href="exampleHref"
      @select-example="emit('selectExample', $event)"
    />

    <main class="app__main">
      <select
        id="app-example-select"
        v-model="activeExampleId"
        class="app__example-select-hidden"
        tabindex="-1"
        aria-hidden="true"
      >
        <option v-for="entry in exampleManifests" :key="entry.id" :value="entry.id">
          {{ exampleCopyFor(entry, locale).label }}
        </option>
      </select>

      <header v-if="activeExample" class="app__scenario-header">
        <h1 id="json-schema-editor-beispiel" class="app__scenario-title">
          {{ activeExampleCopy.label }}
        </h1>
        <p class="app__scenario-desc">{{ activeExampleCopy.description }}</p>
      </header>

      <section class="app__panel">
        <div class="app__view-tabs" role="tablist" :aria-label="ui.tabsAria">
          <button
            type="button"
            role="tab"
            class="app__view-tab"
            :class="{ 'app__view-tab--active': mode === 'form' }"
            :aria-selected="mode === 'form'"
            aria-controls="app-panel-form"
            @click="mode = 'form'"
          >
            {{ ui.tabForm }}
          </button>
          <button
            type="button"
            role="tab"
            class="app__view-tab"
            :class="{ 'app__view-tab--active': mode === 'editor' }"
            :aria-selected="mode === 'editor'"
            aria-controls="app-panel-editor"
            @click="mode = 'editor'"
          >
            {{ ui.tabEditor }}
          </button>
          <button
            type="button"
            role="tab"
            class="app__view-tab"
            :class="{ 'app__view-tab--active': mode === 'json' }"
            :aria-selected="mode === 'json'"
            aria-controls="app-panel-json"
            @click="mode = 'json'"
          >
            {{ ui.tabJson }}
          </button>
          <button
            type="button"
            role="tab"
            class="app__view-tab"
            :class="{ 'app__view-tab--active': mode === 'code' }"
            :aria-selected="mode === 'code'"
            aria-controls="app-panel-code"
            @click="mode = 'code'"
          >
            {{ ui.tabCode }}
          </button>
        </div>

        <div
          v-if="mode === 'form'"
          id="app-panel-form"
          class="app__panel-body app__split"
          role="tabpanel"
          :aria-label="ui.formPanelAria"
        >
          <div class="app__split-main">
            <JsonSchemaForm
              v-model="formData"
              :schema="schema"
              :ui-schema="uiSchema"
              :locale="locale"
              :fallback-locale="fallbackLocale"
              :messages="uiLabelMessages"
            />
          </div>
          <aside class="app__split-side">
            <div class="app__code-header">{{ ui.dataPanelTitle }}</div>
            <!-- Machine-readable mirror for E2E; CodeMirror textContent is not reliable JSON. -->
            <pre class="app__form-data-output" hidden>{{ dataJson }}</pre>
            <SiteCodeEditor
              :value="dataJson"
              language="json"
              :aria-label="ui.dataPanelTitle"
            />
          </aside>
        </div>

        <div
          v-if="mode === 'editor'"
          id="app-panel-editor"
          class="app__panel-body"
          role="tabpanel"
          :aria-label="ui.editorPanelAria"
        >
          <JsonSchemaFormEditor
            v-model:schema="schema"
            v-model:ui-schema="uiSchema"
            v-model:messages="uiLabelMessages"
            :locale="locale"
            :fallback-locale="fallbackLocale"
            :label-locales="labelLocales"
          />
        </div>

        <div
          v-if="mode === 'json'"
          id="app-panel-json"
          class="app__panel-body app__json-view"
          role="tabpanel"
          :aria-label="ui.jsonPanelAria"
        >
          <div class="app__json-tabs" role="tablist" :aria-label="ui.jsonTabsAria">
            <button
              type="button"
              role="tab"
              class="app__json-tab"
              :class="{ 'app__json-tab--active': jsonPane === 'schema' }"
              :aria-selected="jsonPane === 'schema'"
              @click="jsonPane = 'schema'"
            >
              {{ ui.jsonSchema }}
            </button>
            <button
              type="button"
              role="tab"
              class="app__json-tab"
              :class="{ 'app__json-tab--active': jsonPane === 'ui' }"
              :aria-selected="jsonPane === 'ui'"
              @click="jsonPane = 'ui'"
            >
              {{ ui.jsonUi }}
            </button>
            <button
              type="button"
              role="tab"
              class="app__json-tab"
              :class="{ 'app__json-tab--active': jsonPane === 'data' }"
              :aria-selected="jsonPane === 'data'"
              @click="jsonPane = 'data'"
            >
              {{ ui.jsonData }}
            </button>
          </div>
          <SiteCodeEditor
            class="app__json-editor"
            :value="activeJsonContent"
            language="json"
            :aria-label="ui.jsonPanelAria"
          />
        </div>

        <div
          v-if="mode === 'code'"
          id="app-panel-code"
          class="app__panel-body app__code-view"
          role="tabpanel"
          :aria-label="ui.codePanelAria"
        >
          <SiteCodeEditor
            :value="embedCode"
            language="javascript"
            :aria-label="ui.codePanelAria"
          />
        </div>
      </section>
    </main>
  </div>
</template>

// jsonschema-editor-examples-react/src/site/components/organisms/ExamplesWorkspace.tsx
import { useMemo } from "react";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import type { UiSchema } from "@jsonschema-editor/ui-schema/bridge";
import { JsonSchemaForm, JsonSchemaFormEditor, type JseLocale } from "@jsonschema-editor/react";
import { exampleEmbedCode } from "../../../../../jsonschema-editor-examples/src/site/example-embed-code.js";
import {
  exampleCopyFor,
  exampleManifests,
  type ExampleCategory,
  type ExampleId,
  type ExampleManifest,
} from "../../../examples/catalog.js";
import type { AppLocale } from "../../../app-routing.js";
import { SiteCodeEditor } from "../atoms/SiteCodeEditor.js";
import { ExampleCatalog } from "./ExampleCatalog.js";

export type WorkspaceMode = "form" | "editor" | "json" | "code";
type JsonPane = "schema" | "ui" | "data";

interface ExamplesWorkspaceProps {
  locale: AppLocale;
  fallbackLocale: AppLocale;
  labelLocales: readonly JseLocale[];
  ui: {
    scenariosHeading: string;
    tabsAria: string;
    tabForm: string;
    tabEditor: string;
    tabJson: string;
    tabCode: string;
    formPanelAria: string;
    dataPanelTitle: string;
    editorPanelAria: string;
    jsonPanelAria: string;
    codePanelAria: string;
    jsonTabsAria: string;
    jsonSchema: string;
    jsonUi: string;
    jsonData: string;
  };
  visibleCategories: ExampleCategory[];
  activeExampleId: ExampleId;
  activeExample: ExampleManifest;
  activeExampleCopy: { label: string; description: string };
  schema: SchemaDocument;
  uiSchema: UiSchema;
  formData: Record<string, unknown>;
  uiLabelMessages: Partial<Record<JseLocale, Record<string, string>>>;
  mode: WorkspaceMode;
  jsonPane: JsonPane;
  dataJson: string;
  activeJsonContent: string;
  exampleHref: (id: ExampleId) => string;
  onSelectExample: (id: ExampleId) => void;
  onActiveExampleIdChange: (id: ExampleId) => void;
  onFormDataChange: (data: Record<string, unknown>) => void;
  onSchemaChange: (schema: SchemaDocument) => void;
  onUiSchemaChange: (uiSchema: UiSchema) => void;
  onMessagesChange: (messages: Partial<Record<JseLocale, Record<string, string>>>) => void;
  onModeChange: (mode: WorkspaceMode) => void;
  onJsonPaneChange: (pane: JsonPane) => void;
}

export function ExamplesWorkspace({
  locale,
  fallbackLocale,
  labelLocales,
  ui,
  visibleCategories,
  activeExampleId,
  activeExample,
  activeExampleCopy,
  schema,
  uiSchema,
  formData,
  uiLabelMessages,
  mode,
  jsonPane,
  dataJson,
  activeJsonContent,
  exampleHref,
  onSelectExample,
  onActiveExampleIdChange,
  onFormDataChange,
  onSchemaChange,
  onUiSchemaChange,
  onMessagesChange,
  onModeChange,
  onJsonPaneChange,
}: ExamplesWorkspaceProps) {
  const embedCode = useMemo(
    () =>
      exampleEmbedCode({
        stack: "react",
        exampleId: activeExampleId,
        locale,
      }),
    [activeExampleId, locale],
  );

  return (
    <div className="app__workspace">
      <ExampleCatalog
        locale={locale}
        scenariosHeading={ui.scenariosHeading}
        visibleCategories={visibleCategories}
        activeExampleId={activeExampleId}
        exampleHref={exampleHref}
        onSelectExample={onSelectExample}
      />

      <main className="app__main">
        <select
          id="app-example-select"
          className="app__example-select-hidden"
          tabIndex={-1}
          aria-hidden="true"
          value={activeExampleId}
          onChange={(event) => onActiveExampleIdChange(event.target.value as ExampleId)}
        >
          {exampleManifests.map((entry) => (
            <option key={entry.id} value={entry.id}>
              {exampleCopyFor(entry, locale).label}
            </option>
          ))}
        </select>

        {activeExample ? (
          <header className="app__scenario-header">
            <h1 id="json-schema-editor-beispiel" className="app__scenario-title">
              {activeExampleCopy.label}
            </h1>
            <p className="app__scenario-desc">{activeExampleCopy.description}</p>
          </header>
        ) : null}

        <section className="app__panel">
          <div className="app__view-tabs" role="tablist" aria-label={ui.tabsAria}>
            <button
              type="button"
              role="tab"
              className={`app__view-tab${mode === "form" ? " app__view-tab--active" : ""}`}
              aria-selected={mode === "form"}
              aria-controls="app-panel-form"
              onClick={() => onModeChange("form")}
            >
              {ui.tabForm}
            </button>
            <button
              type="button"
              role="tab"
              className={`app__view-tab${mode === "editor" ? " app__view-tab--active" : ""}`}
              aria-selected={mode === "editor"}
              aria-controls="app-panel-editor"
              onClick={() => onModeChange("editor")}
            >
              {ui.tabEditor}
            </button>
            <button
              type="button"
              role="tab"
              className={`app__view-tab${mode === "json" ? " app__view-tab--active" : ""}`}
              aria-selected={mode === "json"}
              aria-controls="app-panel-json"
              onClick={() => onModeChange("json")}
            >
              {ui.tabJson}
            </button>
            <button
              type="button"
              role="tab"
              className={`app__view-tab${mode === "code" ? " app__view-tab--active" : ""}`}
              aria-selected={mode === "code"}
              aria-controls="app-panel-code"
              onClick={() => onModeChange("code")}
            >
              {ui.tabCode}
            </button>
          </div>

          {mode === "form" ? (
            <div
              id="app-panel-form"
              className="app__panel-body app__split"
              role="tabpanel"
              aria-label={ui.formPanelAria}
            >
              <div className="app__split-main">
                <JsonSchemaForm
                  schema={schema}
                  uiSchema={uiSchema}
                  data={formData}
                  onDataChange={onFormDataChange}
                  locale={locale}
                  fallbackLocale={fallbackLocale}
                  messages={uiLabelMessages}
                  validationMode="blur"
                />
              </div>
              <aside className="app__split-side">
                <div className="app__code-header">{ui.dataPanelTitle}</div>
                {/* Machine-readable mirror for E2E; CodeMirror textContent is not reliable JSON. */}
                <pre className="app__form-data-output" hidden>
                  {dataJson}
                </pre>
                <SiteCodeEditor
                  value={dataJson}
                  language="json"
                  ariaLabel={ui.dataPanelTitle}
                />
              </aside>
            </div>
          ) : null}

          {mode === "editor" ? (
            <div
              id="app-panel-editor"
              className="app__panel-body"
              role="tabpanel"
              aria-label={ui.editorPanelAria}
            >
              <JsonSchemaFormEditor
                key={activeExampleId}
                schema={schema}
                uiSchema={uiSchema}
                onSchemaChange={onSchemaChange}
                onUiSchemaChange={onUiSchemaChange}
                locale={locale}
                fallbackLocale={fallbackLocale}
                labelLocales={labelLocales}
                messages={uiLabelMessages}
                onMessagesChange={onMessagesChange}
              />
            </div>
          ) : null}

          {mode === "json" ? (
            <div
              id="app-panel-json"
              className="app__panel-body app__json-view"
              role="tabpanel"
              aria-label={ui.jsonPanelAria}
            >
              <div className="app__json-tabs" role="tablist" aria-label={ui.jsonTabsAria}>
                {(["schema", "ui", "data"] as const).map((pane) => (
                  <button
                    key={pane}
                    type="button"
                    role="tab"
                    className={`app__json-tab${jsonPane === pane ? " app__json-tab--active" : ""}`}
                    aria-selected={jsonPane === pane}
                    onClick={() => onJsonPaneChange(pane)}
                  >
                    {pane === "schema"
                      ? ui.jsonSchema
                      : pane === "ui"
                        ? ui.jsonUi
                        : ui.jsonData}
                  </button>
                ))}
              </div>
              <SiteCodeEditor
                value={activeJsonContent}
                language="json"
                ariaLabel={ui.jsonPanelAria}
              />
            </div>
          ) : null}

          {mode === "code" ? (
            <div
              id="app-panel-code"
              className="app__panel-body app__code-view"
              role="tabpanel"
              aria-label={ui.codePanelAria}
            >
              <SiteCodeEditor
                value={embedCode}
                language="javascript"
                ariaLabel={ui.codePanelAria}
              />
            </div>
          ) : null}
        </section>
      </main>
    </div>
  );
}
