// jsonschema-editor-vue/src/components/molecules/attributes/JsonAttributeControl.vue
<script setup lang="ts">
import JseTextarea from "../../atoms/JseTextarea.vue";
import JseFormField from "../JseFormField.vue";

defineProps<{
  label: string;
  readonly?: boolean;
}>();

const modelValue = defineModel<string>({ default: "" });
</script>

<template>
  <JseFormField :label="label">
    <JseTextarea v-model="modelValue" :disabled="readonly" :rows="3" />
  </JseFormField>
</template>

// jsonschema-editor-react/src/components/molecules/attributes/JsonAttributeControl.tsx
import { JseTextarea } from "../../atoms/JseTextarea.js";
import { JseFormField } from "../JseFormField.js";
import type { AttributeControlProps } from "../../../types/attribute-control-props.js";

export function JsonAttributeControl({
  label,
  readonly,
  modelValue,
  onModelValueChange,
}: AttributeControlProps) {
  const textValue =
    typeof modelValue === "string"
      ? modelValue
      : modelValue === undefined
        ? ""
        : JSON.stringify(modelValue, null, 2);

  return (
    <JseFormField label={label}>
      <JseTextarea
        modelValue={textValue}
        disabled={readonly}
        rows={3}
        onModelValueChange={(value) => {
          try {
            onModelValueChange?.(JSON.parse(value));
          } catch {
            onModelValueChange?.(value);
          }
        }}
      />
    </JseFormField>
  );
}
