// jsonschema-editor-vue/src/components/molecules/attributes/NumberAttributeControl.vue
<script setup lang="ts">
import JseInput from "../../atoms/JseInput.vue";
import JseFormField from "../JseFormField.vue";

defineProps<{
  label: string;
  readonly?: boolean;
}>();

const modelValue = defineModel<number | undefined>();
</script>

<template>
  <JseFormField :label="label">
    <JseInput
      :model-value="modelValue ?? ''"
      type="number"
      :disabled="readonly"
      @update:model-value="modelValue = $event === '' ? undefined : Number($event)"
    />
  </JseFormField>
</template>

// jsonschema-editor-react/src/components/molecules/attributes/NumberAttributeControl.tsx
import { JseInput } from "../../atoms/JseInput.js";
import { JseFormField } from "../JseFormField.js";
import type { AttributeControlProps } from "../../../types/attribute-control-props.js";

export function NumberAttributeControl({
  label,
  readonly,
  modelValue,
  onModelValueChange,
}: AttributeControlProps) {
  const numericValue =
    typeof modelValue === "number" ? modelValue : modelValue === undefined ? "" : String(modelValue);

  return (
    <JseFormField label={label}>
      <JseInput
        type="number"
        modelValue={numericValue}
        disabled={readonly}
        onModelValueChange={(value) =>
          onModelValueChange?.(value === "" ? undefined : Number(value))
        }
      />
    </JseFormField>
  );
}
