// jsonschema-editor-vue/src/components/molecules/panels/SchemaAttributesPanel.vue
<script setup lang="ts">
import { toRef } from "vue";
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import JseCheckbox from "../../atoms/JseCheckbox.vue";
import JseInput from "../../atoms/JseInput.vue";
import JseFormField from "../JseFormField.vue";
import JseSelect from "../../atoms/JseSelect.vue";
import ArrayItemsTypeControl from "../ArrayItemsTypeControl.vue";
import AttributeControlResolver from "../attributes/AttributeControlResolver.vue";
import SchemaFieldBulkActions from "./SchemaFieldBulkActions.vue";
import { useJseI18n } from "../../../composables/useJseI18n";
import { useEditorContext } from "../../../composables/useEditorContext";
import { useSchemaAttributesPanel } from "../../../composables/useSchemaAttributesPanel";
import type { SchemaPath } from "../../../utils/schema-editor";

const props = defineProps<{
  document: SchemaDocument;
  selectedPath: SchemaPath;
}>();

const emit = defineEmits<{
  "update:document": [document: SchemaDocument];
  "update:selectedPath": [path: SchemaPath];
}>();

const { t } = useJseI18n();
const { readonly } = useEditorContext();

const {
  propertyNameInput,
  propertyNameError,
  selectedDefRef,
  selectedNode,
  isRefNode,
  isDefRoot,
  availableDefs,
  parentObject,
  propertyName,
  showPropertyName,
  attributeFields,
  isRequired,
  showItemsTypeControl,
  itemsTypeKind,
  showBulkFieldActions,
  commitPropertyRename,
  readAttribute,
  updateAttribute,
  setRequired,
  commitRefChange,
  setItemsType,
  applyBulkFieldAttribute,
} = useSchemaAttributesPanel(toRef(props, "document"), toRef(props, "selectedPath"), emit);
</script>

<template>
  <div class="jse-attributes-panel">
    <JseFormField
      v-if="showPropertyName"
      :label="isDefRoot ? t('schemaAttributes.defName') : t('schemaAttributes.fieldName')"
    >
      <JseInput
        :model-value="propertyNameInput"
        :placeholder="isDefRoot ? t('schemaAttributes.defNamePlaceholder') : t('schemaAttributes.fieldNamePlaceholder')"
        :readonly="readonly"
        @update:model-value="(value) => { propertyNameInput = String(value); propertyNameError = ''; }"
        @blur="commitPropertyRename"
        @keydown.enter="($event.target as HTMLInputElement).blur()"
      />
      <p v-if="propertyNameError" class="jse-element-actions__error">{{ propertyNameError }}</p>
    </JseFormField>

    <JseFormField v-if="isRefNode" :label="t('schemaAttributes.ref')">
      <JseSelect
        :model-value="selectedDefRef"
        class="jse-field__input"
        :disabled="readonly"
        @update:model-value="(value) => { selectedDefRef = String(value); commitRefChange(); }"
      >
        <option v-for="name in availableDefs" :key="name" :value="name">
          #/$defs/{{ name }}
        </option>
      </JseSelect>
    </JseFormField>

    <AttributeControlResolver
      v-for="field in attributeFields"
      :key="field.name"
      :node="selectedNode"
      :attribute-name="field.name"
      :label="t(field.labelKey)"
      mode="schema"
      :document="document"
      :readonly="readonly"
      :model-value="readAttribute(field.name)"
      @update:model-value="updateAttribute(field.name, $event)"
    />

    <JseFormField
      v-if="parentObject && propertyName && !isDefRoot"
      boolean
      :label="t('schemaAttributes.required')"
    >
      <JseCheckbox
        :model-value="isRequired"
        :disabled="readonly"
        @update:model-value="setRequired($event)"
      />
    </JseFormField>

    <JseFormField v-if="showItemsTypeControl && !readonly" :label="t('schemaAttributes.itemsType')">
      <ArrayItemsTypeControl compact :current-kind="itemsTypeKind" @select="setItemsType" />
    </JseFormField>

    <SchemaFieldBulkActions
      v-if="showBulkFieldActions && !readonly"
      @apply="applyBulkFieldAttribute"
    />
  </div>
</template>

// jsonschema-editor-react/src/components/molecules/panels/SchemaAttributesPanel.tsx
import type { SchemaDocument } from "@jsonschema-editor/json-schema";
import { JseCheckbox } from "../../atoms/JseCheckbox.js";
import { JseInput } from "../../atoms/JseInput.js";
import { JseSelect } from "../../atoms/JseSelect.js";
import { JseFormField } from "../JseFormField.js";
import { ArrayItemsTypeControl } from "../ArrayItemsTypeControl.js";
import { AttributeControlResolver } from "../attributes/AttributeControlResolver.js";
import { SchemaFieldBulkActions } from "./SchemaFieldBulkActions.js";
import { useEditorContext } from "../../../context/EditorContext.js";
import { useJseI18n } from "../../../context/JseI18nContext.js";
import { useSchemaAttributesPanel } from "../../../hooks/useSchemaAttributesPanel.js";
import type { SchemaPath } from "../../../utils/schema-editor.js";

export interface SchemaAttributesPanelProps {
  document: SchemaDocument;
  selectedPath: SchemaPath;
  onDocumentChange: (document: SchemaDocument) => void;
  onSelectedPathChange: (path: SchemaPath) => void;
}

export function SchemaAttributesPanel({
  document,
  selectedPath,
  onDocumentChange,
  onSelectedPathChange,
}: SchemaAttributesPanelProps) {
  const { t } = useJseI18n();
  const { readonly } = useEditorContext();

  const {
    propertyNameInput,
    setPropertyNameInput,
    propertyNameError,
    setPropertyNameError,
    selectedDefRef,
    setSelectedDefRef,
    selectedNode,
    isRefNode,
    isDefRoot,
    availableDefs,
    parentObject,
    propertyName,
    showPropertyName,
    attributeFields,
    isRequired,
    showItemsTypeControl,
    itemsTypeKind,
    showBulkFieldActions,
    commitPropertyRename,
    readAttribute,
    updateAttribute,
    setRequired,
    commitRefChange,
    setItemsType,
    applyBulkFieldAttribute,
  } = useSchemaAttributesPanel(document, selectedPath, {
    onDocumentChange,
    onSelectedPathChange,
  });

  return (
    <div className="jse-attributes-panel">
      {showPropertyName ? (
        <JseFormField
          label={
            isDefRoot ? t("schemaAttributes.defName") : t("schemaAttributes.fieldName")
          }
        >
          <JseInput
            modelValue={propertyNameInput}
            readOnly={readonly}
            placeholder={
              isDefRoot
                ? t("schemaAttributes.defNamePlaceholder")
                : t("schemaAttributes.fieldNamePlaceholder")
            }
            onModelValueChange={(value) => {
              setPropertyNameInput(String(value));
              setPropertyNameError("");
            }}
            onBlur={commitPropertyRename}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                (event.target as HTMLInputElement).blur();
              }
            }}
          />
          {propertyNameError ? (
            <p className="jse-element-actions__error">{propertyNameError}</p>
          ) : null}
        </JseFormField>
      ) : null}

      {isRefNode ? (
        <JseFormField label={t("schemaAttributes.ref")}>
          <JseSelect
            modelValue={selectedDefRef}
            className="jse-field__input"
            disabled={readonly}
            onModelValueChange={(value) => {
              setSelectedDefRef(String(value));
              commitRefChange();
            }}
          >
            {availableDefs.map((name) => (
              <option key={name} value={name}>
                #/$defs/{name}
              </option>
            ))}
          </JseSelect>
        </JseFormField>
      ) : null}

      {attributeFields.map((field) => (
        <AttributeControlResolver
          key={field.name}
          node={selectedNode}
          attributeName={field.name}
          label={t(field.labelKey)}
          mode="schema"
          document={document}
          readonly={readonly}
          modelValue={readAttribute(field.name)}
          onModelValueChange={(value) => updateAttribute(field.name, value)}
        />
      ))}

      {parentObject && propertyName && !isDefRoot ? (
        <JseFormField boolean label={t("schemaAttributes.required")}>
          <JseCheckbox
            modelValue={isRequired}
            disabled={readonly}
            onModelValueChange={setRequired}
          />
        </JseFormField>
      ) : null}

      {showItemsTypeControl && !readonly ? (
        <JseFormField label={t("schemaAttributes.itemsType")}>
          <ArrayItemsTypeControl
            compact
            currentKind={itemsTypeKind}
            onSelect={setItemsType}
          />
        </JseFormField>
      ) : null}

      {showBulkFieldActions && !readonly ? (
        <SchemaFieldBulkActions onApply={applyBulkFieldAttribute} />
      ) : null}
    </div>
  );
}
