// jsonschema-editor-react-extensions/src/components/ExtendedFormatFormField.tsx
import { useMemo } from "react";
import { StringSchema } from "@jsonschema-editor/json-schema";
import {
  JseInput,
  JseSchemaFormField,
  useFormFieldLabel,
  useScopedField,
  type FormFieldProps,
} from "@jsonschema-editor/react";

export function ExtendedFormatFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  const format = resolvedSchema instanceof StringSchema ? resolvedSchema.format : undefined;

  const inputType = useMemo((): string => {
    switch (format) {
      case "email":
        return "email";
      case "uri":
        return "url";
      case "phone":
        return "tel";
      default:
        return "text";
    }
  }, [format]);

  const autocomplete = useMemo((): string | undefined => {
    switch (format) {
      case "email":
        return "email";
      case "uri":
        return "url";
      case "phone":
        return "tel";
      default:
        return undefined;
    }
  }, [format]);

  const linkHref = useMemo((): string | null => {
    if (format !== "uri") return null;
    const raw = value;
    if (typeof raw !== "string" || raw.length === 0) return null;
    try {
      const parsed = new URL(raw);
      if (parsed.protocol === "http:" || parsed.protocol === "https:") return raw;
    } catch {
      return null;
    }
    return null;
  }, [format, value]);

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      <JseInput
        className="jse-field__input jse-field__input--format"
        type={inputType}
        autoComplete={autocomplete}
        modelValue={typeof value === "string" ? value : String(value ?? "")}
        disabled={readonly}
        onModelValueChange={setValue}
      />
      {linkHref ? (
        <a
          className="jse-field__link"
          href={linkHref}
          target="_blank"
          rel="noopener noreferrer"
        >
          {linkHref}
        </a>
      ) : null}
    </JseSchemaFormField>
  );
}

// jsonschema-editor-vue-extensions/src/components/ExtendedFormatFormField.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { SchemaNode } from "@jsonschema-editor/json-schema";
import { StringSchema } from "@jsonschema-editor/json-schema";
import {
  JseInput,
  JseSchemaFormField,
  useFormFieldLabel,
  useScopedField,
} from "@jsonschema-editor/vue";

const props = defineProps<{
  schema: SchemaNode;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope);
const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);

const format = computed(() => {
  const node = resolvedSchema.value;
  return node instanceof StringSchema ? node.format : undefined;
});

const inputType = computed((): string => {
  switch (format.value) {
    case "email":
      return "email";
    case "uri":
      return "url";
    case "phone":
      return "tel";
    default:
      return "text";
  }
});

const autocomplete = computed((): string | undefined => {
  switch (format.value) {
    case "email":
      return "email";
    case "uri":
      return "url";
    case "phone":
      return "tel";
    default:
      return undefined;
  }
});

const linkHref = computed((): string | null => {
  if (format.value !== "uri") return null;
  const raw = value.value;
  if (typeof raw !== "string" || raw.length === 0) return null;
  try {
    const parsed = new URL(raw);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") return raw;
  } catch {
    return null;
  }
  return null;
});
</script>

<template>
  <JseSchemaFormField :label="displayLabel" :description="description" :scope="scope">
    <JseInput
      :model-value="value as string"
      class="jse-field__input jse-field__input--format"
      :type="inputType"
      :autocomplete="autocomplete"
      :disabled="readonly"
      @update:model-value="value = $event"
    />
    <a
      v-if="linkHref"
      class="jse-field__link"
      :href="linkHref"
      target="_blank"
      rel="noopener noreferrer"
    >
      {{ linkHref }}
    </a>
  </JseSchemaFormField>
</template>
