// jsonschema-editor-react-extensions/src/components/SwitchFormField.tsx
import {
  JseSwitch,
  JseSchemaFormField,
  useFormFieldLabel,
  useScopedField,
  type FormFieldProps,
} from "@jsonschema-editor/react";

export function SwitchFormField({
  schema,
  document,
  scope,
  label,
  i18nKey,
  readonly,
}: FormFieldProps) {
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  return (
    <JseSchemaFormField
      label={displayLabel}
      description={description}
      scope={scope}
      boolean
    >
      <JseSwitch
        modelValue={value === true}
        disabled={readonly}
        onModelValueChange={setValue}
      />
    </JseSchemaFormField>
  );
}

// jsonschema-editor-vue-extensions/src/components/SwitchFormField.vue
<script setup lang="ts">
import { toRef } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import {
  useFormFieldLabel,
  useScopedField,
  JseSwitch,
  JseSchemaFormField,
} from "@jsonschema-editor/vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope, documentRef);
const { displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);
</script>

<template>
  <JseSchemaFormField boolean :label="displayLabel" :description="description" :scope="scope">
    <JseSwitch
      :model-value="value === true"
      :disabled="readonly"
      @update:model-value="value = $event"
    />
  </JseSchemaFormField>
</template>
