// jsonschema-editor-vue/src/components/molecules/JseFloatingPanel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, watch } from "vue";
import { useFloatingPanel } from "../../composables/useFloatingPanel";
import JseIconButton from "../atoms/JseIconButton.vue";
import { useJseI18n } from "../../composables/useJseI18n";

const props = withDefaults(
  defineProps<{
    modelValue: boolean;
    title: string;
    initialX?: number;
    initialY?: number;
    initialWidth?: number;
    initialHeight?: number;
  }>(),
  {
    initialX: 24,
    initialY: 24,
    initialWidth: 320,
    initialHeight: 280,
  },
);

const emit = defineEmits<{ "update:modelValue": [open: boolean] }>();

const { t } = useJseI18n();

const panel = useFloatingPanel({
  initialX: props.initialX,
  initialY: props.initialY,
  initialWidth: props.initialWidth,
  initialHeight: props.initialHeight,
});

const panelStyle = computed(() => ({
  left: `${panel.rect.value.x}px`,
  top: `${panel.rect.value.y}px`,
  width: `${panel.rect.value.width}px`,
  height: panel.minimized.value ? `${panel.minimizedHeight}px` : `${panel.rect.value.height}px`,
}));

watch(
  () => props.modelValue,
  (value) => {
    if (value) panel.show();
    else panel.hide();
  },
  { flush: "sync" },
);

watch(
  panel.open,
  (value) => {
    if (value !== props.modelValue) emit("update:modelValue", value);
  },
  { flush: "sync" },
);

function close() {
  emit("update:modelValue", false);
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    event.preventDefault();
    close();
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (open) window.addEventListener("keydown", onKeydown);
    else window.removeEventListener("keydown", onKeydown);
  },
);

onBeforeUnmount(() => {
  window.removeEventListener("keydown", onKeydown);
});

function anchorNear(element: HTMLElement) {
  const bounds = element.getBoundingClientRect();
  panel.show({
    x: Math.min(bounds.right + 8, window.innerWidth - panel.rect.value.width - 16),
    y: Math.max(16, bounds.top),
  });
}

defineExpose({ anchorNear, show: panel.show });
</script>

<template>
  <Teleport to="body">
    <div
      v-if="modelValue"
      class="jse-floating-panel"
      :style="panelStyle"
      role="dialog"
      :aria-label="title"
    >
      <header class="jse-floating-panel__header" @pointerdown="panel.startDrag">
        <span class="jse-floating-panel__title">{{ title }}</span>
        <div class="jse-floating-panel__controls">
          <JseIconButton
            :label="panel.minimized.value ? t('panel.maximize') : t('panel.minimize')"
            @click.stop="panel.toggleMinimized()"
          >
            {{ panel.minimized.value ? "□" : "−" }}
          </JseIconButton>
          <JseIconButton :label="t('panel.close')" @click.stop="close">×</JseIconButton>
        </div>
      </header>

      <div v-show="!panel.minimized.value" class="jse-floating-panel__body">
        <slot />
      </div>

      <div
        v-if="!panel.minimized.value"
        class="jse-floating-panel__resize"
        aria-hidden="true"
        @pointerdown="panel.startResize"
      />
    </div>
  </Teleport>
</template>

// jsonschema-editor-react/src/components/molecules/JseFloatingPanel.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import {
  anchorPanelNearElement,
  useFloatingPanel,
} from "../../hooks/useFloatingPanel.js";
import { useJseI18n } from "../../context/JseI18nContext.js";
import { JseIconButton } from "../atoms/JseIconButton.js";

export interface JseFloatingPanelHandle {
  anchorNear: (element: HTMLElement) => void;
  show: () => void;
}

export interface JseFloatingPanelProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  initialX?: number;
  initialY?: number;
  initialWidth?: number;
  initialHeight?: number;
  children: ReactNode;
}

export const JseFloatingPanel = forwardRef<JseFloatingPanelHandle, JseFloatingPanelProps>(
  function JseFloatingPanel(
    {
      open,
      onOpenChange,
      title,
      initialX = 24,
      initialY = 24,
      initialWidth = 320,
      initialHeight = 280,
      children,
    },
    ref,
  ) {
    const { t } = useJseI18n();
    const panel = useFloatingPanel({
      initialX,
      initialY,
      initialWidth,
      initialHeight,
    });
    const rectRef = useRef(panel.rect);
    rectRef.current = panel.rect;

    useEffect(() => {
      if (open) panel.show();
      else panel.hide();
    }, [open, panel]);

    useImperativeHandle(ref, () => ({
      anchorNear(element: HTMLElement) {
        const anchor = anchorPanelNearElement(rectRef.current, element, rectRef.current.width);
        panel.show(anchor);
        onOpenChange(true);
      },
      show() {
        panel.show();
        onOpenChange(true);
      },
    }));

    useEffect(() => {
      if (!open) return;

      function onKeydown(event: KeyboardEvent) {
        if (event.key === "Escape") {
          event.preventDefault();
          onOpenChange(false);
        }
      }

      window.addEventListener("keydown", onKeydown);
      return () => window.removeEventListener("keydown", onKeydown);
    }, [onOpenChange, open]);

    if (!open) return null;

    const panelStyle = {
      left: `${panel.rect.x}px`,
      top: `${panel.rect.y}px`,
      width: `${panel.rect.width}px`,
      height: panel.minimized ? `${panel.minimizedHeight}px` : `${panel.rect.height}px`,
    };

    return createPortal(
      <div
        className="jse-floating-panel"
        style={panelStyle}
        role="dialog"
        aria-label={title}
      >
        <header className="jse-floating-panel__header" onPointerDown={panel.startDrag}>
          <span className="jse-floating-panel__title">{title}</span>
          <div className="jse-floating-panel__controls">
            <JseIconButton
              label={panel.minimized ? t("panel.maximize") : t("panel.minimize")}
              onClick={(event) => {
                event.stopPropagation();
                panel.toggleMinimized();
              }}
            >
              {panel.minimized ? "□" : "−"}
            </JseIconButton>
            <JseIconButton
              label={t("panel.close")}
              onClick={(event) => {
                event.stopPropagation();
                onOpenChange(false);
              }}
            >
              ×
            </JseIconButton>
          </div>
        </header>

        {!panel.minimized ? (
          <div className="jse-floating-panel__body">{children}</div>
        ) : null}

        {!panel.minimized ? (
          <div
            className="jse-floating-panel__resize"
            aria-hidden="true"
            onPointerDown={panel.startResize}
          />
        ) : null}
      </div>,
      document.body,
    );
  },
);
