// jsonschema-editor-react/src/components/molecules/form/EnumFormField.tsx
import { useMemo } from "react";
import { useFormFieldLabel } from "../../../hooks/useFormFieldLabel.js";
import { useScopedField } from "../../../hooks/useScopedField.js";
import type { FormFieldProps } from "../../../types/form-field-props.js";
import { JseSelect } from "../../atoms/JseSelect.js";
import { JseSchemaFormField } from "./JseSchemaFormField.js";

export function EnumFormField(props: FormFieldProps) {
  const { schema, document, scope, label, i18nKey, readonly } = props;
  const { fieldSchema, value, setValue } = useScopedField(schema, scope, document);
  const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
    schema,
    scope,
    label,
    fieldSchema,
    i18nKey,
  );

  const enumValues = useMemo(() => resolvedSchema?.enumValues ?? [], [resolvedSchema]);

  return (
    <JseSchemaFormField label={displayLabel} description={description} scope={scope}>
      <JseSelect
        modelValue={value as string | number}
        className="jse-field__input"
        disabled={readonly}
        onModelValueChange={(next) => setValue(next)}
      >
        {enumValues.map((option) => (
          <option key={String(option)} value={option as string | number}>
            {String(option)}
          </option>
        ))}
      </JseSelect>
    </JseSchemaFormField>
  );
}

// jsonschema-editor-vue/src/components/molecules/form/EnumFormField.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import { useFormFieldLabel } from "../../../composables/useFormFieldLabel";
import { useScopedField } from "../../../composables/useScopedField";
import JseSelect from "../../atoms/JseSelect.vue";
import JseSchemaFormField from "./JseSchemaFormField.vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const labelRef = toRef(props, "label");
const i18nKeyRef = toRef(props, "i18nKey");
const rootData = defineModel<Record<string, unknown>>({ required: true });

const { fieldSchema, value } = useScopedField(rootSchema, rootData, props.scope, documentRef);
const { resolvedSchema, displayLabel, description } = useFormFieldLabel(
  rootSchema,
  props.scope,
  labelRef,
  fieldSchema,
  i18nKeyRef,
);

const enumValues = computed(() => resolvedSchema.value?.enumValues ?? []);
</script>

<template>
  <JseSchemaFormField :label="displayLabel" :description="description" :scope="scope">
    <JseSelect
      :model-value="value as string | number"
      class="jse-field__input"
      :disabled="readonly"
      @update:model-value="value = $event"
    >
      <option v-for="option in enumValues" :key="String(option)" :value="option as string | number">
        {{ option }}
      </option>
    </JseSelect>
  </JseSchemaFormField>
</template>
