// jsonschema-editor-react/src/components/molecules/form/SchemaFormFieldResolver.tsx
import type { ComponentType } from "react";
import { useMemo } from "react";
import { resolveCompositionAtScope } from "@jsonschema-editor/ui-schema/bridge";
import { useSchemaFormTypeRegistry } from "../../../context/RegistriesContext.js";
import { createFormFieldMatchContext } from "../../../registry/form-field-context.js";
import { isSchemaFieldHidden, isSchemaFieldReadOnly } from "../../../utils/field-behavior.js";
import type { FormFieldProps } from "../../../types/form-field-props.js";
import { useScopedField } from "../../../hooks/useScopedField.js";
import { DefaultFormField } from "./DefaultFormField.js";
import { OneOfFormField } from "./OneOfFormField.js";

export function SchemaFormFieldResolver(props: FormFieldProps) {
  const typeRegistry = useSchemaFormTypeRegistry();
  const { fieldSchema } = useScopedField(props.schema, props.scope, props.document);

  const oneOfComposition = useMemo(() => {
    const resolveRef = props.document
      ? (ref: string) => props.document!.resolveRef(ref)
      : undefined;
    return resolveCompositionAtScope(props.schema, props.scope, resolveRef);
  }, [props.document, props.schema, props.scope]);

  const matchContext = useMemo(
    () =>
      createFormFieldMatchContext({
        scope: props.scope,
        label: props.label,
        i18nKey: props.i18nKey,
        readonly: props.readonly,
        fieldSchema,
        rootSchema: props.schema,
      }),
    [fieldSchema, props.i18nKey, props.label, props.readonly, props.schema, props.scope],
  );

  if (isSchemaFieldHidden(fieldSchema)) {
    return null;
  }

  const readonly = isSchemaFieldReadOnly(fieldSchema, props.readonly);
  const node = fieldSchema ?? props.schema;
  const Resolved = oneOfComposition
    ? OneOfFormField
    : ((typeRegistry.resolve(node, matchContext) as ComponentType<FormFieldProps>) ??
      DefaultFormField);

  return <Resolved {...props} readonly={readonly} />;
}

// jsonschema-editor-vue/src/components/molecules/form/SchemaFormFieldResolver.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { SchemaDocument, SchemaNode } from "@jsonschema-editor/json-schema";
import { resolveCompositionAtScope } from "@jsonschema-editor/ui-schema/bridge";
import { useScopedField } from "../../../composables/useScopedField";
import { useSchemaFormTypeRegistry } from "../../../composables/useRegistries";
import { createFormFieldMatchContext } from "../../../registry/form-field-context";
import { isSchemaFieldHidden, isSchemaFieldReadOnly } from "../../../utils/field-behavior";
import DefaultFormField from "./DefaultFormField.vue";
import OneOfFormField from "./OneOfFormField.vue";

const props = defineProps<{
  schema: SchemaNode;
  document?: SchemaDocument;
  scope: string;
  label?: string;
  i18nKey?: string;
  readonly?: boolean;
}>();

const rootSchema = toRef(props, "schema");
const documentRef = toRef(props, "document");
const rootData = defineModel<Record<string, unknown>>({ required: true });
const typeRegistry = useSchemaFormTypeRegistry();
const { fieldSchema } = useScopedField(rootSchema, rootData, props.scope, documentRef);

const oneOfComposition = computed(() => {
  const resolveRef = documentRef.value
    ? (ref: string) => documentRef.value!.resolveRef(ref)
    : undefined;
  return resolveCompositionAtScope(props.schema, props.scope, resolveRef);
});

const matchContext = computed(() =>
  createFormFieldMatchContext({
    scope: props.scope,
    label: props.label,
    i18nKey: props.i18nKey,
    readonly: props.readonly,
    fieldSchema: fieldSchema.value,
    rootSchema: props.schema,
  }),
);

const resolvedComponent = computed(() => {
  if (oneOfComposition.value) return OneOfFormField;
  const node = fieldSchema.value ?? props.schema;
  return typeRegistry.resolve(node, matchContext.value) ?? DefaultFormField;
});

const isHidden = computed(() => isSchemaFieldHidden(fieldSchema.value));
const effectiveReadonly = computed(() =>
  isSchemaFieldReadOnly(fieldSchema.value, props.readonly),
);
</script>

<template>
  <component
    v-if="!isHidden"
    :is="resolvedComponent"
    v-model="rootData"
    :schema="schema"
    :document="document"
    :scope="scope"
    :label="label"
    :i18n-key="i18nKey"
    :readonly="effectiveReadonly"
  />
</template>
