// jsonschema-editor-examples-react/src/site/components/atoms/BrandLink.tsx
interface BrandLinkProps {
  href: string;
  brandPrefix: string;
  brandSuffix: string;
  onNavigate: () => void;
}

export function BrandLink({ href, brandPrefix, brandSuffix, onNavigate }: BrandLinkProps) {
  return (
    <a
      href={href}
      className="app__brand"
      aria-label="JSON Schema Editor"
      onClick={(event) => {
        event.preventDefault();
        onNavigate();
      }}
    >
      <span className="app__brand-prefix">{brandPrefix}</span>
      <span className="app__brand-suffix">{brandSuffix}</span>
    </a>
  );
}

// jsonschema-editor-examples/src/site/components/atoms/BrandLink.vue
<script setup lang="ts">
defineProps<{
  href: string;
  brandPrefix: string;
  brandSuffix: string;
}>();

const emit = defineEmits<{
  navigate: [];
}>();
</script>

<template>
  <a
    :href="href"
    class="app__brand"
    aria-label="JSON Schema Editor"
    @click.prevent="emit('navigate')"
  >
    <span class="app__brand-prefix">{{ brandPrefix }}</span>
    <span class="app__brand-suffix">{{ brandSuffix }}</span>
  </a>
</template>
