// jsonschema-editor-examples-react/src/site/components/atoms/LocaleSelect.tsx
import { localeOptions } from "../../../../../jsonschema-editor-examples/src/site/i18n/app-ui.js";
import type { AppLocale } from "../../../types/locale.js";

interface LocaleSelectProps {
  label: string;
  locale: AppLocale;
  onLocaleChange: (locale: AppLocale) => void;
}

export function LocaleSelect({ label, locale, onLocaleChange }: LocaleSelectProps) {
  return (
    <label className="app__locale-picker" htmlFor="app-locale-select">
      <span className="app__locale-label">{label}</span>
      <select
        id="app-locale-select"
        className="app__select"
        value={locale}
        onChange={(event) => onLocaleChange(event.target.value as AppLocale)}
      >
        {localeOptions.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  );
}

// jsonschema-editor-examples/src/site/components/atoms/LocaleSelect.vue
<script setup lang="ts">
import type { AppLocale } from "../../../app-routing";
import { localeOptions } from "../../i18n/app-ui";

const locale = defineModel<AppLocale>({ required: true });

defineProps<{
  label: string;
}>();
</script>

<template>
  <label class="app__locale-picker" for="app-locale-select">
    <span class="app__locale-label">{{ label }}</span>
    <select id="app-locale-select" v-model="locale" class="app__select">
      <option v-for="option in localeOptions" :key="option.value" :value="option.value">
        {{ option.label }}
      </option>
    </select>
  </label>
</template>
