// jsonschema-editor-examples-react/src/site/components/atoms/NavLink.tsx
interface NavLinkProps {
  href: string;
  active?: boolean;
  label: string;
  onNavigate: () => void;
}

export function NavLink({ href, active, label, onNavigate }: NavLinkProps) {
  return (
    <a
      href={href}
      className={`app__topnav-link${active ? " app__topnav-link--active" : ""}`}
      aria-current={active ? "page" : undefined}
      onClick={(event) => {
        event.preventDefault();
        onNavigate();
      }}
    >
      {label}
    </a>
  );
}

// jsonschema-editor-examples/src/site/components/atoms/NavLink.vue
<script setup lang="ts">
defineProps<{
  href: string;
  active?: boolean;
  label: string;
}>();

const emit = defineEmits<{
  navigate: [];
}>();
</script>

<template>
  <a
    :href="href"
    class="app__topnav-link"
    :class="{ 'app__topnav-link--active': active }"
    :aria-current="active ? 'page' : undefined"
    @click.prevent="emit('navigate')"
  >
    {{ label }}
  </a>
</template>
