// jsonschema-editor-examples-react/src/site/components/atoms/SiteCodeEditor.tsx
import { useEffect, useRef } from "react";
import {
  createSiteCodeEditor,
  type SiteCodeEditorHandle,
  type SiteCodeEditorLanguage,
} from "../../../../../jsonschema-editor-examples/src/site/code-editor/createSiteCodeEditor.js";

interface SiteCodeEditorProps {
  value: string;
  language: SiteCodeEditorLanguage;
  ariaLabel?: string;
}

export function SiteCodeEditor({ value, language, ariaLabel }: SiteCodeEditorProps) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<SiteCodeEditorHandle | null>(null);

  useEffect(() => {
    if (!hostRef.current) return;
    editorRef.current?.destroy();
    editorRef.current = createSiteCodeEditor(hostRef.current, { value, language });
    return () => {
      editorRef.current?.destroy();
      editorRef.current = null;
    };
    // Remount when language changes; value updates via the effect below.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional remount on language
  }, [language]);

  useEffect(() => {
    editorRef.current?.setValue(value);
  }, [value]);

  return (
    <div
      ref={hostRef}
      className="app__site-code-editor"
      role="region"
      aria-label={ariaLabel}
    />
  );
}

// jsonschema-editor-examples/src/site/components/atoms/SiteCodeEditor.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import {
  createSiteCodeEditor,
  type SiteCodeEditorHandle,
  type SiteCodeEditorLanguage,
} from "../../code-editor/createSiteCodeEditor";

const props = defineProps<{
  value: string;
  language: SiteCodeEditorLanguage;
  ariaLabel?: string;
}>();

const host = ref<HTMLElement | null>(null);
let editor: SiteCodeEditorHandle | null = null;

function mountEditor() {
  if (!host.value) return;
  editor?.destroy();
  editor = createSiteCodeEditor(host.value, {
    value: props.value,
    language: props.language,
  });
}

onMounted(mountEditor);

watch(
  () => props.language,
  () => {
    mountEditor();
  },
);

watch(
  () => props.value,
  (value) => {
    editor?.setValue(value);
  },
);

onBeforeUnmount(() => {
  editor?.destroy();
  editor = null;
});
</script>

<template>
  <div
    ref="host"
    class="app__site-code-editor"
    role="region"
    :aria-label="ariaLabel"
  />
</template>
